// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON layernorm per-row. Real NEON for the three passes:
//   1. sum (vectorized) → mean
//   2. sum of (x-mean)² (vectorized) → variance
//   3. (x - mean) * invStdDev * scale + bias (vectorized)
//
// Caller computes invStdDev = 1/sqrt(var+eps) on the scalar side.

#include "textflag.h"

#define VFADD_S4(m, n, d)  WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFSUB_S4(m, n, d)  WORD $(0x4EA0D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_S4(m, n, d)  WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFMLA_S4(m, n, d)  WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))
#define VMOV_B16(src, dst) WORD $(0x4EA01C00 | ((src) << 16) | ((src) << 5) | (dst))
#define VFADDP_S4(m, n, d) WORD $(0x6E30D400 | ((m) << 16) | ((n) << 5) | (d))
#define FADDP_S(n, d)      WORD $(0x7E30D800 | ((n) << 5) | (d))

// func LayerNormApplyRowNEONAsm(out, row, scale, bias *float32, n int, mean, invStdDev float32)
TEXT ·LayerNormApplyRowNEONAsm(SB), NOSPLIT, $0-48
    MOVD out+0(FP), R0
    MOVD row+8(FP), R1
    MOVD scale+16(FP), R2
    MOVD bias+24(FP), R3
    MOVD n+32(FP), R4
    FMOVS mean+40(FP), F16
    FMOVS invStdDev+44(FP), F17
    VDUP  V16.S[0], V16.S4
    VDUP  V17.S[0], V17.S4

ln_loop4:
    CMP  $4, R4
    BLT  ln_done
    VLD1.P 16(R1), [V0.S4]      // row
    VLD1.P 16(R2), [V1.S4]      // scale
    VLD1.P 16(R3), [V2.S4]      // bias
    VFSUB_S4(16, 0, 0)          // V0 = row - mean
    VFMUL_S4(17, 0, 0)          // V0 *= invStdDev
    VMOV_B16(2, 4)              // V4 = bias
    VFMLA_S4(1, 0, 4)           // V4 = bias + scale * V0
    VST1.P [V4.S4], 16(R0)
    SUB  $4, R4
    B    ln_loop4

ln_done:
    RET

// func LayerNormSquaredDiffSumNEONAsm(row *float32, n int, mean float32) float32
// Computes sum((row[i] - mean)²) — second pass of layernorm.
TEXT ·LayerNormSquaredDiffSumNEONAsm(SB), NOSPLIT, $0-28
    MOVD row+0(FP), R0
    MOVD n+8(FP), R1
    FMOVS mean+16(FP), F28 ; VDUP V28.S[0], V28.S4

    VEOR V29.B16, V29.B16, V29.B16

ssd_loop4:
    CMP  $4, R1
    BLT  ssd_reduce
    VLD1.P 16(R0), [V0.S4]
    VFSUB_S4(28, 0, 0)
    // V29 += V0 * V0 — FMLA Vd, Vn, Vm: Vd = Vd + Vn*Vm.
    VFMLA_S4(0, 0, 29)
    SUB  $4, R1
    B    ssd_loop4

ssd_reduce:
    VFADDP_S4(29, 29, 29)
    FADDP_S(29, 0)

    CBZ  R1, ssd_done

ssd_scalar_loop:
    FMOVS (R0), F1
    FSUBS F28, F1, F1
    FMULS F1, F1, F1
    FADDS F1, F0, F0
    ADD  $4, R0
    SUB  $1, R1
    CBNZ R1, ssd_scalar_loop

ssd_done:
    FMOVS F0, ret+24(FP)
    RET
