// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON float32 VSA helpers: contiguous vector copy for cyclic permute.

#include "textflag.h"

#define VMOV_B16(src, dst) WORD $(0x4EA01C00 | ((src) << 16) | ((src) << 5) | (dst))

// func VsaPermuteCopyF32NEONAsm(dst, src *float32, n int)
TEXT ·VsaPermuteCopyF32NEONAsm(SB), NOSPLIT, $0-24
	MOVD dst+0(FP), R0
	MOVD src+8(FP), R1
	MOVD n+16(FP), R2
	CBZ  R2, done

copy_loop4:
	CMP  $4, R2
	BLT  copy_scalar_tail
	VLD1.P 16(R1), [V0.S4]
	VST1.P [V0.S4], 16(R0)
	SUB  $4, R2
	B    copy_loop4

copy_scalar_tail:
	CBZ  R2, done
	FMOVS (R1), F0
	FMOVS F0, (R0)
	ADD  $4, R1
	ADD  $4, R0
	SUB  $1, R2
	B    copy_scalar_tail

done:
	RET
