#include "hawkes.metal"

using namespace metal;

HAWKES_LOG_PARTIAL_KERNEL(hawkes_log_likelihood_float32_partial, Float32HawkesMarkovStorage, float)
HAWKES_LOG_FINALIZE_KERNEL(hawkes_log_likelihood_float32_finalize, Float32HawkesMarkovStorage, float)
HAWKES_LOG_PARTIAL_KERNEL(hawkes_log_likelihood_float16_partial, Float16HawkesMarkovStorage, half)
HAWKES_LOG_FINALIZE_KERNEL(hawkes_log_likelihood_float16_finalize, Float16HawkesMarkovStorage, half)
HAWKES_LOG_PARTIAL_KERNEL(hawkes_log_likelihood_bfloat16_partial, BFloat16HawkesMarkovStorage, ushort)
HAWKES_LOG_FINALIZE_KERNEL(hawkes_log_likelihood_bfloat16_finalize, BFloat16HawkesMarkovStorage, ushort)
