// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON max-reduce for float32. Four parallel accumulators initialised
// to -inf, then FMAX across 16-lane stripes; folded with FMAX + FMAXV
// at the end to a single scalar. Used by softmax (the max shift) and
// by reduce_max / argmax kernels.
//
// Go scalar reference walks element-by-element with `if v > max { max
// = v }`. FCMGT (used internally by FMAX max-num) returns false on
// NaN, so FMAX/FMAXV match the scalar behavior bit-for-bit when no
// NaNs are present. With NaN, FMAX uses maxnum semantics (NaN→other)
// while the scalar reference returns the running max (which can be
// NaN once seen). Callers that need exact NaN semantics use the
// scalar path; for softmax this isn't an issue.

#include "textflag.h"

// FMAX vector .4S: 0|0|0|01110|0|sz|1|Rm|11110|1|Rn|Rd
// For sz=0 (single), Q=1: 0|1|0|01110|0|0|1|Rm|11110|1|Rn|Rd
// = 0_1_0_01110_001_Rm_111101_Rn_Rd
// = 0x4E20F400
#define VFMAX_S4(m, n, d) WORD $(0x4E20F400 | ((m) << 16) | ((n) << 5) | (d))
// FMAXV (vector across), single-precision .4S: reduces 4 S lanes of
// Vn into S Rd.
// 0|1|0|01110|10|11000|01111|10|Rn|Rd
// = 0x6E30F800
// Hmm need to verify. From ARM ARM: FMAXV V_d.S, V_n.4S
// 0|Q|U|01110|0|sz|11000|01111|10|Rn|Rd
// For Q=1, sz=0, U=1: 0|1|1|01110|0|0|11000|01111|10|nnnnn|ddddd
// = 0_1_1_01110_0_0_11000_01111_10_nnnnn_ddddd
// Binary: 0110_1110_0011_0000_1111_1000_0000_0000 = 0x6E30F800
#define VFMAXV_S4(n, d) WORD $(0x6E30F800 | ((n) << 5) | (d))

// func reduceMaxSoftmaxNEON(src *float32, n int) float32
TEXT ·reduceMaxSoftmaxNEON(SB), NOSPLIT, $0-20
    MOVD src+0(FP), R0
    MOVD n+8(FP), R1

    // Initialize four accumulators to -inf. -inf as f32 = 0xFF800000.
    // We can't easily move an immediate large negative into a NEON
    // register, so load the first element and use that as initial,
    // then loop. Edge case: n=0 → return 0 (callers check).
    CBZ  R1, reduce_max_done

    // Initialize V16-V19 with the first element broadcast.
    FMOVS (R0), F16
    VDUP V16.S[0], V16.S4
    VMOV V16.B16, V17.B16
    VMOV V16.B16, V18.B16
    VMOV V16.B16, V19.B16

reduce_max_loop16:
    CMP  $16, R1
    BLT  reduce_max_loop4
    VLD1.P 64(R0), [V0.S4, V1.S4, V2.S4, V3.S4]
    VFMAX_S4(0, 16, 16)
    VFMAX_S4(1, 17, 17)
    VFMAX_S4(2, 18, 18)
    VFMAX_S4(3, 19, 19)
    SUB  $16, R1
    B    reduce_max_loop16

reduce_max_loop4:
    CMP  $4, R1
    BLT  reduce_max_scalar_tail
    VLD1.P 16(R0), [V0.S4]
    VFMAX_S4(0, 16, 16)
    SUB  $4, R1
    B    reduce_max_loop4

reduce_max_scalar_tail:
    // Fold the 4 accumulators into V16.
    VFMAX_S4(17, 16, 16)
    VFMAX_S4(18, 16, 16)
    VFMAX_S4(19, 16, 16)
    // Reduce V16's 4 lanes to scalar in F0.
    VFMAXV_S4(16, 0)

    CBZ  R1, reduce_max_finalize

reduce_max_scalar_loop:
    FMOVS (R0), F1
    // F0 = max(F0, F1). Use the same FCSEL trick as the binary max
    // kernel for NaN-non-propagating semantics matching Go.
    FCMPS F1, F0
    FCSELS GT, F0, F1, F0
    ADD  $4, R0
    SUB  $1, R1
    CBNZ R1, reduce_max_scalar_loop

reduce_max_finalize:
    FMOVS F0, ret+16(FP)
    RET

reduce_max_done:
    FMOVS ZR, F0
    FMOVS F0, ret+16(FP)
    RET
// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON softmax over a row: subtract max, exp, sum, divide.
// Uses the 7th-order Taylor exp polynomial inline (no calls).
// Reads max from caller (already computed via reduceMaxSoftmaxNEON).
//
// Args:
//   dst      — *float32, destination row (n elements)
//   src      — *float32, source row (n elements)
//   maxValue — *float32, scalar pointer to the row's maximum
//   n        — int, number of elements
// Returns: total sum (so the caller can normalize externally if it
// wants a different output convention).

#define VFADD_S4(m, n, d)  WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFSUB_S4(m, n, d)  WORD $(0x4EA0D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_S4(m, n, d)  WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFMLA_S4(m, n, d)  WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFDIV_S4(m, n, d)  WORD $(0x6E20FC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFRINTN_S4(n, d)   WORD $(0x4E218800 | ((n) << 5) | (d))
#define VFCVTZS_S4(n, d)   WORD $(0x4EA1B800 | ((n) << 5) | (d))
#define VADD_S4(m, n, d)   WORD $(0x4EA08400 | ((m) << 16) | ((n) << 5) | (d))
#define VSHL_S4_BY23(n, d) WORD $(0x4F375400 | ((n) << 5) | (d))
#define VMOV_B16(src, dst) WORD $(0x4EA01C00 | ((src) << 16) | ((src) << 5) | (dst))
// FADDP vector .4S: 0x6E30D400 base | Rm<<16 | Rn<<5 | Rd
#define VFADDP_S4(m, n, d) WORD $(0x6E30D400 | ((m) << 16) | ((n) << 5) | (d))
// FADDP scalar .2S → S: 0x7E30D800 base
#define FADDP_S(n, d)      WORD $(0x7E30D800 | ((n) << 5) | (d))

DATA  smC<>+0(SB)/4, $1.4426950408889634
DATA  smC<>+4(SB)/4, $0.6931471805599453
DATA  smC<>+8(SB)/4, $127.0
DATA  smC<>+12(SB)/4, $0.00019841270
DATA  smC<>+16(SB)/4, $0.0013888889
DATA  smC<>+20(SB)/4, $0.008333334
DATA  smC<>+24(SB)/4, $0.041666667
DATA  smC<>+28(SB)/4, $0.16666667
DATA  smC<>+32(SB)/4, $0.5
DATA  smC<>+36(SB)/4, $1.0
DATA  smC<>+40(SB)/4, $1.0
DATA  smC<>+44(SB)/4, $-87.0   // exp clamp lower bound (below this exp→0)
GLOBL smC<>(SB), 8, $48

#define EXP_BODY(in, out) \
    VFMUL_S4(16, in, 1)                  \
    VFRINTN_S4(1, 1)                     \
    VFMUL_S4(17, 1, 2)                   \
    VFSUB_S4(2, in, in)                  \
    VMOV_B16(19, 3)                      \
    VMOV_B16(20, 4) ; VFMLA_S4(in, 3, 4) \
    VMOV_B16(21, 3) ; VFMLA_S4(in, 4, 3) \
    VMOV_B16(22, 4) ; VFMLA_S4(in, 3, 4) \
    VMOV_B16(23, 3) ; VFMLA_S4(in, 4, 3) \
    VMOV_B16(24, 4) ; VFMLA_S4(in, 3, 4) \
    VMOV_B16(25, 3) ; VFMLA_S4(in, 4, 3) \
    VMOV_B16(26, 4) ; VFMLA_S4(in, 3, 4) \
    VFCVTZS_S4(1, 5)                     \
    VADD_S4(27, 5, 5)                    \
    VSHL_S4_BY23(5, 5)                   \
    VFMUL_S4(5, 4, out)

// softmaxRowExpSum: out[i] = exp(src[i] - maxVal); returns sum of out.
// func softmaxExpSumNEON(dst, src *float32, maxValue float32, n int) float32
TEXT ·softmaxExpSumNEON(SB), NOSPLIT, $0-36
    MOVD dst+0(FP), R0
    MOVD src+8(FP), R1
    FMOVS maxValue+16(FP), F28
    MOVD n+24(FP), R2

    // Constants V16..V27.
    MOVD $smC<>(SB), R3
    FMOVS  0(R3), F16 ; VDUP V16.S[0], V16.S4
    FMOVS  4(R3), F17 ; VDUP V17.S[0], V17.S4
    FMOVS  8(R3), F18 ; VDUP V18.S[0], V18.S4
    FMOVS 12(R3), F19 ; VDUP V19.S[0], V19.S4
    FMOVS 16(R3), F20 ; VDUP V20.S[0], V20.S4
    FMOVS 20(R3), F21 ; VDUP V21.S[0], V21.S4
    FMOVS 24(R3), F22 ; VDUP V22.S[0], V22.S4
    FMOVS 28(R3), F23 ; VDUP V23.S[0], V23.S4
    FMOVS 32(R3), F24 ; VDUP V24.S[0], V24.S4
    FMOVS 36(R3), F25 ; VDUP V25.S[0], V25.S4
    FMOVS 40(R3), F26 ; VDUP V26.S[0], V26.S4
    VFCVTZS_S4(18, 27)
    // V28 broadcast = maxValue.
    VDUP V28.S[0], V28.S4
    // V30 = -87.0 broadcast (exp clamp floor).
    FMOVS 44(R3), F30 ; VDUP V30.S[0], V30.S4

    // V29 = running sum accumulator (4 lanes).
    VEOR V29.B16, V29.B16, V29.B16

sm_loop4:
    CMP  $4, R2
    BLT  sm_scalar_tail
    VLD1.P 16(R1), [V0.S4]
    VFSUB_S4(28, 0, 0)                   // V0 = src - maxValue
    // Clamp V0 to >= -87.0 so 2^n stays in the normalized f32 range.
    // FMAX V_d, V_n, V_m → V_d = max(V_n, V_m). Encoding: VFMAX_S4(m, n, d).
    VFMAX_S4(30, 0, 0)                   // V0 = max(V0, -87)
    EXP_BODY(0, 6)                       // V6 = exp(V0)
    VST1.P [V6.S4], 16(R0)
    VFADD_S4(6, 29, 29)                  // accumulate
    SUB  $4, R2
    B    sm_loop4

sm_scalar_tail:
    // Fold V29 into F31 via two FADDP steps.
    VFADDP_S4(29, 29, 29)                // pairwise: [a+b, c+d, a+b, c+d]
    FADDP_S(29, 31)                      // F31 = (a+b)+(c+d)

    CBZ  R2, sm_done

sm_scalar_loop:
    FMOVS (R1), F0
    VDUP V0.S[0], V0.S4
    VFSUB_S4(28, 0, 0)
    VFMAX_S4(30, 0, 0)
    EXP_BODY(0, 6)
    FMOVS F6, (R0)
    // Add lane 0 of V6 to F31.
    FADDS F6, F31, F31
    ADD  $4, R1
    ADD  $4, R0
    SUB  $1, R2
    CBNZ R2, sm_scalar_loop

sm_done:
    FMOVS F31, ret+32(FP)
    RET

// func scaleF32NEON(dst, src *float32, scale float32, count int)
TEXT ·scaleF32NEON(SB), NOSPLIT, $0-28
    MOVD dst+0(FP), R0
    MOVD src+8(FP), R1
    FMOVS scale+16(FP), F16
    VDUP V16.S[0], V16.S4
    MOVD count+24(FP), R2
smn_scale_loop4:
    CMP  $4, R2
    BLT  smn_scale_scalar
    VLD1.P 16(R1), [V0.S4]
    VFMUL_S4(16, 0, 7)
    VST1.P [V7.S4], 16(R0)
    SUB  $4, R2
    B    smn_scale_loop4
smn_scale_scalar:
    CBZ  R2, smn_scale_done
smn_scale_scalar_loop:
    FMOVS (R1), F0
    FMULS F16, F0, F0
    FMOVS F0, (R0)
    ADD  $4, R1
    ADD  $4, R0
    SUB  $1, R2
    CBNZ R2, smn_scale_scalar_loop
smn_scale_done:
    RET

// func logSoftmaxShiftNEON(dst, src *float32, maxValue, logSum float32, count int)
TEXT ·logSoftmaxShiftNEON(SB), NOSPLIT, $0-32
    MOVD dst+0(FP), R0
    MOVD src+8(FP), R1
    FMOVS maxValue+16(FP), F16
    VDUP V16.S[0], V16.S4
    FMOVS logSum+20(FP), F17
    VDUP V17.S[0], V17.S4
    MOVD count+24(FP), R2
smn_log_loop4:
    CMP  $4, R2
    BLT  smn_log_scalar
    VLD1.P 16(R1), [V0.S4]
    VFSUB_S4(16, 0, 6)
    VFSUB_S4(17, 6, 7)
    VST1.P [V7.S4], 16(R0)
    SUB  $4, R2
    B    smn_log_loop4
smn_log_scalar:
    CBZ  R2, smn_log_done
smn_log_scalar_loop:
    FMOVS (R1), F0
    FSUBS F16, F0, F0
    FSUBS F17, F0, F0
    FMOVS F0, (R0)
    ADD  $4, R1
    ADD  $4, R0
    SUB  $1, R2
    CBNZ R2, smn_log_scalar_loop
smn_log_done:
    RET

// func SoftmaxF32NEON(dst, src *float32, count int)
TEXT ·SoftmaxF32NEON(SB), NOSPLIT, $48-24
    MOVD dst+0(FP), R10
    MOVD src+8(FP), R11
    MOVD count+16(FP), R12
    MOVD R11, 0(RSP)
    MOVD R12, 8(RSP)
    CALL ·reduceMaxSoftmaxNEON(SB)
    FMOVS F0, F6
    MOVD R10, 0(RSP)
    MOVD R11, 8(RSP)
    FMOVS F6, 16(RSP)
    MOVD R12, 24(RSP)
    CALL ·softmaxExpSumNEON(SB)
    FMOVS smC<>+36(SB), F8
    FDIVS F8, F0, F8
    MOVD R10, 0(RSP)
    MOVD R10, 8(RSP)
    FMOVS F8, 16(RSP)
    MOVD R12, 24(RSP)
    CALL ·scaleF32NEON(SB)
    RET

// func LogSoftmaxF32NEON(dst, src *float32, count int)
TEXT ·LogSoftmaxF32NEON(SB), NOSPLIT, $56-24
    MOVD dst+0(FP), R10
    MOVD src+8(FP), R11
    MOVD count+16(FP), R12
    MOVD R11, 0(RSP)
    MOVD R12, 8(RSP)
    CALL ·reduceMaxSoftmaxNEON(SB)
    FMOVS F0, F6
    MOVD R10, 0(RSP)
    MOVD R11, 8(RSP)
    FMOVS F6, 16(RSP)
    MOVD R12, 24(RSP)
    CALL ·softmaxExpSumNEON(SB)
    FMOVS F0, 32(RSP)
    ADD  $32, RSP, R13
    MOVD R13, 0(RSP)
    MOVD R13, 8(RSP)
    MOVD $1, R14
    MOVD R14, 16(RSP)
    CALL ·LogF32NEON(SB)
    FMOVS F0, F9
    MOVD R10, 0(RSP)
    MOVD R11, 8(RSP)
    FMOVS F6, 16(RSP)
    FMOVS F9, 20(RSP)
    MOVD R12, 24(RSP)
    CALL ·logSoftmaxShiftNEON(SB)
    RET
