// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON conv2d output-row computation for the common case
// (stride=1, dilation=1). Walks 4 output columns at a time through
// the (in-channel, kernel-h, kernel-w) loop using FMLA.
//
// One call produces one row of one channel: out[b, oc, oh, 0..outW].

#include "textflag.h"

#define VFMUL_S4(m, n, d)  WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFMLA_S4(m, n, d)  WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFADD_S4(m, n, d)  WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))

// func Conv2dStride1RowNEONAsm(
//     outRow *float32,
//     input *float32,
//     weight *float32,
//     biasValue float32,
//     outCols int,
//     inChannels int,
//     kH int,
//     kW int,
//     inHStride int,   // input height stride in floats = inWidth
//     inCStride int,   // input channel stride in floats = inHeight * inWidth
//     wHStride int,    // weight height stride = kW
//     wCStride int,    // weight channel stride = kH * kW
//     ihStart int,     // input row corresponding to outRow's first output col's kernel anchor
//     iwStart int,     // input col for kernel anchor (always 0 for no-padding stride=1)
// )
TEXT ·Conv2dStride1RowNEONAsm(SB), NOSPLIT, $0-112
    MOVD outRow+0(FP), R0
    MOVD input+8(FP), R1
    MOVD weight+16(FP), R2
    FMOVS biasValue+24(FP), F28 ; VDUP V28.S[0], V28.S4
    MOVD outCols+32(FP), R3
    MOVD inChannels+40(FP), R4
    MOVD kH+48(FP), R5
    MOVD kW+56(FP), R6
    MOVD inHStride+64(FP), R7
    MOVD inCStride+72(FP), R8
    MOVD wHStride+80(FP), R9
    MOVD wCStride+88(FP), R10
    MOVD ihStart+96(FP), R11
    // iwStart at +104 is unused for stride=1 no-padding (always 0).

    // Byte strides: multiply by 4.
    LSL  $2, R7, R7
    LSL  $2, R8, R8
    LSL  $2, R9, R9
    LSL  $2, R10, R10
    // ihStart already a row index → input pointer offset by ihStart * inHStride bytes.
    MUL  R7, R11, R11
    ADD  R11, R1, R1

col_block_loop:
    CMP  $4, R3
    BLT  conv2d_done

    // Initialize V0 = bias broadcast.
    WORD $(0x4EA01C00 | (28 << 16) | (28 << 5) | 0)  // VMOV V28, V0

    // Walk inChannels × kH × kW.
    MOVD R4, R12                   // remaining in-channels
    MOVD R1, R13                   // input pointer (current)
    MOVD R2, R14                   // weight pointer (current)

c_loop:
    CBZ  R12, c_done
    MOVD R5, R15                   // remaining kH
    MOVD R13, R16                  // input row pointer at this channel
    MOVD R14, R17                  // weight row pointer

kh_loop:
    CBZ  R15, kh_done
    MOVD R6, R19                   // remaining kW
    MOVD R16, R20                  // input col pointer
    MOVD R17, R21                  // weight col pointer

kw_loop:
    CBZ  R19, kw_done
    // Load weight scalar at R21, broadcast.
    FMOVS (R21), F1
    VDUP V1.S[0], V1.S4
    // Load 4 contiguous input floats at R20 (advancing by 1 col per kw step is built into the offset).
    VLD1 (R20), [V2.S4]
    VFMLA_S4(1, 2, 0)              // V0 += V1 * V2
    ADD  $4, R21                   // weight++ (1 float)
    ADD  $4, R20                   // input++ (1 col stride; this loop walks kW)
    SUB  $1, R19
    B    kw_loop

kw_done:
    ADD  R7, R16, R16              // input row += inHStride bytes
    ADD  R9, R17, R17              // weight row += wHStride bytes
    SUB  $1, R15
    B    kh_loop

kh_done:
    ADD  R8, R13, R13              // input channel += inCStride bytes
    ADD  R10, R14, R14             // weight channel += wCStride bytes
    SUB  $1, R12
    B    c_loop

c_done:
    VST1 [V0.S4], (R0)
    ADD  $16, R0                   // out += 4 floats
    ADD  $16, R1                   // input anchor advances by 4 cols (stride=1, 4 outs = 4 input col shifts)
    SUB  $4, R3
    B    col_block_loop

conv2d_done:
    RET
