// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON conv2d stride=1 row driver for fp16. Four output columns per
// block: FCVTL widen, FMLA accumulate, FCVTN narrow.

#include "textflag.h"

#define VFMLA_S4(m, n, d)  WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_H8(m, n, d)  WORD $(0x6E401C00 | ((m) << 16) | ((n) << 5) | (d))
#define VFCVTL_4S(n, d)     WORD $(0x0E217800 | ((n) << 5) | (d))
#define VFCVTN_4H(n, d)     WORD $(0x0E216800 | ((n) << 5) | (d))
#define VFADD_S4(m, n, d)   WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
#define FADDP_S(n, d)       WORD $(0x7E30D800 | ((n) << 5) | (d))

// func Conv2dStride1RowFP16NEONAsm(
//     outRow *uint16,
//     input *uint16,
//     weight *uint16,
//     biasValue float32,
//     outCols int,
//     inChannels int,
//     kH int,
//     kW int,
//     inHStride int,
//     inCStride int,
//     wHStride int,
//     wCStride int,
//     ihStart int,
//     iwStart int,
// )
TEXT ·Conv2dStride1RowFP16NEONAsm(SB), NOSPLIT, $16-112
    MOVD outRow+0(FP), R0
    MOVD input+8(FP), R1
    MOVD weight+16(FP), R2
    FMOVS biasValue+24(FP), F28
    MOVD outCols+32(FP), R3
    MOVD inChannels+40(FP), R4
    MOVD kH+48(FP), R5
    MOVD kW+56(FP), R6
    MOVD inHStride+64(FP), R7
    MOVD inCStride+72(FP), R8
    MOVD wHStride+80(FP), R9
    MOVD wCStride+88(FP), R10
    MOVD ihStart+96(FP), R11

    LSL  $1, R7, R7
    LSL  $1, R8, R8
    LSL  $1, R9, R9
    LSL  $1, R10, R10
    MUL  R7, R11, R11
    ADD  R11, R1, R1
    MOVD RSP, R23

    VDUP V28.S[0], V28.S4
    WORD $(0x4EA01C00 | (28 << 16) | (28 << 5) | 0)

col_block_loop:
    CMP  $4, R3
    BLT  conv2d_fp16_done

    WORD $(0x4EA01C00 | (28 << 16) | (28 << 5) | 0)

    MOVD R4, R12
    MOVD R1, R13
    MOVD R2, R14

c_loop:
    CBZ  R12, c_done
    MOVD R5, R15
    MOVD R13, R16
    MOVD R14, R17

kh_loop:
    CBZ  R15, kh_done
    MOVD R6, R19
    MOVD R16, R20
    MOVD R17, R21

kw_loop:
    CBZ  R19, kw_done
    MOVHU (R21), R22
    VMOV R22, V1.H[0]
    VMOV V1.H[0], R22
    MOVH R22, (R23)
    VLD1R (R23), [V1.H4]
    VLD1 (R20), [V2.H4]
    VFMUL_H8(2, 1, 24)
    VFCVTL_4S(24, 20)
    VFADD_S4(20, 0, 0)
    ADD  $2, R21
    ADD  $2, R20
    SUB  $1, R19
    B    kw_loop

kw_done:
    ADD  R7, R16, R16
    ADD  R9, R17, R17
    SUB  $1, R15
    B    kh_loop

kh_done:
    ADD  R8, R13, R13
    ADD  R10, R14, R14
    SUB  $1, R12
    B    c_loop

c_done:
    VFCVTN_4H(0, 12)
    VST1 [V12.H4], (R0)
    ADD  $8, R0
    ADD  $8, R1
    SUB  $4, R3
    B    col_block_loop

conv2d_fp16_done:
    RET

// func Conv2dPatchDotFP16NEONAsm(weight, patch *uint16, n int) float32
TEXT ·Conv2dPatchDotFP16NEONAsm(SB), NOSPLIT, $0-28
    MOVD weight+0(FP), R0
    MOVD patch+8(FP), R1
    MOVD n+16(FP), R2

    VEOR V16.B16, V16.B16, V16.B16
    VEOR V17.B16, V17.B16, V17.B16
    VEOR V18.B16, V18.B16, V18.B16
    VEOR V19.B16, V19.B16, V19.B16

cpd_fp16_loop16:
    CMP  $16, R2
    BLT  cpd_fp16_loop8
    VLD1.P 32(R0), [V0.H8, V1.H8]
    VLD1.P 32(R1), [V2.H8, V3.H8]
    VFMUL_H8(2, 0, 24)
    VFMUL_H8(3, 1, 25)
    VFCVTL_4S(24, 4)
    WORD $(0x4E217800 | (24 << 5) | 5)
    VFCVTL_4S(25, 6)
    WORD $(0x4E217800 | (25 << 5) | 7)
    VFADD_S4(4, 16, 16)
    VFADD_S4(5, 17, 17)
    VFADD_S4(6, 18, 18)
    VFADD_S4(7, 19, 19)
    SUB  $16, R2
    B    cpd_fp16_loop16

cpd_fp16_loop8:
    CMP  $8, R2
    BLT  cpd_fp16_reduce
    VLD1.P 16(R0), [V0.H8]
    VLD1.P 16(R1), [V2.H8]
    VFMUL_H8(2, 0, 24)
    VFCVTL_4S(24, 4)
    WORD $(0x4E217800 | (24 << 5) | 5)
    VFADD_S4(4, 16, 16)
    VFADD_S4(5, 17, 17)
    SUB  $8, R2
    B    cpd_fp16_loop8

cpd_fp16_reduce:
    WORD $(0x4E20D400 | (17 << 16) | (16 << 5) | 16)
    WORD $(0x4E20D400 | (18 << 16) | (16 << 5) | 16)
    WORD $(0x4E20D400 | (19 << 16) | (16 << 5) | 16)
    WORD $(0x6E30D400 | (16 << 16) | (16 << 5) | 16)
    WORD $(0x7E30D800 | (16 << 5) | 0)

    CBZ  R2, cpd_fp16_finalize

cpd_fp16_tail:
    MOVHU.P 2(R0), R3
    MOVHU.P 2(R1), R4
    LSL  $16, R3, R3
    LSL  $16, R4, R4
    FMOVS R3, F1
    FMOVS R4, F2
    FMULS F2, F1, F1
    FADDS F1, F0, F0
    SUB  $1, R2
    CBNZ R2, cpd_fp16_tail

cpd_fp16_finalize:
    FMOVS F0, ret+24(FP)
    RET
