// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// Patch dot for conv2d: f64 accumulation matching ConvPatchDotScalar.

#include "textflag.h"

#define VFMLA_D2(m, n, d) WORD $(0x4E60CC00 | ((m) << 16) | ((n) << 5) | (d))
#define FCVTL_2D(n, d)    WORD $(0x0E617800 | ((n) << 5) | (d))
#define FCVTL2_2D(n, d)   WORD $(0x4E617800 | ((n) << 5) | (d))
#define VFADD_D2(m, n, d) WORD $(0x4E60D400 | ((m) << 16) | ((n) << 5) | (d))
#define FADDP_D(n, d)     WORD $(0x7E70D800 | ((n) << 5) | (d))

// func Conv2dPatchDotNEONAsm(weight, patch *float32, n int) float32
TEXT ·Conv2dPatchDotNEONAsm(SB), NOSPLIT, $0-28
	MOVD weight+0(FP), R0
	MOVD patch+8(FP), R1
	MOVD n+16(FP), R2

	VEOR V16.B16, V16.B16, V16.B16
	VEOR V17.B16, V17.B16, V17.B16
	VEOR V18.B16, V18.B16, V18.B16
	VEOR V19.B16, V19.B16, V19.B16

cpd_loop8:
	CMP $8, R2
	BLT cpd_loop4
	VLD1.P 32(R0), [V0.S4, V1.S4]
	VLD1.P 32(R1), [V4.S4, V5.S4]
	FCVTL_2D(0, 8)
	FCVTL2_2D(0, 9)
	FCVTL_2D(1, 10)
	FCVTL2_2D(1, 11)
	FCVTL_2D(4, 12)
	FCVTL2_2D(4, 13)
	FCVTL_2D(5, 14)
	FCVTL2_2D(5, 15)
	VFMLA_D2(12, 8, 16)
	VFMLA_D2(13, 9, 17)
	VFMLA_D2(14, 10, 18)
	VFMLA_D2(15, 11, 19)
	SUB $8, R2
	B cpd_loop8

cpd_loop4:
	CMP $4, R2
	BLT cpd_reduce
	VLD1.P 16(R0), [V0.S4]
	VLD1.P 16(R1), [V4.S4]
	FCVTL_2D(0, 8)
	FCVTL2_2D(0, 9)
	FCVTL_2D(4, 12)
	FCVTL2_2D(4, 13)
	VFMLA_D2(12, 8, 16)
	VFMLA_D2(13, 9, 17)
	SUB $4, R2
	B cpd_loop4

cpd_reduce:
	VFADD_D2(17, 16, 16)
	VFADD_D2(18, 16, 16)
	VFADD_D2(19, 16, 16)
	FADDP_D(16, 0)

	CBZ R2, cpd_finalize

cpd_tail:
	FMOVS (R0), F1
	FMOVS (R1), F2
	FCVTSD F1, F1
	FCVTSD F2, F2
	FMULD F2, F1, F1
	FADDD F1, F0, F0
	ADD $4, R0
	ADD $4, R1
	SUB $1, R2
	CBNZ R2, cpd_tail

cpd_finalize:
	FCVTDS F0, F0
	FMOVS F0, ret+24(FP)
	RET
