// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON conv2d stride=1 row driver for bf16. Four output columns per
// block: widen bf16→f32, FMLA accumulate, RSHRN narrow f32→bf16.

#include "textflag.h"
#include "../neon_bf16_macros.inc"

#define VFMLA_S4(m, n, d)  WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))

// func Conv2dStride1RowBF16NEONAsm(
//     outRow *uint16,
//     input *uint16,
//     weight *uint16,
//     biasValue float32,
//     outCols int,
//     inChannels int,
//     kH int,
//     kW int,
//     inHStride int,   // inWidth (element count)
//     inCStride int,   // inHeight * inWidth
//     wHStride int,    // kW
//     wCStride int,    // kH * kW
//     ihStart int,
//     iwStart int,
// )
TEXT ·Conv2dStride1RowBF16NEONAsm(SB), NOSPLIT, $0-112
    MOVD outRow+0(FP), R0
    MOVD input+8(FP), R1
    MOVD weight+16(FP), R2
    FMOVS biasValue+24(FP), F28
    MOVD outCols+32(FP), R3
    MOVD inChannels+40(FP), R4
    MOVD kH+48(FP), R5
    MOVD kW+56(FP), R6
    MOVD inHStride+64(FP), R7
    MOVD inCStride+72(FP), R8
    MOVD wHStride+80(FP), R9
    MOVD wCStride+88(FP), R10
    MOVD ihStart+96(FP), R11

    VEOR V31.B16, V31.B16, V31.B16
    LSL  $1, R7, R7
    LSL  $1, R8, R8
    LSL  $1, R9, R9
    LSL  $1, R10, R10
    MUL  R7, R11, R11
    ADD  R11, R1, R1

    VDUP V28.S[0], V28.S4
    WORD $(0x4EA01C00 | (28 << 16) | (28 << 5) | 0)

col_block_loop:
    CMP  $4, R3
    BLT  conv2d_bf16_done

    WORD $(0x4EA01C00 | (28 << 16) | (28 << 5) | 0)

    MOVD R4, R12
    MOVD R1, R13
    MOVD R2, R14

c_loop:
    CBZ  R12, c_done
    MOVD R5, R15
    MOVD R13, R16
    MOVD R14, R17

kh_loop:
    CBZ  R15, kh_done
    MOVD R6, R19
    MOVD R16, R20
    MOVD R17, R21

kw_loop:
    CBZ  R19, kw_done
    MOVHU (R21), R22
    LSL  $16, R22, R22
    FMOVS R22, F1
    VDUP V1.S[0], V1.S4
    VLD1 (R20), [V2.H4]
    BF16_BITS_TO_F32_H4(V2.H8, V20.H8)
    VFMLA_S4(20, 1, 0)
    ADD  $2, R21
    ADD  $2, R20
    SUB  $1, R19
    B    kw_loop

kw_done:
    ADD  R7, R16, R16
    ADD  R9, R17, R17
    SUB  $1, R15
    B    kh_loop

kh_done:
    ADD  R8, R13, R13
    ADD  R10, R14, R14
    SUB  $1, R12
    B    c_loop

c_done:
    F32_BITS_TO_BF16_H4(0)
    VST1 [V12.H4], (R0)
    ADD  $8, R0
    ADD  $8, R1
    SUB  $4, R3
    B    col_block_loop

conv2d_bf16_done:
    RET

// func Conv2dPatchDotBF16NEONAsm(weight, patch *uint16, n int) float32
TEXT ·Conv2dPatchDotBF16NEONAsm(SB), NOSPLIT, $0-28
    MOVD weight+0(FP), R0
    MOVD patch+8(FP), R1
    MOVD n+16(FP), R2

    VEOR V31.B16, V31.B16, V31.B16
    VEOR V16.B16, V16.B16, V16.B16
    VEOR V17.B16, V17.B16, V17.B16
    VEOR V18.B16, V18.B16, V18.B16
    VEOR V19.B16, V19.B16, V19.B16

cpd_bf16_loop16:
    CMP  $16, R2
    BLT  cpd_bf16_loop8
    VLD1.P 32(R0), [V0.H8, V1.H8]
    VLD1.P 32(R1), [V2.H8, V3.H8]
    VZIP1 V0.H8, V31.H8, V4.H8
    VZIP2 V0.H8, V31.H8, V5.H8
    VZIP1 V1.H8, V31.H8, V6.H8
    VZIP2 V1.H8, V31.H8, V7.H8
    VZIP1 V2.H8, V31.H8, V8.H8
    VZIP2 V2.H8, V31.H8, V9.H8
    VZIP1 V3.H8, V31.H8, V10.H8
    VZIP2 V3.H8, V31.H8, V11.H8
    VFMLA_S4(8, 4, 16)
    VFMLA_S4(9, 5, 17)
    VFMLA_S4(10, 6, 18)
    VFMLA_S4(11, 7, 19)
    SUB  $16, R2
    B    cpd_bf16_loop16

cpd_bf16_loop8:
    CMP  $8, R2
    BLT  cpd_bf16_reduce
    VLD1.P 16(R0), [V0.H8]
    VLD1.P 16(R1), [V2.H8]
    VZIP1 V0.H8, V31.H8, V4.H8
    VZIP2 V0.H8, V31.H8, V5.H8
    VZIP1 V2.H8, V31.H8, V8.H8
    VZIP2 V2.H8, V31.H8, V9.H8
    VFMLA_S4(8, 4, 16)
    VFMLA_S4(9, 5, 17)
    SUB  $8, R2
    B    cpd_bf16_loop8

cpd_bf16_reduce:
    WORD $(0x4E20D400 | (17 << 16) | (16 << 5) | 16)
    WORD $(0x4E20D400 | (18 << 16) | (16 << 5) | 16)
    WORD $(0x4E20D400 | (19 << 16) | (16 << 5) | 16)
    WORD $(0x6E30D400 | (16 << 16) | (16 << 5) | 16)
    WORD $(0x7E30D800 | (16 << 5) | 0)

    CBZ  R2, cpd_bf16_finalize

cpd_bf16_tail:
    MOVHU.P 2(R0), R3
    MOVHU.P 2(R1), R4
    LSL  $16, R3, R3
    LSL  $16, R4, R4
    FMOVS R3, F1
    FMOVS R4, F2
    FMULS F2, F1, F1
    FADDS F1, F0, F0
    SUB  $1, R2
    CBNZ R2, cpd_bf16_tail

cpd_bf16_finalize:
    FMOVS F0, ret+24(FP)
    RET
