// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0

#include "textflag.h"

#define VFMLA_S4(m, n, d) WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFCVTL_4S(n, d)   WORD $(0x0E217800 | ((n) << 5) | (d))
#define VFCVTN_4H(n, d)   WORD $(0x0E216800 | ((n) << 5) | (d))

// func ConvTranspose2dTapFP16NEONAsm(outRow *uint16, weightVal float32, inputCol *uint16, outCols int)
TEXT ·ConvTranspose2dTapFP16NEONAsm(SB), NOSPLIT, $0-32
    MOVD outRow+0(FP), R0
    FMOVS weightVal+8(FP), F16
    VDUP V16.S[0], V31.S4
    MOVD inputCol+16(FP), R1
    MOVD outCols+24(FP), R2

    CMP  $4, R2
    BLT  ct_fp16_tap_done

    VLD1 (R0), [V0.H4]
    VFCVTL_4S(0, 0)
    VLD1 (R1), [V1.H4]
    VFCVTL_4S(1, 20)
    VFMLA_S4(20, 31, 0)
    VFCVTN_4H(0, 12)
    VST1 [V12.H4], (R0)

ct_fp16_tap_done:
    RET
