// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON conv transpose2d tap for fp16: native .8H multiply-add.

#include "textflag.h"

#define VFADD_H8(m, n, d) WORD $(0x4E401400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_H8(m, n, d) WORD $(0x6E401C00 | ((m) << 16) | ((n) << 5) | (d))

// func ConvTranspose2dTapFP16NEONAsm(outRow *uint16, weightVal float32, inputCol *uint16, outCols int)
TEXT ·ConvTranspose2dTapFP16NEONAsm(SB), NOSPLIT, $16-32
	MOVD outRow+0(FP), R0
	FMOVS weightVal+8(FP), F16
	MOVD inputCol+16(FP), R1
	MOVD outCols+24(FP), R2

	CMP  $4, R2
	BLT  ct_fp16_tap_done

	WORD $0x1E214000
	MOVD RSP, R3
	FMOVS F16, F0
	FCVTSH F0, F0
	FMOVS F0, R4
	VMOV R4, V31.H[0]
	VMOV V31.H[0], R4
	MOVH R4, (R3)
	VLD1R (R3), [V31.H4]

	VLD1 (R0), [V0.H4]
	VLD1 (R1), [V1.H4]
	VFMUL_H8(1, 31, 24)
	VFADD_H8(24, 0, 0)
	VST1 [V0.H4], (R0)

ct_fp16_tap_done:
	RET
