// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// One conv-transpose2d kernel tap: outRow[0:4] += weight * input[0:4].

#include "textflag.h"

#define VFMLA_S4(m, n, d) WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))

// func ConvTranspose2dTapNEONAsm(
//     outRow *float32,
//     weightVal float32,
//     inputCol *float32,
//     outCols int,
// )
TEXT ·ConvTranspose2dTapNEONAsm(SB), NOSPLIT, $0-32
    MOVD outRow+0(FP), R0
    FMOVS weightVal+8(FP), F16
    VDUP V16.S[0], V31.S4
    MOVD inputCol+16(FP), R1
    MOVD outCols+24(FP), R2

    CMP  $4, R2
    BLT  ct_tap_done
    VLD1 (R0), [V0.S4]
    VLD1 (R1), [V1.S4]
    VFMLA_S4(31, 1, 0)
    VST1 [V0.S4], (R0)

ct_tap_done:
    RET
