// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0

#include "textflag.h"

#define VFMAX_S4(m, n, d) WORD $(0x4E20F400 | ((m) << 16) | ((n) << 5) | (d))
#define VFADD_S4(m, n, d) WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_S4(m, n, d) WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))
#define VMOV_VREG(src, dst) WORD $(0x4EA01C00 | ((src) << 16) | ((src) << 5) | (dst))
#define NARROW_BF16_S4_TO_H4(src) \
    VMOV_VREG(src, 8) \
    VMOV_VREG(src, 9) \
    VUZP2 V9.H8, V8.H8, V12.H8

DATA poolNegInf<>+0(SB)/4, $0xFF800000
GLOBL poolNegInf<>(SB), 8, $4

// func MaxPool2DStride1RowBF16NEONAsm(outRow, input *uint16, outCols, kH, kW, inHStride, ihStart int)
TEXT ·MaxPool2DStride1RowBF16NEONAsm(SB), NOSPLIT, $0-56
    MOVD outRow+0(FP), R0
    MOVD input+8(FP), R1
    MOVD outCols+16(FP), R2
    MOVD kH+24(FP), R3
    MOVD kW+32(FP), R4
    MOVD inHStride+40(FP), R5
    MOVD ihStart+48(FP), R6

    VEOR V31.B16, V31.B16, V31.B16
    LSL  $1, R5, R5
    MUL  R5, R6, R6
    ADD  R6, R1, R1

    MOVD $0xFF800000, R7
    VMOV R7, V30.S[0]
    VDUP V30.S[0], V30.S4

mp_bf16_col_loop:
    CMP  $4, R2
    BLT  mp_bf16_done
    WORD $(0x4EA01C00 | (30 << 16) | (30 << 5) | 0)

    MOVD R3, R8
    MOVD R1, R9

mp_bf16_kh_loop:
    CBZ  R8, mp_bf16_kh_done
    MOVD R4, R10
    MOVD R9, R11

mp_bf16_kw_loop:
    CBZ  R10, mp_bf16_kw_done
    VLD1 (R11), [V2.H4]
    VZIP1 V2.H8, V31.H8, V20.H8
    VFMAX_S4(20, 0, 0)
    ADD  $2, R11
    SUB  $1, R10
    B    mp_bf16_kw_loop

mp_bf16_kw_done:
    ADD  R5, R9, R9
    SUB  $1, R8
    B    mp_bf16_kh_loop

mp_bf16_kh_done:
    NARROW_BF16_S4_TO_H4(0)
    VST1 [V12.H4], (R0)
    ADD  $8, R0
    ADD  $8, R1
    SUB  $4, R2
    B    mp_bf16_col_loop

mp_bf16_done:
    RET

// func AvgPool2DStride1RowBF16NEONAsm(outRow, input *uint16, outCols, kH, kW, inHStride, ihStart int)
TEXT ·AvgPool2DStride1RowBF16NEONAsm(SB), NOSPLIT, $0-56
    MOVD outRow+0(FP), R0
    MOVD input+8(FP), R1
    MOVD outCols+16(FP), R2
    MOVD kH+24(FP), R3
    MOVD kW+32(FP), R4
    MOVD inHStride+40(FP), R5
    MOVD ihStart+48(FP), R6

    VEOR V31.B16, V31.B16, V31.B16
    LSL  $1, R5, R5
    MUL  R5, R6, R6
    ADD  R6, R1, R1

    MUL  R4, R3, R12
    SCVTFWS R12, F31
    MOVD $0x3F800000, R7
    VMOV R7, V28.S[0]
    VDUP V28.S[0], V28.S4
    VDUP V31.S[0], V31.S4
    WORD $(0x6E20FC00 | (31 << 16) | (28 << 5) | 29)

ap_bf16_col_loop:
    CMP  $4, R2
    BLT  ap_bf16_done
    VEOR V0.B16, V0.B16, V0.B16

    MOVD R3, R8
    MOVD R1, R9

ap_bf16_kh_loop:
    CBZ  R8, ap_bf16_kh_done
    MOVD R4, R10
    MOVD R9, R11

ap_bf16_kw_loop:
    CBZ  R10, ap_bf16_kw_done
    VLD1 (R11), [V2.H4]
    VZIP1 V2.H8, V31.H8, V20.H8
    VFADD_S4(20, 0, 0)
    ADD  $2, R11
    SUB  $1, R10
    B    ap_bf16_kw_loop

ap_bf16_kw_done:
    ADD  R5, R9, R9
    SUB  $1, R8
    B    ap_bf16_kh_loop

ap_bf16_kh_done:
    VFMUL_S4(29, 0, 0)
    NARROW_BF16_S4_TO_H4(0)
    VST1 [V12.H4], (R0)
    ADD  $8, R0
    ADD  $8, R1
    SUB  $4, R2
    B    ap_bf16_col_loop

ap_bf16_done:
    RET

// func MaxPool2x2Stride2RowBF16NEONAsm(outRow, input *uint16, outCols, inWidth, ihStart int)
TEXT ·MaxPool2x2Stride2RowBF16NEONAsm(SB), NOSPLIT, $0-40
    MOVD outRow+0(FP), R0
    MOVD input+8(FP), R1
    MOVD outCols+16(FP), R2
    MOVD inWidth+24(FP), R3
    MOVD ihStart+32(FP), R4

    VEOR V31.B16, V31.B16, V31.B16
    LSL  $1, R3, R5
    MUL  R5, R4, R6
    ADD  R6, R1, R1
    ADD  R5, R1, R7

mp22_bf16_col_loop:
    CMP  $4, R2
    BLT  mp22_bf16_done
    VLD2 (R1), [V0.H4, V1.H4]
    VZIP1 V0.H8, V31.H8, V20.H8
    VZIP1 V1.H8, V31.H8, V21.H8
    VFMAX_S4(20, 21, 22)
    VLD2 (R7), [V0.H4, V1.H4]
    VZIP1 V0.H8, V31.H8, V20.H8
    VZIP1 V1.H8, V31.H8, V21.H8
    VFMAX_S4(20, 21, 23)
    VFMAX_S4(23, 22, 24)
    NARROW_BF16_S4_TO_H4(24)
    VST1 [V12.H4], (R0)
    ADD  $16, R1
    ADD  $16, R7
    ADD  $8, R0
    SUB  $4, R2
    B    mp22_bf16_col_loop

mp22_bf16_done:
    RET

// func AvgPool2x2Stride2RowBF16NEONAsm(outRow, input *uint16, outCols, inWidth, ihStart int)
TEXT ·AvgPool2x2Stride2RowBF16NEONAsm(SB), NOSPLIT, $0-40
    MOVD outRow+0(FP), R0
    MOVD input+8(FP), R1
    MOVD outCols+16(FP), R2
    MOVD inWidth+24(FP), R3
    MOVD ihStart+32(FP), R4

    MOVD $0x3E800000, R8
    VMOV R8, V30.S[0]
    VDUP V30.S[0], V30.S4

    VEOR V31.B16, V31.B16, V31.B16
    LSL  $1, R3, R5
    MUL  R5, R4, R6
    ADD  R6, R1, R1
    ADD  R5, R1, R7

ap22_bf16_col_loop:
    CMP  $4, R2
    BLT  ap22_bf16_done
    VLD2 (R1), [V0.H4, V1.H4]
    VZIP1 V0.H8, V31.H8, V20.H8
    VZIP1 V1.H8, V31.H8, V21.H8
    VLD2 (R7), [V2.H4, V3.H4]
    VZIP1 V2.H8, V31.H8, V22.H8
    VZIP1 V3.H8, V31.H8, V23.H8
    VEOR V4.B16, V4.B16, V4.B16
    VFADD_S4(20, 4, 4)
    VFADD_S4(21, 4, 4)
    VFADD_S4(22, 4, 4)
    VFADD_S4(23, 4, 4)
    VFMUL_S4(30, 4, 4)
    NARROW_BF16_S4_TO_H4(4)
    VST1 [V12.H4], (R0)
    ADD  $16, R1
    ADD  $16, R7
    ADD  $8, R0
    SUB  $4, R2
    B    ap22_bf16_col_loop

ap22_bf16_done:
    RET
