// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON 2D pooling row drivers. Each call processes 4 contiguous output
// columns for one (batch, channel, output row) triple — the inner
// kernel-window loop uses FMAX (max pool) or FADD (avg pool) on .4S
// against contiguous input rows.
//
// Caller computes startRow/startCol per output row; valid for any
// stride and padding (the input pointer + offsets handle it).
// Bounds clipping (for padding) is the caller's responsibility — the
// asm does not test row/col bounds in the inner loop.

#include "textflag.h"

#define VFADD_S4(m, n, d) WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMAX_S4(m, n, d) WORD $(0x4E20F400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_S4(m, n, d) WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))

DATA poolNegInf<>+0(SB)/4, $0xFF800000
DATA poolZero32<>+0(SB)/4, $0
DATA poolQuarter<>+0(SB)/4, $0x3E800000
GLOBL poolNegInf<>(SB), 8, $4
GLOBL poolZero32<>(SB), 8, $4
GLOBL poolQuarter<>(SB), 8, $4

// func MaxPool2DStride1RowNEONAsm(
//     outRow *float32, input *float32,
//     outCols, kH, kW int,
//     inHStride int,   // input width (bytes pre-scale)
//     ihStart int,     // anchor input row for this output row
// )
TEXT ·MaxPool2DStride1RowNEONAsm(SB), NOSPLIT, $0-56
    MOVD outRow+0(FP), R0
    MOVD input+8(FP), R1
    MOVD outCols+16(FP), R2
    MOVD kH+24(FP), R3
    MOVD kW+32(FP), R4
    MOVD inHStride+40(FP), R5
    MOVD ihStart+48(FP), R6

    LSL  $2, R5, R5                // byte stride
    MUL  R5, R6, R6
    ADD  R6, R1, R1                // anchor pointer

    // Initialize "running max" to -inf — bit pattern 0xFF800000.
    MOVD $0xFF800000, R7
    VMOV R7, V31.S[0]
    VDUP V31.S[0], V31.S4

mp_col_loop:
    CMP  $4, R2
    BLT  mp_done
    // V0 = -inf accumulator.
    WORD $(0x4EA01C00 | (31 << 16) | (31 << 5) | 0)  // VMOV V31, V0

    MOVD R3, R8                    // remaining kH
    MOVD R1, R9                    // input row pointer

mp_kh_loop:
    CBZ  R8, mp_kh_done
    MOVD R4, R10                   // remaining kW
    MOVD R9, R11                   // input col pointer

mp_kw_loop:
    CBZ  R10, mp_kw_done
    VLD1 (R11), [V1.S4]            // 4 contiguous floats at this kernel position
    VFMAX_S4(1, 0, 0)              // V0 = max(V0, V1)
    ADD  $4, R11                   // kw column advance
    SUB  $1, R10
    B    mp_kw_loop

mp_kw_done:
    ADD  R5, R9, R9                // next kernel row
    SUB  $1, R8
    B    mp_kh_loop

mp_kh_done:
    VST1 [V0.S4], (R0)
    ADD  $16, R0
    ADD  $16, R1                   // anchor moves by 4 cols (stride=1)
    SUB  $4, R2
    B    mp_col_loop

mp_done:
    RET

// func AvgPool2DStride1RowNEONAsm(
//     outRow *float32, input *float32,
//     outCols, kH, kW int,
//     inHStride int,
//     ihStart int,
// )
// Computes sum over the kernel window then multiplies by 1/(kH*kW).
TEXT ·AvgPool2DStride1RowNEONAsm(SB), NOSPLIT, $0-56
    MOVD outRow+0(FP), R0
    MOVD input+8(FP), R1
    MOVD outCols+16(FP), R2
    MOVD kH+24(FP), R3
    MOVD kW+32(FP), R4
    MOVD inHStride+40(FP), R5
    MOVD ihStart+48(FP), R6

    LSL  $2, R5, R5
    MUL  R5, R6, R6
    ADD  R6, R1, R1

    // 1 / (kH * kW) as broadcast in V31.
    MUL  R4, R3, R12
    SCVTFWS R12, F31
    // Reciprocal via FDIV: V31 = 1.0 / V31.
    MOVD $0x3F800000, R7
    VMOV R7, V30.S[0]              // 1.0 bits
    VDUP V30.S[0], V30.S4
    VDUP V31.S[0], V31.S4
    // V29 = 1.0 / V31
    WORD $(0x6E20FC00 | (31 << 16) | (30 << 5) | 29)  // VFDIV V31, V30, V29

ap_col_loop:
    CMP  $4, R2
    BLT  ap_done
    // V0 = 0 accumulator.
    VEOR V0.B16, V0.B16, V0.B16

    MOVD R3, R8
    MOVD R1, R9

ap_kh_loop:
    CBZ  R8, ap_kh_done
    MOVD R4, R10
    MOVD R9, R11

ap_kw_loop:
    CBZ  R10, ap_kw_done
    VLD1 (R11), [V1.S4]
    VFADD_S4(1, 0, 0)
    ADD  $4, R11
    SUB  $1, R10
    B    ap_kw_loop

ap_kw_done:
    ADD  R5, R9, R9
    SUB  $1, R8
    B    ap_kh_loop

ap_kh_done:
    // V0 *= 1/(kH*kW)
    VFMUL_S4(29, 0, 0)
    VST1 [V0.S4], (R0)
    ADD  $16, R0
    ADD  $16, R1
    SUB  $4, R2
    B    ap_col_loop

ap_done:
    RET

// func MaxPool2x2Stride2RowNEONAsm(
//     outRow *float32, input *float32,
//     outCols, inWidth, ihStart int,
// )
// 2×2 max pool, stride 2, no padding — four output columns per call.
TEXT ·MaxPool2x2Stride2RowNEONAsm(SB), NOSPLIT, $0-40
    MOVD outRow+0(FP), R0
    MOVD input+8(FP), R1
    MOVD outCols+16(FP), R2
    MOVD inWidth+24(FP), R3
    MOVD ihStart+32(FP), R4

    LSL  $2, R3, R5                // row byte stride
    MUL  R5, R4, R6
    ADD  R6, R1, R1                // row0 anchor
    ADD  R5, R1, R7                // row1 anchor

    MOVD $0xFF800000, R8
    VMOV R8, V31.S[0]
    VDUP V31.S[0], V31.S4

mp22_col_loop:
    CMP  $4, R2
    BLT  mp22_done
    VLD2 (R1), [V0.S4, V1.S4]
    VFMAX_S4(1, 0, 2)
    VLD2 (R7), [V0.S4, V1.S4]
    VFMAX_S4(1, 0, 3)
    VFMAX_S4(3, 2, 4)
    VST1 [V4.S4], (R0)
    ADD  $32, R1
    ADD  $32, R7
    ADD  $16, R0
    SUB  $4, R2
    B    mp22_col_loop

mp22_done:
    RET

// func AvgPool2x2Stride2RowNEONAsm(
//     outRow *float32, input *float32,
//     outCols, inWidth, ihStart int,
// )
// 2×2 avg pool, stride 2 — four output columns per vector pass.
TEXT ·AvgPool2x2Stride2RowNEONAsm(SB), NOSPLIT, $0-40
    MOVD outRow+0(FP), R0
    MOVD input+8(FP), R1
    MOVD outCols+16(FP), R2
    MOVD inWidth+24(FP), R3
    MOVD ihStart+32(FP), R4

    LSL  $2, R3, R5
    MUL  R5, R4, R6
    ADD  R6, R1, R1
    ADD  R5, R1, R7

    MOVD $0x3E800000, R8
    VMOV R8, V31.S[0]
    VDUP V31.S[0], V31.S4

ap22_col_loop:
    CMP  $4, R2
    BLT  ap22_done
    VLD2 (R1), [V0.S4, V1.S4]
    VLD2 (R7), [V2.S4, V3.S4]
    VEOR V4.B16, V4.B16, V4.B16
    VFADD_S4(0, 4, 4)
    VFADD_S4(1, 4, 4)
    VFADD_S4(2, 4, 4)
    VFADD_S4(3, 4, 4)
    VFMUL_S4(31, 4, 4)
    VST1 [V4.S4], (R0)
    ADD  $32, R1
    ADD  $32, R7
    ADD  $16, R0
    SUB  $4, R2
    B    ap22_col_loop

ap22_done:
    RET
