// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON fp16 pooling: native .8H max/add/mul/div (no FCVTL/FCVTN in hot paths).

#include "textflag.h"

#define VFCMGT_H8(m, n, d) WORD $(0x6EC02400 | ((m) << 16) | ((n) << 5) | (d))
#define VFADD_H8(m, n, d)  WORD $(0x4E401400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_H8(m, n, d)  WORD $(0x6E401C00 | ((m) << 16) | ((n) << 5) | (d))
#define VFDIV_H8(m, n, d)  WORD $(0x6E403C00 | ((m) << 16) | ((n) << 5) | (d))
#define VBSL_B16(m, n, d)  WORD $(0x6E601C00 | ((m) << 16) | ((n) << 5) | (d))
#define VMOV_B16(src, dst) WORD $(0x4EA01C00 | ((src) << 16) | ((src) << 5) | (dst))

// func MaxPool2DStride1RowFP16NEONAsm(outRow, input *uint16, outCols, kH, kW, inHStride, ihStart int)
TEXT ·MaxPool2DStride1RowFP16NEONAsm(SB), NOSPLIT, $0-56
	MOVD outRow+0(FP), R0
	MOVD input+8(FP), R1
	MOVD outCols+16(FP), R2
	MOVD kH+24(FP), R3
	MOVD kW+32(FP), R4
	MOVD inHStride+40(FP), R5
	MOVD ihStart+48(FP), R6

	LSL  $1, R5, R5
	MUL  R5, R6, R6
	ADD  R6, R1, R1

	MOVD $0xfc00, R7
	VMOV R7, V30.H[0]
	VDUP V30.H[0], V30.H4

mp_fp16_col_loop:
	CMP  $4, R2
	BLT  mp_fp16_done
	WORD $(0x4EA01C00 | (30 << 16) | (30 << 5) | 0)

	MOVD R3, R8
	MOVD R1, R9

mp_fp16_kh_loop:
	CBZ  R8, mp_fp16_kh_done
	MOVD R4, R10
	MOVD R9, R11

mp_fp16_kw_loop:
	CBZ  R10, mp_fp16_kw_done
	VLD1 (R11), [V2.H4]
	VFCMGT_H8(2, 0, 28)
	VBSL_B16(2, 0, 28)
	VMOV_B16(28, 0)
	ADD  $2, R11
	SUB  $1, R10
	B    mp_fp16_kw_loop

mp_fp16_kw_done:
	ADD  R5, R9, R9
	SUB  $1, R8
	B    mp_fp16_kh_loop

mp_fp16_kh_done:
	VST1 [V0.H4], (R0)
	ADD  $8, R0
	ADD  $8, R1
	SUB  $4, R2
	B    mp_fp16_col_loop

mp_fp16_done:
	RET

// func AvgPool2DStride1RowFP16NEONAsm(outRow, input *uint16, outCols, kH, kW, inHStride, ihStart int)
TEXT ·AvgPool2DStride1RowFP16NEONAsm(SB), NOSPLIT, $0-56
	MOVD outRow+0(FP), R0
	MOVD input+8(FP), R1
	MOVD outCols+16(FP), R2
	MOVD kH+24(FP), R3
	MOVD kW+32(FP), R4
	MOVD inHStride+40(FP), R5
	MOVD ihStart+48(FP), R6

	LSL  $1, R5, R5
	MUL  R5, R6, R6
	ADD  R6, R1, R1

	MUL  R4, R3, R12
	SCVTFWS R12, F0
	FCVTSH F0, F0
	FMOVS F0, R7
	VMOV R7, V31.H[0]
	VDUP V31.H[0], V31.H4

	MOVD $0x3c00, R7
	VMOV R7, V30.H[0]
	VDUP V30.H[0], V30.H4
	VFDIV_H8(31, 30, 29)

ap_fp16_col_loop:
	CMP  $4, R2
	BLT  ap_fp16_done
	VEOR V0.B16, V0.B16, V0.B16

	MOVD R3, R8
	MOVD R1, R9

ap_fp16_kh_loop:
	CBZ  R8, ap_fp16_kh_done
	MOVD R4, R10
	MOVD R9, R11

ap_fp16_kw_loop:
	CBZ  R10, ap_fp16_kw_done
	VLD1 (R11), [V2.H4]
	VFADD_H8(2, 0, 0)
	ADD  $2, R11
	SUB  $1, R10
	B    ap_fp16_kw_loop

ap_fp16_kw_done:
	ADD  R5, R9, R9
	SUB  $1, R8
	B    ap_fp16_kh_loop

ap_fp16_kh_done:
	VFMUL_H8(29, 0, 0)
	VST1 [V0.H4], (R0)
	ADD  $8, R0
	ADD  $8, R1
	SUB  $4, R2
	B    ap_fp16_col_loop

ap_fp16_done:
	RET

// func MaxPool2x2Stride2RowFP16NEONAsm(outRow, input *uint16, outCols, inWidth, ihStart int)
TEXT ·MaxPool2x2Stride2RowFP16NEONAsm(SB), NOSPLIT, $0-40
	MOVD outRow+0(FP), R0
	MOVD input+8(FP), R1
	MOVD outCols+16(FP), R2
	MOVD inWidth+24(FP), R3
	MOVD ihStart+32(FP), R4

	LSL  $1, R3, R5
	MUL  R5, R4, R6
	ADD  R6, R1, R1
	ADD  R5, R1, R7

mp22_fp16_col_loop:
	CMP  $4, R2
	BLT  mp22_fp16_done
	VLD2 (R1), [V0.H4, V1.H4]
	VFCMGT_H8(1, 0, 28)
	VBSL_B16(1, 0, 28)
	VMOV_B16(28, 20)
	VLD2 (R7), [V2.H4, V3.H4]
	VFCMGT_H8(3, 2, 29)
	VBSL_B16(3, 2, 29)
	VMOV_B16(29, 21)
	VFCMGT_H8(21, 20, 28)
	VBSL_B16(21, 20, 28)
	VMOV_B16(28, 0)
	VST1 [V0.H4], (R0)
	ADD  $16, R1
	ADD  $16, R7
	ADD  $8, R0
	SUB  $4, R2
	B    mp22_fp16_col_loop

mp22_fp16_done:
	RET

// func AvgPool2x2Stride2RowFP16NEONAsm(outRow, input *uint16, outCols, inWidth, ihStart int)
TEXT ·AvgPool2x2Stride2RowFP16NEONAsm(SB), NOSPLIT, $0-40
	MOVD outRow+0(FP), R0
	MOVD input+8(FP), R1
	MOVD outCols+16(FP), R2
	MOVD inWidth+24(FP), R3
	MOVD ihStart+32(FP), R4

	MOVD $0x3400, R8
	VMOV R8, V30.H[0]
	VDUP V30.H[0], V30.H4

	LSL  $1, R3, R5
	MUL  R5, R4, R6
	ADD  R6, R1, R1
	ADD  R5, R1, R7

ap22_fp16_col_loop:
	CMP  $4, R2
	BLT  ap22_fp16_done
	VLD2 (R1), [V0.H4, V1.H4]
	VFADD_H8(1, 0, 20)
	VLD2 (R7), [V2.H4, V3.H4]
	VFADD_H8(3, 2, 21)
	VFADD_H8(21, 20, 0)
	VFMUL_H8(30, 0, 0)
	VST1 [V0.H4], (R0)
	ADD  $16, R1
	ADD  $16, R7
	ADD  $8, R0
	SUB  $4, R2
	B    ap22_fp16_col_loop

ap22_fp16_done:
	RET
