// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0

#include "textflag.h"

#define VFMAX_S4(m, n, d) WORD $(0x4E20F400 | ((m) << 16) | ((n) << 5) | (d))
#define VFADD_S4(m, n, d) WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_S4(m, n, d) WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFCVTL_4S(n, d)   WORD $(0x0E217800 | ((n) << 5) | (d))
#define VFCVTN_4H(n, d)   WORD $(0x0E216800 | ((n) << 5) | (d))

// func MaxPool2DStride1RowFP16NEONAsm(outRow, input *uint16, outCols, kH, kW, inHStride, ihStart int)
TEXT ·MaxPool2DStride1RowFP16NEONAsm(SB), NOSPLIT, $0-56
    MOVD outRow+0(FP), R0
    MOVD input+8(FP), R1
    MOVD outCols+16(FP), R2
    MOVD kH+24(FP), R3
    MOVD kW+32(FP), R4
    MOVD inHStride+40(FP), R5
    MOVD ihStart+48(FP), R6

    LSL  $1, R5, R5
    MUL  R5, R6, R6
    ADD  R6, R1, R1

    MOVD $0xFF800000, R7
    VMOV R7, V30.S[0]
    VDUP V30.S[0], V30.S4

mp_fp16_col_loop:
    CMP  $4, R2
    BLT  mp_fp16_done
    WORD $(0x4EA01C00 | (30 << 16) | (30 << 5) | 0)

    MOVD R3, R8
    MOVD R1, R9

mp_fp16_kh_loop:
    CBZ  R8, mp_fp16_kh_done
    MOVD R4, R10
    MOVD R9, R11

mp_fp16_kw_loop:
    CBZ  R10, mp_fp16_kw_done
    VLD1 (R11), [V2.H4]
    VFCVTL_4S(2, 2)
    VFMAX_S4(2, 0, 0)
    ADD  $2, R11
    SUB  $1, R10
    B    mp_fp16_kw_loop

mp_fp16_kw_done:
    ADD  R5, R9, R9
    SUB  $1, R8
    B    mp_fp16_kh_loop

mp_fp16_kh_done:
    VFCVTN_4H(0, 12)
    VST1 [V12.H4], (R0)
    ADD  $8, R0
    ADD  $8, R1
    SUB  $4, R2
    B    mp_fp16_col_loop

mp_fp16_done:
    RET

// func AvgPool2DStride1RowFP16NEONAsm(outRow, input *uint16, outCols, kH, kW, inHStride, ihStart int)
TEXT ·AvgPool2DStride1RowFP16NEONAsm(SB), NOSPLIT, $0-56
    MOVD outRow+0(FP), R0
    MOVD input+8(FP), R1
    MOVD outCols+16(FP), R2
    MOVD kH+24(FP), R3
    MOVD kW+32(FP), R4
    MOVD inHStride+40(FP), R5
    MOVD ihStart+48(FP), R6

    LSL  $1, R5, R5
    MUL  R5, R6, R6
    ADD  R6, R1, R1

    MUL  R4, R3, R12
    SCVTFWS R12, F31
    MOVD $0x3F800000, R7
    VMOV R7, V30.S[0]
    VDUP V30.S[0], V30.S4
    VDUP V31.S[0], V31.S4
    WORD $(0x6E20FC00 | (31 << 16) | (30 << 5) | 29)

ap_fp16_col_loop:
    CMP  $4, R2
    BLT  ap_fp16_done
    VEOR V0.B16, V0.B16, V0.B16

    MOVD R3, R8
    MOVD R1, R9

ap_fp16_kh_loop:
    CBZ  R8, ap_fp16_kh_done
    MOVD R4, R10
    MOVD R9, R11

ap_fp16_kw_loop:
    CBZ  R10, ap_fp16_kw_done
    VLD1 (R11), [V2.H4]
    VFCVTL_4S(2, 2)
    VFADD_S4(2, 0, 0)
    ADD  $2, R11
    SUB  $1, R10
    B    ap_fp16_kw_loop

ap_fp16_kw_done:
    ADD  R5, R9, R9
    SUB  $1, R8
    B    ap_fp16_kh_loop

ap_fp16_kh_done:
    VFMUL_S4(29, 0, 0)
    VFCVTN_4H(0, 12)
    VST1 [V12.H4], (R0)
    ADD  $8, R0
    ADD  $8, R1
    SUB  $4, R2
    B    ap_fp16_col_loop

ap_fp16_done:
    RET

#define VFCVTL2_4S(n, d)  WORD $(0x4E217800 | ((n) << 5) | (d))

// func MaxPool2x2Stride2RowFP16NEONAsm(outRow, input *uint16, outCols, inWidth, ihStart int)
TEXT ·MaxPool2x2Stride2RowFP16NEONAsm(SB), NOSPLIT, $0-40
    MOVD outRow+0(FP), R0
    MOVD input+8(FP), R1
    MOVD outCols+16(FP), R2
    MOVD inWidth+24(FP), R3
    MOVD ihStart+32(FP), R4

    LSL  $1, R3, R5
    MUL  R5, R4, R6
    ADD  R6, R1, R1
    ADD  R5, R1, R7

mp22_fp16_col_loop:
    CMP  $4, R2
    BLT  mp22_fp16_done
    VLD2 (R1), [V0.H4, V1.H4]
    VFCVTL_4S(0, 20)
    VFCVTL2_4S(0, 21)
    VFMAX_S4(20, 21, 22)
    VLD2 (R7), [V0.H4, V1.H4]
    VFCVTL_4S(0, 20)
    VFCVTL2_4S(0, 21)
    VFMAX_S4(20, 21, 23)
    VFMAX_S4(23, 22, 24)
    VFCVTN_4H(24, 12)
    VST1 [V12.H4], (R0)
    ADD  $16, R1
    ADD  $16, R7
    ADD  $8, R0
    SUB  $4, R2
    B    mp22_fp16_col_loop

mp22_fp16_done:
    RET

// func AvgPool2x2Stride2RowFP16NEONAsm(outRow, input *uint16, outCols, inWidth, ihStart int)
TEXT ·AvgPool2x2Stride2RowFP16NEONAsm(SB), NOSPLIT, $0-40
    MOVD outRow+0(FP), R0
    MOVD input+8(FP), R1
    MOVD outCols+16(FP), R2
    MOVD inWidth+24(FP), R3
    MOVD ihStart+32(FP), R4

    MOVD $0x3E800000, R8
    VMOV R8, V30.S[0]
    VDUP V30.S[0], V30.S4

    LSL  $1, R3, R5
    MUL  R5, R4, R6
    ADD  R6, R1, R1
    ADD  R5, R1, R7

ap22_fp16_col_loop:
    CMP  $4, R2
    BLT  ap22_fp16_done
    VLD2 (R1), [V0.H4, V1.H4]
    VFCVTL_4S(0, 20)
    VFCVTL2_4S(0, 21)
    VLD2 (R7), [V2.H4, V3.H4]
    VFCVTL_4S(2, 22)
    VFCVTL2_4S(2, 23)
    VEOR V4.B16, V4.B16, V4.B16
    VFADD_S4(20, 4, 4)
    VFADD_S4(21, 4, 4)
    VFADD_S4(22, 4, 4)
    VFADD_S4(23, 4, 4)
    VFMUL_S4(30, 4, 4)
    VFCVTN_4H(4, 12)
    VST1 [V12.H4], (R0)
    ADD  $16, R1
    ADD  $16, R7
    ADD  $8, R0
    SUB  $4, R2
    B    ap22_fp16_col_loop

ap22_fp16_done:
    RET
