// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON PhaseCoupling for float32:
//   gm = sqrt(abs(left) * abs(right))
//   dst = (left * right) / (gm * gm) when gm >= eps, else 0

#include "textflag.h"

#define VFABS_S4(n, d)    WORD $(0x4EA0F800 | ((n) << 5) | (d))
#define VFSQRT_S4(n, d)   WORD $(0x6EA1F800 | ((n) << 5) | (d))
#define VFMUL_S4(m, n, d) WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFDIV_S4(m, n, d) WORD $(0x6E20FC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFCMGT_S4(m, n, d) WORD $(0x6EA0E400 | ((m) << 16) | ((n) << 5) | (d))
#define VBSL_B16(m, n, d)  WORD $(0x6E601C00 | ((m) << 16) | ((n) << 5) | (d))
#define VMOV_B16(src, dst) WORD $(0x4EA01C00 | ((src) << 16) | ((src) << 5) | (dst))

#define COUPLING_F32_S4(left, right, dst, eps, zero, t0, t1, t2, t3, t4, lt) \
    VFABS_S4(left, t0) \
    VFABS_S4(right, t1) \
    VFMUL_S4(t1, t0, t2) \
    VFSQRT_S4(t2, t3) \
    VFCMGT_S4(t3, eps, lt) \
    VFMUL_S4(right, left, t4) \
    VFMUL_S4(t3, t3, t3) \
    VFDIV_S4(t3, t4, t4) \
    VBSL_B16(t4, zero, lt) \
    VMOV_B16(lt, dst)

#define COUPLING_F32_4X4 \
    COUPLING_F32_S4(0, 4, 16, 29, 31, 20, 21, 22, 23, 24, 28) \
    COUPLING_F32_S4(1, 5, 17, 29, 31, 20, 21, 22, 23, 24, 28) \
    COUPLING_F32_S4(2, 6, 18, 29, 31, 20, 21, 22, 23, 24, 28) \
    COUPLING_F32_S4(3, 7, 19, 29, 31, 20, 21, 22, 23, 24, 28)

#define COUPLING_F32_1X1 \
    COUPLING_F32_S4(0, 4, 16, 29, 31, 20, 21, 22, 23, 24, 28)

// func PhaseCouplingFloat32NEONAsm(
//     destination, leftGrowth, rightGrowth *float32,
//     count int,
// )
TEXT ·PhaseCouplingFloat32NEONAsm(SB), NOSPLIT, $0-32
	MOVD destination+0(FP), R0
	MOVD leftGrowth+8(FP), R1
	MOVD rightGrowth+16(FP), R2
	MOVD count+24(FP), R3

	FMOVS $0.01, F29
	VDUP V29.S[0], V29.S4
	VEOR V31.B16, V31.B16, V31.B16

pcf32_neon_loop16:
	CMP  $16, R3
	BLT  pcf32_neon_loop4

	VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
	VLD1.P 64(R2), [V4.S4, V5.S4, V6.S4, V7.S4]
	COUPLING_F32_4X4
	VST1.P [V16.S4, V17.S4, V18.S4, V19.S4], 64(R0)
	SUB  $16, R3
	B    pcf32_neon_loop16

pcf32_neon_loop4:
	CMP  $4, R3
	BLT  pcf32_neon_done

	VLD1.P 16(R1), [V0.S4]
	VLD1.P 16(R2), [V4.S4]
	COUPLING_F32_1X1
	VST1.P [V16.S4], 16(R0)
	SUB  $4, R3
	B    pcf32_neon_loop4

pcf32_neon_done:
	RET
