// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON PhaseCoupling for float16 (.8H native, no f32 widen):
//   gm = sqrt(abs(left) * abs(right))
//   dst = (left * right) / (gm * gm) when gm >= eps, else 0

#include "textflag.h"

#define VFMUL_H8(m, n, d)  WORD $(0x6E401C00 | ((m) << 16) | ((n) << 5) | (d))
#define VFABS_H8(n, d)     WORD $(0x4EF8F800 | ((n) << 5) | (d))
#define VFSQRT_H8(n, d)    WORD $(0x6EF9F800 | ((n) << 5) | (d))
#define VFDIV_H8(m, n, d)  WORD $(0x6E403C00 | ((m) << 16) | ((n) << 5) | (d))
#define VFCMGT_H8(m, n, d) WORD $(0x6EC02400 | ((m) << 16) | ((n) << 5) | (d))
#define VBSL_B16(m, n, d)  WORD $(0x6E601C00 | ((m) << 16) | ((n) << 5) | (d))
#define VMOV_B16(src, dst) WORD $(0x4EA01C00 | ((src) << 16) | ((src) << 5) | (dst))

DATA geomCouplingFP16EpsNEON<>+0(SB)/2, $0x211f
GLOBL geomCouplingFP16EpsNEON<>(SB), RODATA|NOPTR, $2

#define COUPLING_FP16_H8(left, right, dst, eps, zero, t0, t1, t2, t3, t4, lt) \
	VFABS_H8(left, t0) \
	VFABS_H8(right, t1) \
	VFMUL_H8(t1, t0, t2) \
	VFSQRT_H8(t2, t3) \
	VFCMGT_H8(t3, eps, lt) \
	VFMUL_H8(right, left, t4) \
	VFMUL_H8(t3, t3, t3) \
	VFDIV_H8(t3, t4, t4) \
	VBSL_B16(t4, zero, lt) \
	VMOV_B16(lt, dst)

#define COUPLING_FP16_2X8 \
	COUPLING_FP16_H8(0, 2, 16, 29, 31, 20, 21, 22, 23, 24, 28) \
	COUPLING_FP16_H8(1, 3, 17, 29, 31, 20, 21, 22, 23, 24, 28)

#define COUPLING_FP16_1X8 \
	COUPLING_FP16_H8(0, 2, 16, 29, 31, 20, 21, 22, 23, 24, 28)

// func PhaseCouplingFloat16NEONAsm(dst, left, right *uint16, count int)
TEXT ·PhaseCouplingFloat16NEONAsm(SB), NOSPLIT, $0-32
	MOVD destination+0(FP), R0
	MOVD leftGrowth+8(FP), R1
	MOVD rightGrowth+16(FP), R2
	MOVD count+24(FP), R3

	MOVD $geomCouplingFP16EpsNEON<>(SB), R6
	VLD1R (R6), [V29.H8]
	VEOR V31.B16, V31.B16, V31.B16

pcfp16_neon_loop16:
	CMP  $16, R3
	BLT  pcfp16_neon_loop8

	VLD1.P 32(R1), [V0.H8, V1.H8]
	VLD1.P 32(R2), [V2.H8, V3.H8]
	COUPLING_FP16_2X8
	VST1.P [V16.H8, V17.H8], 32(R0)
	SUB  $16, R3
	B    pcfp16_neon_loop16

pcfp16_neon_loop8:
	CMP  $8, R3
	BLT  pcfp16_neon_done

	VLD1.P 16(R1), [V0.H8]
	VLD1.P 16(R2), [V2.H8]
	COUPLING_FP16_1X8
	VST1.P [V16.H8], 16(R0)
	SUB  $8, R3
	B    pcfp16_neon_loop8

pcfp16_neon_done:
	RET
