// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON float64 vector kernels for geometry host math.

#include "textflag.h"

#define VFMUL_D2(m, n, d)  WORD $(0x4E60DC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFADD_D2(m, n, d)  WORD $(0x4E60D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMAX_D2(m, n, d)  WORD $(0x4E60F400 | ((m) << 16) | ((n) << 5) | (d))
#define VFSQRT_D2(n, d)    WORD $(0x6E61D800 | ((n) << 5) | (d))
#define FADDP_D(n, d)      WORD $(0x7E70D800 | ((n) << 5) | (d))

// func SumFloat64NEONAsm(src *float64, count int) float64
TEXT ·SumFloat64NEONAsm(SB), NOSPLIT, $0-24
	MOVD src+0(FP), R0
	MOVD count+8(FP), R1

	VEOR V16.B16, V16.B16, V16.B16
	VEOR V17.B16, V17.B16, V17.B16
	VEOR V18.B16, V18.B16, V18.B16
	VEOR V19.B16, V19.B16, V19.B16

sum64_loop8:
	CMP  $8, R1
	BLT  sum64_loop2

	VLD1.P 64(R0), [V0.D2, V1.D2, V2.D2, V3.D2]
	VFADD_D2(0, 16, 16)
	VFADD_D2(1, 17, 17)
	VFADD_D2(2, 18, 18)
	VFADD_D2(3, 19, 19)
	SUB  $8, R1
	B    sum64_loop8

sum64_loop2:
	CMP  $2, R1
	BLT  sum64_reduce

	VLD1.P 16(R0), [V0.D2]
	VFADD_D2(0, 16, 16)
	SUB  $2, R1
	B    sum64_loop2

sum64_reduce:
	VFADD_D2(17, 16, 16)
	VFADD_D2(18, 16, 16)
	VFADD_D2(19, 16, 16)
	FADDP_D(16, 0)

	CBZ  R1, sum64_done

sum64_scalar:
	FMOVD (R0), F1
	FADDD F1, F0, F0
	ADD  $8, R0
	SUB  $1, R1
	CBNZ R1, sum64_scalar

sum64_done:
	FMOVD F0, ret+16(FP)
	RET

// func SumOfSquaresFloat64NEONAsm(src *float64, count int) float64
TEXT ·SumOfSquaresFloat64NEONAsm(SB), NOSPLIT, $0-24
	MOVD src+0(FP), R0
	MOVD count+8(FP), R1

	VEOR V16.B16, V16.B16, V16.B16
	VEOR V17.B16, V17.B16, V17.B16
	VEOR V18.B16, V18.B16, V18.B16
	VEOR V19.B16, V19.B16, V19.B16

sumsq64_loop8:
	CMP  $8, R1
	BLT  sumsq64_loop2

	VLD1.P 64(R0), [V0.D2, V1.D2, V2.D2, V3.D2]
	VFMUL_D2(0, 0, 20)
	VFADD_D2(20, 16, 16)
	VFMUL_D2(1, 1, 20)
	VFADD_D2(20, 17, 17)
	VFMUL_D2(2, 2, 20)
	VFADD_D2(20, 18, 18)
	VFMUL_D2(3, 3, 20)
	VFADD_D2(20, 19, 19)
	SUB  $8, R1
	B    sumsq64_loop8

sumsq64_loop2:
	CMP  $2, R1
	BLT  sumsq64_reduce

	VLD1.P 16(R0), [V0.D2]
	VFMUL_D2(0, 0, 20)
	VFADD_D2(20, 16, 16)
	SUB  $2, R1
	B    sumsq64_loop2

sumsq64_reduce:
	VFADD_D2(17, 16, 16)
	VFADD_D2(18, 16, 16)
	VFADD_D2(19, 16, 16)
	FADDP_D(16, 0)

	CBZ  R1, sumsq64_done

sumsq64_scalar:
	FMOVD (R0), F1
	FMULD F1, F1, F1
	FADDD F1, F0, F0
	ADD  $8, R0
	SUB  $1, R1
	CBNZ R1, sumsq64_scalar

sumsq64_done:
	FMOVD F0, ret+16(FP)
	RET

// func DotFloat64NEONAsm(left, right *float64, count int) float64
TEXT ·DotFloat64NEONAsm(SB), NOSPLIT, $0-32
	MOVD left+0(FP), R0
	MOVD right+8(FP), R1
	MOVD count+16(FP), R2

	VEOR V16.B16, V16.B16, V16.B16
	VEOR V17.B16, V17.B16, V17.B16
	VEOR V18.B16, V18.B16, V18.B16
	VEOR V19.B16, V19.B16, V19.B16

dot64_loop8:
	CMP  $8, R2
	BLT  dot64_loop2

	VLD1.P 64(R0), [V0.D2, V1.D2, V2.D2, V3.D2]
	VLD1.P 64(R1), [V4.D2, V5.D2, V6.D2, V7.D2]
	VFMUL_D2(4, 0, 20)
	VFADD_D2(20, 16, 16)
	VFMUL_D2(5, 1, 20)
	VFADD_D2(20, 17, 17)
	VFMUL_D2(6, 2, 20)
	VFADD_D2(20, 18, 18)
	VFMUL_D2(7, 3, 20)
	VFADD_D2(20, 19, 19)
	SUB  $8, R2
	B    dot64_loop8

dot64_loop2:
	CMP  $2, R2
	BLT  dot64_reduce

	VLD1.P 16(R0), [V0.D2]
	VLD1.P 16(R1), [V4.D2]
	VFMUL_D2(4, 0, 20)
	VFADD_D2(20, 16, 16)
	SUB  $2, R2
	B    dot64_loop2

dot64_reduce:
	VFADD_D2(17, 16, 16)
	VFADD_D2(18, 16, 16)
	VFADD_D2(19, 16, 16)
	FADDP_D(16, 0)

	CBZ  R2, dot64_done

dot64_scalar:
	FMOVD (R0), F1
	FMOVD (R1), F2
	FMULD F2, F1, F1
	FADDD F1, F0, F0
	ADD  $8, R0
	ADD  $8, R1
	SUB  $1, R2
	CBNZ R2, dot64_scalar

dot64_done:
	FMOVD F0, ret+24(FP)
	RET

// func MaxFloat64NEONAsm(src *float64, count int) float64
TEXT ·MaxFloat64NEONAsm(SB), NOSPLIT, $0-24
	MOVD src+0(FP), R0
	MOVD count+8(FP), R1

	CBZ  R1, max64_zero

	FMOVD (R0), F0
	ADD  $8, R0
	SUB  $1, R1
	CBZ  R1, max64_done_scalar

max64_loop2:
	CMP  $2, R1
	BLT  max64_scalar

	FMOVD (R0), F1
	FCMPD F1, F0
	BLE  max64_pair1
	FMOVD F1, F0

max64_pair1:
	FMOVD 8(R0), F1
	FCMPD F1, F0
	BLE  max64_pair2
	FMOVD F1, F0

max64_pair2:
	ADD  $16, R0
	SUB  $2, R1
	B    max64_loop2

max64_scalar:
	CBZ  R1, max64_done_scalar

max64_scalar_loop:
	FMOVD (R0), F1
	FCMPD F1, F0
	BLE  max64_scalar_skip
	FMOVD F1, F0

max64_scalar_skip:
	ADD  $8, R0
	SUB  $1, R1
	CBNZ R1, max64_scalar_loop

max64_done_scalar:
	FMOVD F0, ret+16(FP)
	RET

max64_zero:
	FMOVD $0.0, F0
	FMOVD F0, ret+16(FP)
	RET

// func ScaleFloat64NEONAsm(dst, src *float64, scale float64, count int)
TEXT ·ScaleFloat64NEONAsm(SB), NOSPLIT, $0-40
	MOVD dst+0(FP), R0
	MOVD src+8(FP), R1
	FMOVD scale+16(FP), F31
	MOVD count+24(FP), R2

scale64_loop2:
	CMP  $2, R2
	BLT  scale64_scalar

	VDUP V31.D[0], V31.D2
	VLD1.P 16(R1), [V0.D2]
	VFMUL_D2(31, 0, 0)
	VST1.P [V0.D2], 16(R0)
	SUB  $2, R2
	B    scale64_loop2

scale64_scalar:
	CBZ  R2, scale64_done

	FMOVD (R1), F0
	FMULD F31, F0, F0
	FMOVD F0, (R0)
	ADD  $8, R1
	ADD  $8, R0
	SUB  $1, R2
	CBNZ R2, scale64_scalar

scale64_done:
	RET

// func AddScalarFloat64NEONAsm(dst, src *float64, offset float64, count int)
TEXT ·AddScalarFloat64NEONAsm(SB), NOSPLIT, $0-40
	MOVD dst+0(FP), R0
	MOVD src+8(FP), R1
	FMOVD offset+16(FP), F31
	MOVD count+24(FP), R2

adds64_loop2:
	CMP  $2, R2
	BLT  adds64_scalar

	VDUP V31.D[0], V31.D2
	VLD1.P 16(R1), [V0.D2]
	VFADD_D2(31, 0, 0)
	VST1.P [V0.D2], 16(R0)
	SUB  $2, R2
	B    adds64_loop2

adds64_scalar:
	CBZ  R2, adds64_done

	FMOVD (R1), F0
	FADDD F31, F0, F0
	FMOVD F0, (R0)
	ADD  $8, R1
	ADD  $8, R0
	SUB  $1, R2
	CBNZ R2, adds64_scalar

adds64_done:
	RET

// func MulFloat64NEONAsm(dst, left, right *float64, count int)
TEXT ·MulFloat64NEONAsm(SB), NOSPLIT, $0-32
	MOVD dst+0(FP), R0
	MOVD left+8(FP), R1
	MOVD right+16(FP), R2
	MOVD count+24(FP), R3

mul64_loop2:
	CMP  $2, R3
	BLT  mul64_scalar

	VLD1.P 16(R1), [V0.D2]
	VLD1.P 16(R2), [V4.D2]
	VFMUL_D2(4, 0, 0)
	VST1.P [V0.D2], 16(R0)
	SUB  $2, R3
	B    mul64_loop2

mul64_scalar:
	CBZ  R3, mul64_done

	FMOVD (R1), F0
	FMOVD (R2), F1
	FMULD F1, F0, F0
	FMOVD F0, (R0)
	ADD  $8, R1
	ADD  $8, R2
	ADD  $8, R0
	SUB  $1, R3
	CBNZ R3, mul64_scalar

mul64_done:
	RET

// func AddFloat64NEONAsm(dst, left, right *float64, count int)
TEXT ·AddFloat64NEONAsm(SB), NOSPLIT, $0-32
	MOVD dst+0(FP), R0
	MOVD left+8(FP), R1
	MOVD right+16(FP), R2
	MOVD count+24(FP), R3

add64_loop2:
	CMP  $2, R3
	BLT  add64_scalar

	VLD1.P 16(R1), [V0.D2]
	VLD1.P 16(R2), [V4.D2]
	VFADD_D2(4, 0, 0)
	VST1.P [V0.D2], 16(R0)
	SUB  $2, R3
	B    add64_loop2

add64_scalar:
	CBZ  R3, add64_done

	FMOVD (R1), F0
	FMOVD (R2), F1
	FADDD F1, F0, F0
	FMOVD F0, (R0)
	ADD  $8, R1
	ADD  $8, R2
	ADD  $8, R0
	SUB  $1, R3
	CBNZ R3, add64_scalar

add64_done:
	RET

// func SqrtFloat64NEONAsm(dst, src *float64, count int)
TEXT ·SqrtFloat64NEONAsm(SB), NOSPLIT, $0-24
	MOVD dst+0(FP), R0
	MOVD src+8(FP), R1
	MOVD count+16(FP), R2

sqrt64_loop2:
	CMP  $2, R2
	BLT  sqrt64_scalar

	VLD1.P 16(R1), [V0.D2]
	VFSQRT_D2(0, 0)
	VST1.P [V0.D2], 16(R0)
	SUB  $2, R2
	B    sqrt64_loop2

sqrt64_scalar:
	CBZ  R2, sqrt64_done

	FMOVD (R1), F0
	FSQRTD F0, F0
	FMOVD F0, (R0)
	ADD  $8, R1
	ADD  $8, R0
	SUB  $1, R2
	CBNZ R2, sqrt64_scalar

sqrt64_done:
	RET
