// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON PhaseDial kernels for fixed PhaseDialDimensions (128) complex128 vectors.
// Each complex128 is stored as [real, imag] in a 16-byte lane (V0.D2).

#include "textflag.h"

#define VFADD_D2(m, n, d) WORD $(0x4E60D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_D2(m, n, d) WORD $(0x4E60DC00 | ((m) << 16) | ((n) << 5) | (d))
#define FADDP_D(n, d)     WORD $(0x7E70D800 | ((n) << 5) | (d))

// func DialEnergy128NEONAsm(dial *complex128) float64
TEXT ·DialEnergy128NEONAsm(SB), NOSPLIT, $0-16
	MOVD dial+0(FP), R0

	VEOR V16.B16, V16.B16, V16.B16
	VEOR V17.B16, V17.B16, V17.B16
	MOVD $128, R1

dial_energy_loop:
	VLD1.P 16(R0), [V0.D2]
	VFMUL_D2(0, 0, 4)
	VFADD_D2(4, 16, 16)
	SUB  $1, R1
	CBNZ R1, dial_energy_loop

	VFADD_D2(17, 16, 16)
	FADDP_D(16, 0)
	FMOVD F0, ret+8(FP)
	RET

// func DialNormalize128NEONAsm(dial *complex128)
TEXT ·DialNormalize128NEONAsm(SB), NOSPLIT, $0-8
	MOVD dial+0(FP), R0

	FMOVD $0.0, F16
	MOVD R0, R1
	MOVD $128, R2

dial_norm_energy:
	FMOVD (R1), F0
	FMOVD 8(R1), F1
	FMULD F0, F0, F2
	FMULD F1, F1, F3
	FADDD F3, F2, F2
	FADDD F2, F16, F16
	ADD  $16, R1
	SUB  $1, R2
	CBNZ R2, dial_norm_energy

	FCMPD $0.0, F16
	BLE  dial_norm_done

	FMOVD F16, F0
	FSQRTD F0, F0
	FMOVD $1.0, F2
	FDIVD F0, F2, F3
	MOVD $128, R2

dial_norm_apply:
	FMOVD (R0), F4
	FMOVD 8(R0), F5
	FMULD F3, F4, F4
	FMULD F3, F5, F5
	FMOVD F4, (R0)
	FMOVD F5, 8(R0)
	ADD  $16, R0
	SUB  $1, R2
	CBNZ R2, dial_norm_apply

dial_norm_done:
	RET

// func DialSimilarity128NEONAsm(left, right *complex128) float64
TEXT ·DialSimilarity128NEONAsm(SB), NOSPLIT, $0-24
	MOVD left+0(FP), R0
	MOVD right+8(FP), R1

	FMOVD $0.0, F16
	FMOVD $0.0, F17
	FMOVD $0.0, F18
	MOVD $128, R2

dial_sim_loop:
	FMOVD (R0), F0
	FMOVD 8(R0), F1
	FMOVD (R1), F2
	FMOVD 8(R1), F3
	FMULD F0, F2, F4
	FMULD F1, F3, F5
	FADDD F5, F4, F4
	FADDD F4, F16, F16
	FMULD F0, F0, F4
	FMULD F1, F1, F5
	FADDD F5, F4, F4
	FADDD F4, F17, F17
	FMULD F2, F2, F4
	FMULD F3, F3, F5
	FADDD F5, F4, F4
	FADDD F4, F18, F18
	ADD  $16, R0
	ADD  $16, R1
	SUB  $1, R2
	CBNZ R2, dial_sim_loop

	FMULD F17, F18, F19
	FCMPD $0.0, F19
	BLE  dial_sim_zero
	FSQRTD F17, F17
	FSQRTD F18, F18
	FMULD F18, F17, F17
	FDIVD F17, F16, F16
	FMOVD F16, ret+16(FP)
	RET

dial_sim_zero:
	FMOVD $0.0, F16
	FMOVD F16, ret+16(FP)
	RET

// func DialRotate128NEONAsm(out, in *complex128, cosAngle, sinAngle float64)
TEXT ·DialRotate128NEONAsm(SB), NOSPLIT, $0-32
	MOVD out+0(FP), R0
	MOVD in+8(FP), R1
	FMOVD cosAngle+16(FP), F29
	FMOVD sinAngle+24(FP), F30
	MOVD $128, R2

	dial_rot_loop:
	FMOVD (R1), F4
	FMOVD 8(R1), F5
	FMULD F4, F29, F6
	FMULD F5, F30, F7
	FSUBD F7, F6, F6
	FMULD F4, F30, F4
	FMULD F5, F29, F5
	FADDD F5, F4, F4
	FMOVD F6, (R0)
	FMOVD F4, 8(R0)
	ADD  $16, R1
	ADD  $16, R0
	SUB  $1, R2
	CBNZ R2, dial_rot_loop

	RET

// func DialAddPhases128NEONAsm(dial *complex128, cosines, sines *float64)
TEXT ·DialAddPhases128NEONAsm(SB), NOSPLIT, $0-24
	MOVD dial+0(FP), R0
	MOVD cosines+8(FP), R1
	MOVD sines+16(FP), R2
	MOVD $128, R3

dial_add_loop:
	FMOVD (R0), F4
	FMOVD 8(R0), F5
	FMOVD (R1), F6
	FMOVD (R2), F7
	FADDD F6, F4, F4
	FADDD F7, F5, F5
	FMOVD F4, (R0)
	FMOVD F5, 8(R0)
	ADD  $16, R0
	ADD  $8, R1
	ADD  $8, R2
	SUB  $1, R3
	CBNZ R3, dial_add_loop

	RET

// func DialComposeMidpoint128NEONAsm(out, left, right *complex128)
TEXT ·DialComposeMidpoint128NEONAsm(SB), NOSPLIT, $0-24
	MOVD out+0(FP), R0
	MOVD left+8(FP), R1
	MOVD right+16(FP), R2

	FMOVD $0.0, F16
	FMOVD $0.0, F17
	MOVD R1, R3
	MOVD R2, R4
	MOVD $128, R5

dial_comp_energy:
	FMOVD (R3), F0
	FMOVD 8(R3), F1
	FMULD F0, F0, F6
	FMULD F1, F1, F7
	FADDD F7, F6, F6
	FADDD F6, F16, F16
	FMOVD (R4), F0
	FMOVD 8(R4), F1
	FMULD F0, F0, F6
	FMULD F1, F1, F7
	FADDD F7, F6, F6
	FADDD F6, F17, F17
	ADD  $16, R3
	ADD  $16, R4
	SUB  $1, R5
	CBNZ R5, dial_comp_energy

	FCMPD $0.0, F16
	BLE  dial_comp_done
	FCMPD $0.0, F17
	BLE  dial_comp_done

	FMOVD F16, F0
	FSQRTD F0, F0
	FMOVD $1.0, F6
	FDIVD F0, F6, F18
	FMOVD F17, F0
	FSQRTD F0, F0
	FDIVD F0, F6, F19

	MOVD left+8(FP), R1
	MOVD right+16(FP), R2
	MOVD out+0(FP), R0
	FMOVD $0.0, F20
	MOVD $128, R5

dial_comp_accum:
	FMOVD (R1), F0
	FMOVD 8(R1), F1
	FMOVD (R2), F2
	FMOVD 8(R2), F3
	FMULD F18, F0, F0
	FMULD F18, F1, F1
	FMULD F19, F2, F2
	FMULD F19, F3, F3
	FADDD F2, F0, F0
	FADDD F3, F1, F1
	FMOVD F0, (R0)
	FMOVD F1, 8(R0)
	FMULD F0, F0, F6
	FMULD F1, F1, F7
	FADDD F7, F6, F6
	FADDD F6, F20, F20
	ADD  $16, R0
	ADD  $16, R1
	ADD  $16, R2
	SUB  $1, R5
	CBNZ R5, dial_comp_accum

	FCMPD $0.0, F20
	BLE  dial_comp_done

	FMOVD F20, F0
	FSQRTD F0, F0
	FDIVD F0, F6, F21
	MOVD out+0(FP), R0
	MOVD $128, R5

dial_comp_norm:
	FMOVD (R0), F0
	FMOVD 8(R0), F1
	FMULD F21, F0, F0
	FMULD F21, F1, F1
	FMOVD F0, (R0)
	FMOVD F1, 8(R0)
	ADD  $16, R0
	SUB  $1, R5
	CBNZ R5, dial_comp_norm

dial_comp_done:
	RET
