// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON loss kernels for f32: mse, mae, kl. Each fuses the per-element
// transform with the reduce so we touch each element once.

#include "textflag.h"

#define VFADD_S4(m, n, d)  WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFSUB_S4(m, n, d)  WORD $(0x4EA0D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_S4(m, n, d)  WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFMLA_S4(m, n, d)  WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFABS_S4(n, d)     WORD $(0x4EA0F800 | ((n) << 5) | (d))
#define VFADDP_S4(m, n, d) WORD $(0x6E30D400 | ((m) << 16) | ((n) << 5) | (d))
#define FADDP_S(n, d)      WORD $(0x7E30D800 | ((n) << 5) | (d))

// func MseSumNEONAsm(predictions, targets *float32, n int) float32
// Returns sum((p[i] - t[i])²). Caller divides by n.
TEXT ·MseSumNEONAsm(SB), NOSPLIT, $0-28
    MOVD predictions+0(FP), R0
    MOVD targets+8(FP), R1
    MOVD n+16(FP), R2

    VEOR V16.B16, V16.B16, V16.B16
    VEOR V17.B16, V17.B16, V17.B16
    VEOR V18.B16, V18.B16, V18.B16
    VEOR V19.B16, V19.B16, V19.B16

mse_loop16:
    CMP  $16, R2
    BLT  mse_loop4
    VLD1.P 64(R0), [V0.S4, V1.S4, V2.S4, V3.S4]
    VLD1.P 64(R1), [V4.S4, V5.S4, V6.S4, V7.S4]
    VFSUB_S4(4, 0, 0)
    VFSUB_S4(5, 1, 1)
    VFSUB_S4(6, 2, 2)
    VFSUB_S4(7, 3, 3)
    VFMLA_S4(0, 0, 16)
    VFMLA_S4(1, 1, 17)
    VFMLA_S4(2, 2, 18)
    VFMLA_S4(3, 3, 19)
    SUB  $16, R2
    B    mse_loop16

mse_loop4:
    CMP  $4, R2
    BLT  mse_reduce
    VLD1.P 16(R0), [V0.S4]
    VLD1.P 16(R1), [V4.S4]
    VFSUB_S4(4, 0, 0)
    VFMLA_S4(0, 0, 16)
    SUB  $4, R2
    B    mse_loop4

mse_reduce:
    VFADD_S4(17, 16, 16)
    VFADD_S4(18, 16, 16)
    VFADD_S4(19, 16, 16)
    VFADDP_S4(16, 16, 16)
    FADDP_S(16, 0)

    CBZ  R2, mse_done

mse_scalar_loop:
    FMOVS (R0), F1
    FMOVS (R1), F2
    FSUBS F2, F1, F1
    FMULS F1, F1, F1
    FADDS F1, F0, F0
    ADD  $4, R0
    ADD  $4, R1
    SUB  $1, R2
    CBNZ R2, mse_scalar_loop

mse_done:
    FMOVS F0, ret+24(FP)
    RET

// func MaeSumNEONAsm(predictions, targets *float32, n int) float32
// Returns sum(|p[i] - t[i]|).
TEXT ·MaeSumNEONAsm(SB), NOSPLIT, $0-28
    MOVD predictions+0(FP), R0
    MOVD targets+8(FP), R1
    MOVD n+16(FP), R2

    VEOR V16.B16, V16.B16, V16.B16
    VEOR V17.B16, V17.B16, V17.B16
    VEOR V18.B16, V18.B16, V18.B16
    VEOR V19.B16, V19.B16, V19.B16

mae_loop16:
    CMP  $16, R2
    BLT  mae_loop4
    VLD1.P 64(R0), [V0.S4, V1.S4, V2.S4, V3.S4]
    VLD1.P 64(R1), [V4.S4, V5.S4, V6.S4, V7.S4]
    VFSUB_S4(4, 0, 0)
    VFSUB_S4(5, 1, 1)
    VFSUB_S4(6, 2, 2)
    VFSUB_S4(7, 3, 3)
    VFABS_S4(0, 0)
    VFABS_S4(1, 1)
    VFABS_S4(2, 2)
    VFABS_S4(3, 3)
    VFADD_S4(0, 16, 16)
    VFADD_S4(1, 17, 17)
    VFADD_S4(2, 18, 18)
    VFADD_S4(3, 19, 19)
    SUB  $16, R2
    B    mae_loop16

mae_loop4:
    CMP  $4, R2
    BLT  mae_reduce
    VLD1.P 16(R0), [V0.S4]
    VLD1.P 16(R1), [V4.S4]
    VFSUB_S4(4, 0, 0)
    VFABS_S4(0, 0)
    VFADD_S4(0, 16, 16)
    SUB  $4, R2
    B    mae_loop4

mae_reduce:
    VFADD_S4(17, 16, 16)
    VFADD_S4(18, 16, 16)
    VFADD_S4(19, 16, 16)
    VFADDP_S4(16, 16, 16)
    FADDP_S(16, 0)

    CBZ  R2, mae_done

mae_scalar_loop:
    FMOVS (R0), F1
    FMOVS (R1), F2
    FSUBS F2, F1, F1
    FABSS F1, F1
    FADDS F1, F0, F0
    ADD  $4, R0
    ADD  $4, R1
    SUB  $1, R2
    CBNZ R2, mae_scalar_loop

mae_done:
    FMOVS F0, ret+24(FP)
    RET
