// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON int4 (packed nibble) dequantization. Two int4 values per byte,
// low nibble = element 2k, high nibble = element 2k+1. Each nibble is
// a signed 4-bit value sign-extended to int8.
//
// Pipeline per 16 nibbles (8 input bytes):
//   load 8 bytes  → V0.B8 = [pair0..pair7]
//   sign-extend low nibbles: V1.B8 = (V0 << 4) >> 4 (arithmetic)
//   sign-extend high nibbles: V2.B8 = V0 >> 4 (arithmetic)
//   interleave: V3.B16 = ZIP1(V1, V2) gives [lo0, hi0, lo1, hi1, ...]
//   subtract zeroPoint (broadcast int8) → V4.B16
//   sign-extend int8→int16 (SXTL/SXTL2) → 2 vectors .H8
//   sign-extend int16→int32 (SXTL/SXTL2) → 4 vectors .S4
//   SCVTF int32→f32 (4×)
//   FMUL by scale (4×)
//   store 16 f32 lanes
//
// Matches the scalar reference:
//   value = nibble - zeroPoint
//   out[i] = float32(value) * scale

#include "textflag.h"

// SHL .B8 by 4: 0x0F0C5400
#define VSHL_B8_BY4(n, d)    WORD $(0x0F0C5400 | ((n) << 5) | (d))
// SSHR .B8 by 4 (arithmetic right shift): 0x0F0C0400
#define VSSHR_B8_BY4(n, d)   WORD $(0x0F0C0400 | ((n) << 5) | (d))
// ZIP1 .B16: interleave low halves of two B8 vectors into one B16
// Encoding ZIP1 .16B: 0|1|0|01110|00|0|Rm|0|011|1|0|Rn|Rd = 0x4E003800
#define VZIP1_B16(m, n, d)   WORD $(0x4E003800 | ((m) << 16) | ((n) << 5) | (d))
// SUB vector .B16 (integer): 0|1|1|01110|00|1|Rm|10000|1|Rn|Rd = 0x6E208400
#define VSUB_B16(m, n, d)    WORD $(0x6E208400 | ((m) << 16) | ((n) << 5) | (d))
// SXTL/SXTL2 chain (from int8 dequant kernel).
#define VSXTL_H8(n, d)       WORD $(0x0F08A400 | ((n) << 5) | (d))
#define VSXTL2_H8(n, d)      WORD $(0x4F08A400 | ((n) << 5) | (d))
#define VSXTL_S4(n, d)       WORD $(0x0F10A400 | ((n) << 5) | (d))
#define VSXTL2_S4(n, d)      WORD $(0x4F10A400 | ((n) << 5) | (d))
#define VSCVTF_S4(n, d)      WORD $(0x4E21D800 | ((n) << 5) | (d))
#define VFMUL_S4(m, n, d)    WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))

// func DequantInt4NEONAsm(dst *float32, src *byte, n int, scale float32, zeroPoint int8)
TEXT ·DequantInt4NEONAsm(SB), NOSPLIT, $0-29
    MOVD dst+0(FP), R0
    MOVD src+8(FP), R1
    MOVD n+16(FP), R2
    FMOVS scale+24(FP), F30
    MOVBU zeroPoint+28(FP), R3

    VDUP V30.S[0], V30.S4
    // Broadcast zeroPoint as int8 across V31.B16. The low 8 bits hold
    // the value; sign-extension of the broadcasted lane happens below
    // when we widen .B → .H → .S.
    VMOV R3, V31.B[0]
    VDUP V31.B[0], V31.B16

dequant_int4_loop16:
    CMP  $16, R2
    BLT  dequant_int4_scalar_tail
    VLD1.P 8(R1), [V0.B8]
    VSHL_B8_BY4(0, 1)
    VSSHR_B8_BY4(1, 1)
    VSSHR_B8_BY4(0, 2)
    VZIP1_B16(2, 1, 3)
    VSUB_B16(31, 3, 4)
    VSXTL_H8(4, 5)
    VSXTL2_H8(4, 6)
    VSXTL_S4(5, 7)
    VSXTL2_S4(5, 8)
    VSXTL_S4(6, 9)
    VSXTL2_S4(6, 10)
    VSCVTF_S4(7, 7)
    VSCVTF_S4(8, 8)
    VSCVTF_S4(9, 9)
    VSCVTF_S4(10, 10)
    VFMUL_S4(30, 7, 7)
    VFMUL_S4(30, 8, 8)
    VFMUL_S4(30, 9, 9)
    VFMUL_S4(30, 10, 10)
    VST1.P [V7.S4, V8.S4, V9.S4, V10.S4], 64(R0)
    SUB  $16, R2
    B    dequant_int4_loop16

dequant_int4_scalar_tail:
    CBZ  R2, dequant_int4_done

    // Scalar tail: process logical elements one at a time. We need to
    // track whether we're at a low- or high-nibble position. For
    // simplicity, the tail always re-reads the current byte and
    // selects the right nibble. R4 tracks the parity (0 = low, 1 = high).
    MOVD ZR, R4

dequant_int4_scalar_loop:
    MOVBU (R1), R5

    // If R4 == 0, take low nibble; else take high nibble (shifted right by 4).
    CMP  $0, R4
    BEQ  dequant_int4_take_lo
    LSR  $4, R5, R5
dequant_int4_take_lo:
    AND  $0x0F, R5, R5
    // Sign-extend 4-bit value to int64 by shifting against the 64-bit
    // sign bit at position 63, then arithmetic-shift right by the same
    // amount. After this R5 holds a signed int with the sign of the
    // original 4-bit value.
    LSL  $60, R5, R5
    ASR  $60, R5, R5
    // Subtract zeroPoint (which is in R3, sign-extend it).
    SXTB R3, R6
    SUB  R6, R5, R5
    SCVTFWS R5, F0
    FMULS F30, F0, F0
    FMOVS F0, (R0)
    ADD  $4, R0

    // Advance the source: if we just consumed the high nibble, advance R1 by 1.
    EOR  $1, R4, R4
    CMP  $1, R4
    BEQ  dequant_int4_next_iter
    ADD  $1, R1

dequant_int4_next_iter:
    SUB  $1, R2
    CBNZ R2, dequant_int4_scalar_loop

dequant_int4_done:
    RET
