// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON int8 dequantization: out[i] = float32(q[i] - zeroPoint) * scale.
// Processes 16 int8 lanes per inner iteration:
//   load .B16 → SXTL/SXTL2 → 2 .H8 int16 vectors → subtract zeroPoint
//   → SXTL/SXTL2 each → 4 .S4 int32 vectors → SCVTF int32→f32 → FMUL scale
// 16 lanes × 4 bytes per f32 = 64 bytes written per iteration.

#include "textflag.h"

// SXTL Vd.H8, Vn.B8 (sign-extend, low half)
#define VSXTL_H8(n, d)   WORD $(0x0F08A400 | ((n) << 5) | (d))
// SXTL2 Vd.H8, Vn.B16 (sign-extend, high half)
#define VSXTL2_H8(n, d)  WORD $(0x4F08A400 | ((n) << 5) | (d))
// SXTL Vd.S4, Vn.H4
#define VSXTL_S4(n, d)   WORD $(0x0F10A400 | ((n) << 5) | (d))
// SXTL2 Vd.S4, Vn.H8
#define VSXTL2_S4(n, d)  WORD $(0x4F10A400 | ((n) << 5) | (d))
// SCVTF Vd.4S, Vn.4S (signed int32 → f32)
#define VSCVTF_S4(n, d)  WORD $(0x4E21D800 | ((n) << 5) | (d))
// SUB vector .H8 (signed/unsigned identical for narrow-add semantics)
#define VSUB_H8(m, n, d) WORD $(0x6E608400 | ((m) << 16) | ((n) << 5) | (d))
// FMUL vector .4S
#define VFMUL_S4(m, n, d) WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))

// func DequantInt8NEONAsm(dst *float32, src *int8, n int, scale float32, zeroPoint int16)
// Args: dst 8B at 0, src 8B at 8, n 8B at 16, scale 4B at 24, zp 2B at 28
TEXT ·DequantInt8NEONAsm(SB), NOSPLIT, $0-30
    MOVD dst+0(FP), R0
    MOVD src+8(FP), R1
    MOVD n+16(FP), R2
    FMOVS scale+24(FP), F30
    MOVHU zeroPoint+28(FP), R3

    // Broadcast scale across V30.S4.
    VDUP V30.S[0], V30.S4
    // Broadcast zeroPoint (as int16) across V31.H8.
    VMOV R3, V31.H[0]
    VDUP V31.H[0], V31.H8

dequant_int8_loop16:
    CMP  $16, R2
    BLT  dequant_int8_loop8
    VLD1.P 16(R1), [V0.B16]
    VSXTL_H8(0, 1)
    VSXTL2_H8(0, 2)
    VSUB_H8(31, 1, 1)
    VSUB_H8(31, 2, 2)
    VSXTL_S4(1, 3)
    VSXTL2_S4(1, 4)
    VSXTL_S4(2, 5)
    VSXTL2_S4(2, 6)
    VSCVTF_S4(3, 3)
    VSCVTF_S4(4, 4)
    VSCVTF_S4(5, 5)
    VSCVTF_S4(6, 6)
    VFMUL_S4(30, 3, 3)
    VFMUL_S4(30, 4, 4)
    VFMUL_S4(30, 5, 5)
    VFMUL_S4(30, 6, 6)
    VST1.P [V3.S4, V4.S4, V5.S4, V6.S4], 64(R0)
    SUB  $16, R2
    B    dequant_int8_loop16

dequant_int8_loop8:
    CMP  $8, R2
    BLT  dequant_int8_scalar_tail
    // Read 8 bytes as .B8 via VLD1; SXTL writes to .H8 (8 int16 lanes).
    VLD1.P 8(R1), [V0.B8]
    VSXTL_H8(0, 1)
    VSUB_H8(31, 1, 1)
    VSXTL_S4(1, 3)
    VSXTL2_S4(1, 4)
    VSCVTF_S4(3, 3)
    VSCVTF_S4(4, 4)
    VFMUL_S4(30, 3, 3)
    VFMUL_S4(30, 4, 4)
    VST1.P [V3.S4, V4.S4], 32(R0)
    SUB  $8, R2
    B    dequant_int8_loop8

dequant_int8_scalar_tail:
    CBZ  R2, dequant_int8_done

dequant_int8_scalar_loop:
    MOVBU.P 1(R1), R4
    // Sign-extend the byte: bit 7 propagates.
    SXTB R4, R4
    // Subtract zeroPoint (which was zero-extended into R3 — sign-extend it too).
    SXTH R3, R5
    SUB  R5, R4, R4
    SCVTFWS R4, F0
    FMULS F30, F0, F0
    FMOVS F0, (R0)
    ADD  $4, R0
    SUB  $1, R2
    CBNZ R2, dequant_int8_scalar_loop

dequant_int8_done:
    RET
