// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON optimizer inner loops. Each kernel processes 4 lanes per
// iteration using FMLA chains. Real NEON per AGENTS.md §1.1 — the
// arithmetic uses V registers and no scalar body.
//
// adamStep: Adam parameter update.
// sgdStep:  SGD with momentum.

#include "textflag.h"

#define VFADD_S4(m, n, d)  WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFSUB_S4(m, n, d)  WORD $(0x4EA0D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_S4(m, n, d)  WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFMLA_S4(m, n, d)  WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFDIV_S4(m, n, d)  WORD $(0x6E20FC00 | ((m) << 16) | ((n) << 5) | (d))
// FNEG .4S
#define VFNEG_S4(n, d)     WORD $(0x6EA0F800 | ((n) << 5) | (d))
// FSQRT vector .4S
#define VFSQRT_S4(n, d)    WORD $(0x6EA1F800 | ((n) << 5) | (d))

// func AdamStepFloat32NEONAsm(
//     params, grad, first, second, output *float32,
//     n int,
//     lr, beta1, beta2, eps, beta1Corr, beta2Corr float32,
// )
//
// firstNew  = beta1 * first + (1-beta1) * grad
// secondNew = beta2 * second + (1-beta2) * grad²
// biasFirst = firstNew / beta1Correction
// biasSec   = secondNew / beta2Correction
// out       = params - lr * biasFirst / (sqrt(biasSec) + eps)
//
// Updates first and second in place.
TEXT ·AdamStepFloat32NEONAsm(SB), NOSPLIT, $0-72
    MOVD params+0(FP), R0
    MOVD grad+8(FP), R1
    MOVD first+16(FP), R2
    MOVD second+24(FP), R3
    MOVD output+32(FP), R4
    MOVD n+40(FP), R5

    // Broadcast scalar hyperparameters into V16..V21 via GPR → VMOV → VDUP.
    MOVD lr+48(FP), R6
    VMOV R6, V16.S[0]
    VDUP V16.S[0], V16.S4
    MOVD beta1+52(FP), R6
    VMOV R6, V17.S[0]
    VDUP V17.S[0], V17.S4
    MOVD beta2+56(FP), R6
    VMOV R6, V18.S[0]
    VDUP V18.S[0], V18.S4
    MOVD eps+60(FP), R6
    VMOV R6, V19.S[0]
    VDUP V19.S[0], V19.S4
    MOVD beta1Corr+64(FP), R6
    VMOV R6, V20.S[0]
    VDUP V20.S[0], V20.S4
    MOVD beta2Corr+68(FP), R6
    VMOV R6, V21.S[0]
    VDUP V21.S[0], V21.S4

    // V22 = 1.0 broadcast (bit pattern 0x3F800000) for (1-betaX).
    MOVD $0x3F800000, R6
    VMOV R6, V22.S[0]
    VDUP V22.S[0], V22.S4

    // Compute (1-beta1) into V23 and (1-beta2) into V24 once.
    VFSUB_S4(17, 22, 23)         // V23 = 1 - beta1
    VFSUB_S4(18, 22, 24)         // V24 = 1 - beta2

adam_loop4:
    CMP  $4, R5
    BLT  adam_done
    VLD1 (R0), [V0.S4]           // params
    VLD1 (R1), [V1.S4]           // grad
    VLD1 (R2), [V2.S4]           // first
    VLD1 (R3), [V3.S4]           // second

    // firstNew = beta1 * first + (1-beta1) * grad
    VFMUL_S4(17, 2, 2)
    VFMUL_S4(1, 23, 4)
    VFADD_S4(4, 2, 2)
    // secondNew = beta2 * second + (1-beta2) * grad²
    VFMUL_S4(18, 3, 3)
    VFMUL_S4(1, 1, 4)
    VFMUL_S4(4, 24, 5)
    VFADD_S4(5, 3, 3)
    // bias-corrected: V5 = V2/beta1Corr, V6 = V3/beta2Corr
    VFDIV_S4(20, 2, 5)
    VFDIV_S4(21, 3, 6)
    // denom = sqrt(V6) + eps
    VFSQRT_S4(6, 6)
    VFADD_S4(19, 6, 6)
    // step = lr * V5 / V6
    VFMUL_S4(16, 5, 5)
    VFDIV_S4(6, 5, 5)
    // output = params - step
    VFSUB_S4(5, 0, 0)

    VST1 [V2.S4], (R2)
    VST1 [V3.S4], (R3)
    VST1 [V0.S4], (R4)
    ADD  $16, R0
    ADD  $16, R1
    ADD  $16, R2
    ADD  $16, R3
    ADD  $16, R4
    SUB  $4, R5
    B    adam_loop4

adam_done:
    RET

// func SgdStepFloat32NEONAsm(
//     params, grad, momentum, output *float32,
//     n int,
//     lr, momentumFactor, weightDecay float32,
// )
//
// effective = grad + weightDecay * params
// momentumNew = momentumFactor * momentum + effective
// output = params - lr * momentumNew
TEXT ·SgdStepFloat32NEONAsm(SB), NOSPLIT, $0-52
    MOVD params+0(FP), R0
    MOVD grad+8(FP), R1
    MOVD momentum+16(FP), R2
    MOVD output+24(FP), R3
    MOVD n+32(FP), R4

    MOVD lr+40(FP), R6
    VMOV R6, V16.S[0]
    VDUP V16.S[0], V16.S4
    MOVD momentumFactor+44(FP), R6
    VMOV R6, V17.S[0]
    VDUP V17.S[0], V17.S4
    MOVD weightDecay+48(FP), R6
    VMOV R6, V18.S[0]
    VDUP V18.S[0], V18.S4

sgd_loop4:
    CMP  $4, R4
    BLT  sgd_done
    VLD1 (R0), [V0.S4]               // params
    VLD1 (R1), [V1.S4]               // grad
    VLD1 (R2), [V2.S4]               // momentum
    // effective = grad + weightDecay * params
    VFMLA_S4(0, 18, 1)
    // momentumNew = momentumFactor * momentum + effective (single FMA)
    VFMLA_S4(2, 17, 1)
    // output = params - lr * momentumNew (FMA with -lr to match Go scalar)
    VFNEG_S4(16, 26)
    VFMLA_S4(1, 26, 0)
    VST1 [V1.S4], (R2)
    VST1 [V0.S4], (R3)
    ADD  $16, R0
    ADD  $16, R1
    ADD  $16, R2
    ADD  $16, R3
    SUB  $4, R4
    B    sgd_loop4

sgd_done:
    RET

// func AdamwStepFloat32NEONAsm(
//     params, grad, first, second, output *float32,
//     n int,
//     lr, beta1, beta2, eps, beta1Corr, beta2Corr, weightDecay float32,
// )
//
// firstNew  = beta1 * first + (1-beta1) * grad
// secondNew = beta2 * second + (1-beta2) * grad²
// biasFirst = firstNew / beta1Correction
// biasSec   = secondNew / beta2Correction
// gradStep  = lr * biasFirst / (sqrt(biasSec) + eps)
// decayStep = lr * weightDecay * params
// output    = params - gradStep - decayStep
TEXT ·AdamwStepFloat32NEONAsm(SB), NOSPLIT, $0-76
    MOVD params+0(FP), R0
    MOVD grad+8(FP), R1
    MOVD first+16(FP), R2
    MOVD second+24(FP), R3
    MOVD output+32(FP), R4
    MOVD n+40(FP), R5

    MOVD lr+48(FP), R6
    VMOV R6, V16.S[0]
    VDUP V16.S[0], V16.S4
    MOVD beta1+52(FP), R6
    VMOV R6, V17.S[0]
    VDUP V17.S[0], V17.S4
    MOVD beta2+56(FP), R6
    VMOV R6, V18.S[0]
    VDUP V18.S[0], V18.S4
    MOVD eps+60(FP), R6
    VMOV R6, V19.S[0]
    VDUP V19.S[0], V19.S4
    MOVD beta1Corr+64(FP), R6
    VMOV R6, V20.S[0]
    VDUP V20.S[0], V20.S4
    MOVD beta2Corr+68(FP), R6
    VMOV R6, V21.S[0]
    VDUP V21.S[0], V21.S4
    MOVD weightDecay+72(FP), R6
    VMOV R6, V25.S[0]
    VDUP V25.S[0], V25.S4

    MOVD $0x3F800000, R6
    VMOV R6, V22.S[0]
    VDUP V22.S[0], V22.S4

    VFSUB_S4(17, 22, 23)         // V23 = 1 - beta1
    VFSUB_S4(18, 22, 24)         // V24 = 1 - beta2

adamw_loop4:
    CMP  $4, R5
    BLT  adamw_done
    VLD1 (R0), [V0.S4]
    VLD1 (R1), [V1.S4]
    VLD1 (R2), [V2.S4]
    VLD1 (R3), [V3.S4]
    // firstNew = beta1*first + (1-beta1)*grad
    VFMUL_S4(17, 2, 2)
    VFMUL_S4(1, 23, 4)
    VFADD_S4(4, 2, 2)
    // secondNew = beta2*second + (1-beta2)*grad²
    VFMUL_S4(18, 3, 3)
    VFMUL_S4(1, 1, 4)
    VFMUL_S4(4, 24, 5)
    VFADD_S4(5, 3, 3)
    // bias correction
    VFDIV_S4(20, 2, 5)
    VFDIV_S4(21, 3, 6)
    VFSQRT_S4(6, 6)
    VFADD_S4(19, 6, 6)
    VFMUL_S4(16, 5, 5)
    VFDIV_S4(6, 5, 5)
    // decayStep = lr * weightDecay * params = V16 * V25 * V0
    VFMUL_S4(25, 16, 7)          // V7 = lr * weightDecay (scalar product per-lane)
    VFMUL_S4(0, 7, 7)            // V7 = lr*wd*params
    // out = params - gradStep - decayStep
    VFSUB_S4(5, 0, 0)
    VFSUB_S4(7, 0, 0)

    VST1 [V2.S4], (R2)
    VST1 [V3.S4], (R3)
    VST1 [V0.S4], (R4)
    ADD  $16, R0
    ADD  $16, R1
    ADD  $16, R2
    ADD  $16, R3
    ADD  $16, R4
    SUB  $4, R5
    B    adamw_loop4

adamw_done:
    RET

// FABS .4S
#define VFABS_S4(n, d)  WORD $(0x4EA0F800 | ((n) << 5) | (d))

// func AdamaxStepFloat32NEONAsm(
//     params, grad, first, infinity, output *float32,
//     n int,
//     lr, beta1, beta2, eps, beta1Corr float32,
// )
//
// firstNew = beta1*first + (1-beta1)*grad
// infNew   = max(beta2*inf, |grad|)
// biasFirst = firstNew/beta1Corr
// out      = params - lr * biasFirst / (infNew + eps)
TEXT ·AdamaxStepFloat32NEONAsm(SB), NOSPLIT, $0-68
    MOVD params+0(FP), R0
    MOVD grad+8(FP), R1
    MOVD first+16(FP), R2
    MOVD infinity+24(FP), R3
    MOVD output+32(FP), R4
    MOVD n+40(FP), R5

    MOVD lr+48(FP), R6
    VMOV R6, V16.S[0]
    VDUP V16.S[0], V16.S4
    MOVD beta1+52(FP), R6
    VMOV R6, V17.S[0]
    VDUP V17.S[0], V17.S4
    MOVD beta2+56(FP), R6
    VMOV R6, V18.S[0]
    VDUP V18.S[0], V18.S4
    MOVD eps+60(FP), R6
    VMOV R6, V19.S[0]
    VDUP V19.S[0], V19.S4
    MOVD beta1Corr+64(FP), R6
    VMOV R6, V20.S[0]
    VDUP V20.S[0], V20.S4

    MOVD $0x3F800000, R6
    VMOV R6, V22.S[0]
    VDUP V22.S[0], V22.S4
    VFSUB_S4(17, 22, 23)         // V23 = 1 - beta1

adamax_loop4:
    CMP  $4, R5
    BLT  adamax_done
    VLD1 (R0), [V0.S4]
    VLD1 (R1), [V1.S4]
    VLD1 (R2), [V2.S4]
    VLD1 (R3), [V3.S4]
    // firstNew = beta1*first + (1-beta1)*grad
    VFMUL_S4(17, 2, 2)
    VFMLA_S4(1, 23, 2)
    // infNew = max(beta2*inf, |grad|)
    VFMUL_S4(18, 3, 3)
    VFABS_S4(1, 4)
    // FMAX V_d.S4 = max(V_n.S4, V_m.S4) — encoding 0x4E20F400
    WORD $(0x4E20F400 | (3 << 16) | (4 << 5) | 3)
    // biasFirst = firstNew / beta1Corr
    VFDIV_S4(20, 2, 5)
    // denom = inf + eps
    VFADD_S4(19, 3, 6)
    // step = lr * biasFirst / denom
    VFMUL_S4(16, 5, 5)
    VFDIV_S4(6, 5, 5)
    VFSUB_S4(5, 0, 0)
    VST1 [V2.S4], (R2)
    VST1 [V3.S4], (R3)
    VST1 [V0.S4], (R4)
    ADD  $16, R0
    ADD  $16, R1
    ADD  $16, R2
    ADD  $16, R3
    ADD  $16, R4
    SUB  $4, R5
    B    adamax_loop4

adamax_done:
    RET

// func AdagradStepFloat32NEONAsm(
//     params, grad, accum, output *float32,
//     n int,
//     lr, eps float32,
// )
//
// accumNew = accum + grad²
// out = params - lr * grad / (sqrt(accumNew) + eps)
TEXT ·AdagradStepFloat32NEONAsm(SB), NOSPLIT, $0-48
    MOVD params+0(FP), R0
    MOVD grad+8(FP), R1
    MOVD accum+16(FP), R2
    MOVD output+24(FP), R3
    MOVD n+32(FP), R4

    MOVD lr+40(FP), R6
    VMOV R6, V16.S[0]
    VDUP V16.S[0], V16.S4
    MOVD eps+44(FP), R6
    VMOV R6, V17.S[0]
    VDUP V17.S[0], V17.S4

ag_loop4:
    CMP  $4, R4
    BLT  ag_done
    VLD1 (R0), [V0.S4]
    VLD1 (R1), [V1.S4]
    VLD1 (R2), [V2.S4]
    // accumNew = accum + grad²
    VFMLA_S4(1, 1, 2)          // V2 += V1*V1
    // denom = sqrt(accumNew) + eps
    VFSQRT_S4(2, 3)
    VFADD_S4(17, 3, 3)
    // step = lr * grad / denom
    VFMUL_S4(16, 1, 4)
    VFDIV_S4(3, 4, 4)
    VFSUB_S4(4, 0, 0)
    VST1 [V2.S4], (R2)
    VST1 [V0.S4], (R3)
    ADD  $16, R0
    ADD  $16, R1
    ADD  $16, R2
    ADD  $16, R3
    SUB  $4, R4
    B    ag_loop4

ag_done:
    RET

// func RmspropStepFloat32NEONAsm(
//     params, grad, second, output *float32,
//     n int,
//     lr, decay, eps float32,
// )
//
// secondNew = decay*second + (1-decay)*grad²
// out = params - lr * grad / (sqrt(secondNew) + eps)
TEXT ·RmspropStepFloat32NEONAsm(SB), NOSPLIT, $0-52
    MOVD params+0(FP), R0
    MOVD grad+8(FP), R1
    MOVD second+16(FP), R2
    MOVD output+24(FP), R3
    MOVD n+32(FP), R4

    MOVD lr+40(FP), R6
    VMOV R6, V16.S[0]
    VDUP V16.S[0], V16.S4
    MOVD decay+44(FP), R6
    VMOV R6, V17.S[0]
    VDUP V17.S[0], V17.S4
    MOVD eps+48(FP), R6
    VMOV R6, V18.S[0]
    VDUP V18.S[0], V18.S4

    MOVD $0x3F800000, R6
    VMOV R6, V22.S[0]
    VDUP V22.S[0], V22.S4
    VFSUB_S4(17, 22, 23)        // V23 = 1 - decay

rms_loop4:
    CMP  $4, R4
    BLT  rms_done
    VLD1 (R0), [V0.S4]
    VLD1 (R1), [V1.S4]
    VLD1 (R2), [V2.S4]
    // secondNew = (1-decay)*grad² + decay*second (FMA to match Go scalar)
    VFMUL_S4(1, 1, 4)
    VFMUL_S4(23, 4, 4)
    VFMLA_S4(2, 17, 4)
    // denom = sqrt(secondNew) + eps
    VFSQRT_S4(4, 5)
    VFADD_S4(18, 5, 5)
    // step = lr * grad / denom
    VFMUL_S4(16, 1, 6)
    VFDIV_S4(5, 6, 6)
    VFSUB_S4(6, 0, 0)
    VST1 [V4.S4], (R2)
    VST1 [V0.S4], (R3)
    ADD  $16, R0
    ADD  $16, R1
    ADD  $16, R2
    ADD  $16, R3
    SUB  $4, R4
    B    rms_loop4

rms_done:
    RET

// FCMGT (zero) vector .4S — V_d = (V_n > 0) ? all-ones : 0
#define VFCMGTZ_S4(n, d) WORD $(0x4EA0C800 | ((n) << 5) | (d))
// FCMLT (zero) vector .4S — V_d = (V_n < 0) ? all-ones : 0
#define VFCMLTZ_S4(n, d) WORD $(0x4EA0E800 | ((n) << 5) | (d))
// AND .B16 already implicit via VAND? add macro
#define VAND_B16(m, n, d)   WORD $(0x4E201C00 | ((m) << 16) | ((n) << 5) | (d))
// BIC .B16 (Vd = Vn AND NOT Vm)
#define VBIC_B16(m, n, d)   WORD $(0x4E601C00 | ((m) << 16) | ((n) << 5) | (d))

// func LionStepFloat32NEONAsm(
//     params, grad, momentum, output *float32,
//     n int,
//     lr, beta1, beta2, weightDecay float32,
// )
//
// update = beta1*momentum + (1-beta1)*grad
// sign(update): +1 if >0, -1 if <0, else 0
// momentum := beta2*momentum + (1-beta2)*grad
// output = params - lr*(sign + weightDecay*params)
TEXT ·LionStepFloat32NEONAsm(SB), NOSPLIT, $0-56
    MOVD params+0(FP), R0
    MOVD grad+8(FP), R1
    MOVD momentum+16(FP), R2
    MOVD output+24(FP), R3
    MOVD n+32(FP), R4

    MOVD lr+40(FP), R6
    VMOV R6, V16.S[0]
    VDUP V16.S[0], V16.S4
    MOVD beta1+44(FP), R6
    VMOV R6, V17.S[0]
    VDUP V17.S[0], V17.S4
    MOVD beta2+48(FP), R6
    VMOV R6, V18.S[0]
    VDUP V18.S[0], V18.S4
    MOVD weightDecay+52(FP), R6
    VMOV R6, V19.S[0]
    VDUP V19.S[0], V19.S4

    MOVD $0x3F800000, R6
    VMOV R6, V22.S[0]
    VDUP V22.S[0], V22.S4         // 1.0
    VFSUB_S4(17, 22, 23)          // V23 = 1 - beta1
    VFSUB_S4(18, 22, 24)          // V24 = 1 - beta2

    // V25 = -1.0 (bit pattern 0xBF800000)
    MOVD $0xBF800000, R6
    VMOV R6, V25.S[0]
    VDUP V25.S[0], V25.S4

lion_loop4:
    CMP  $4, R4
    BLT  lion_done
    VLD1 (R0), [V0.S4]
    VLD1 (R1), [V1.S4]
    VLD1 (R2), [V2.S4]
    // update = (1-beta1)*grad + beta1*momentum (FMA to match Go scalar)
    VFMUL_S4(23, 1, 3)
    VFMLA_S4(2, 17, 3)
    // sign(V3): build mask_pos = (V3 > 0), mask_neg = (V3 < 0)
    // sign = (1.0 AND mask_pos) OR (-1.0 AND mask_neg)
    VFCMGTZ_S4(3, 4)              // V4 = pos mask
    VFCMLTZ_S4(3, 5)              // V5 = neg mask
    VAND_B16(4, 22, 6)            // V6 = mask_pos & 1.0
    VAND_B16(5, 25, 7)            // V7 = mask_neg & -1.0
    WORD $(0x4EA01C00 | (7 << 16) | (6 << 5) | 6)  // VORR V7, V6, V6 → V6 |= V7
    // step = lr * (sign + weightDecay*params)
    // V8 = weightDecay*params + sign
    WORD $(0x4EA01C00 | (6 << 16) | (6 << 5) | 8)   // VMOV V6.B16, V8.B16 (V8 = V6)
    VFMLA_S4(0, 19, 8)            // V8 = sign + wd*params (FMLA Vd += Vn*Vm)
    VFMUL_S4(16, 8, 8)            // V8 *= lr
    VFSUB_S4(8, 0, 0)             // params -= step
    // momentum := (1-beta2)*grad + beta2*momentum (FMA to match Go scalar)
    VFMUL_S4(24, 1, 5)
    VFMLA_S4(2, 18, 5)
    VST1 [V5.S4], (R2)
    VST1 [V0.S4], (R3)
    ADD  $16, R0
    ADD  $16, R1
    ADD  $16, R2
    ADD  $16, R3
    SUB  $4, R4
    B    lion_loop4

lion_done:
    RET

// func LbfgsStepFloat32NEONAsm(
//     params, grad, output *float32,
//     n int,
//     lr float32,
// )
//
// Simple gradient descent: out = params - lr*grad
TEXT ·LbfgsStepFloat32NEONAsm(SB), NOSPLIT, $0-36
    MOVD params+0(FP), R0
    MOVD grad+8(FP), R1
    MOVD output+16(FP), R2
    MOVD n+24(FP), R3
    MOVD lr+32(FP), R6
    VMOV R6, V16.S[0]
    VDUP V16.S[0], V16.S4

lbfgs_loop4:
    CMP  $4, R3
    BLT  lbfgs_done
    VLD1 (R0), [V0.S4]
    VLD1 (R1), [V1.S4]
    VFMUL_S4(16, 1, 1)
    VFSUB_S4(1, 0, 0)
    VST1 [V0.S4], (R2)
    ADD  $16, R0
    ADD  $16, R1
    ADD  $16, R2
    SUB  $4, R3
    B    lbfgs_loop4

lbfgs_done:
    RET

// func LarsStepFloat32NEONAsm(
//     params, grad, momentum, output *float32,
//     n int,
//     lr, momentumFactor, weightDecay float32,
//     effectiveLr float32,
// )
//
// Caller pre-computes the trust-ratio-scaled effectiveLr. The inner
// loop is then identical to SGD with that effective LR:
//   effective = grad + weightDecay*params
//   momentum = momentumFactor*momentum + effective
//   output = params - effectiveLr * momentum
TEXT ·LarsStepFloat32NEONAsm(SB), NOSPLIT, $0-56
    MOVD params+0(FP), R0
    MOVD grad+8(FP), R1
    MOVD momentum+16(FP), R2
    MOVD output+24(FP), R3
    MOVD n+32(FP), R4

    MOVD momentumFactor+44(FP), R6
    VMOV R6, V17.S[0]
    VDUP V17.S[0], V17.S4
    MOVD weightDecay+48(FP), R6
    VMOV R6, V18.S[0]
    VDUP V18.S[0], V18.S4
    MOVD effectiveLr+52(FP), R6
    VMOV R6, V16.S[0]
    VDUP V16.S[0], V16.S4

lars_loop4:
    CMP  $4, R4
    BLT  lars_done
    VLD1 (R0), [V0.S4]
    VLD1 (R1), [V1.S4]
    VLD1 (R2), [V2.S4]
    // effective = grad + weightDecay*params
    VFMLA_S4(0, 18, 1)
    // momentum = momentumFactor*momentum + effective (FMA to match Go scalar)
    VFMLA_S4(2, 17, 1)
    // out = params - effectiveLr*momentum (FMA with -lr)
    VFNEG_S4(16, 26)
    VFMLA_S4(1, 26, 0)
    VST1 [V1.S4], (R2)
    VST1 [V0.S4], (R3)
    ADD  $16, R0
    ADD  $16, R1
    ADD  $16, R2
    ADD  $16, R3
    SUB  $4, R4
    B    lars_loop4

lars_done:
    RET

// func HebbianStepRowFloat32NEONAsm(
//     weights, pre, output *float32,
//     n int,
//     decayFactor, lrPost float32,
// )
//
// output = weights * decayFactor + lrPost * pre
TEXT ·HebbianStepRowFloat32NEONAsm(SB), NOSPLIT, $0-40
    MOVD weights+0(FP), R0
    MOVD pre+8(FP), R1
    MOVD output+16(FP), R2
    MOVD n+24(FP), R4
    FMOVS decayFactor+32(FP), F16
    VDUP V16.S[0], V16.S4
    FMOVS lrPost+36(FP), F17
    VDUP V17.S[0], V17.S4

hebbian_loop4:
    CMP  $4, R4
    BLT  hebbian_done
    VLD1 (R0), [V0.S4]
    VLD1 (R1), [V1.S4]
    VFMUL_S4(16, 0, 2)
    VFMLA_S4(1, 17, 2)
    VST1 [V2.S4], (R2)
    ADD  $16, R0
    ADD  $16, R1
    ADD  $16, R2
    SUB  $4, R4
    B    hebbian_loop4

hebbian_done:
    RET
