// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON float32 causal kernels: counterfactual estimator and strided dot.

#include "textflag.h"

#define VFADD_S4(m, n, d) WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFSUB_S4(m, n, d) WORD $(0x4EA0D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_S4(m, n, d) WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFMLA_S4(m, n, d) WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))

// func CounterfactualF32NEONAsm(out, observedY, observedX, counterfactualX *float32, slope float32, n int)
// out[i] = observedY[i] + slope * (counterfactualX[i] - observedX[i])
TEXT ·CounterfactualF32NEONAsm(SB), NOSPLIT, $8-48
	MOVD  out+0(FP), R0
	MOVD  observedY+8(FP), R1
	MOVD  observedX+16(FP), R2
	MOVD  counterfactualX+24(FP), R3
	FMOVS slope+32(FP), F31
	MOVD  n+40(FP), R4
	FMOVS F31, 0(RSP)
	VDUP  V31.S[0], V31.S4
	CBZ   R4, cf_done

cf_loop4:
	CMP  $4, R4
	BLT  cf_scalar_tail
	VLD1.P 16(R3), [V0.S4]
	VLD1.P 16(R2), [V1.S4]
	VFSUB_S4(1, 0, 0)
	VFMUL_S4(31, 0, 0)
	VLD1.P 16(R1), [V2.S4]
	VFADD_S4(2, 0, 0)
	VST1.P [V0.S4], 16(R0)
	SUB  $4, R4
	B    cf_loop4

cf_scalar_tail:
	CBZ  R4, cf_done
	FMOVS (R3), F0
	FMOVS (R2), F1
	FSUBS F1, F0, F0
	FMULS F31, F0, F0
	FMOVS (R1), F1
	FADDS F0, F1, F0
	FMOVS F0, (R0)
	ADD  $4, R1
	ADD  $4, R2
	ADD  $4, R3
	ADD  $4, R0
	SUB  $1, R4
	B    cf_scalar_tail

cf_done:
	RET

// func StridedDotF32NEONAsm(values *float32, stride int, weights *float32, n int) float32
// sum_{index=0}^{n-1} values[index*stride] * weights[index]
TEXT ·StridedDotF32NEONAsm(SB), NOSPLIT, $0-32
	MOVD values+0(FP), R0
	MOVD stride+8(FP), R1
	MOVD weights+16(FP), R2
	MOVD n+24(FP), R3
	LSL  $2, R1, R1
	FMOVS $0, F0
	CBZ  R3, strided_done

strided_scalar_loop:
	FMOVS (R0), F1
	FMOVS (R2), F2
	FMULS F2, F1, F1
	FADDS F1, F0, F0
	ADD  R1, R0
	ADD  $4, R2
	SUB  $1, R3
	CBNZ R3, strided_scalar_loop

strided_done:
	FMOVS F0, ret+32(FP)
	RET
