// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON float32 periodic-stencil kernels for 1-D physics operators.

#include "textflag.h"

#define VFADD_S4(m, n, d) WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFSUB_S4(m, n, d) WORD $(0x4EA0D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_S4(m, n, d) WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFMLA_S4(m, n, d) WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))

// func Laplacian1DStencilF32NEONAsm(out, left, center, right *float32, invH2 float32, n int)
// out[i] = (left[i] + right[i] - 2*center[i]) * invH2
TEXT ·Laplacian1DStencilF32NEONAsm(SB), NOSPLIT, $8-48
	MOVD  out+0(FP), R0
	MOVD  left+8(FP), R1
	MOVD  center+16(FP), R2
	MOVD  right+24(FP), R3
	FMOVS invH2+32(FP), F31
	MOVD  n+40(FP), R4
	FMOVS F31, 0(RSP)
	VDUP  V31.S[0], V31.S4
	CBZ   R4, lap1_done

lap1_loop4:
	CMP  $4, R4
	BLT  lap1_scalar_tail
	VLD1.P 16(R1), [V0.S4]
	VLD1.P 16(R3), [V1.S4]
	VFADD_S4(1, 0, 0)
	VLD1.P 16(R2), [V2.S4]
	VFADD_S4(2, 2, 2)
	VFSUB_S4(2, 0, 0)
	VFMUL_S4(31, 0, 0)
	VST1.P [V0.S4], 16(R0)
	SUB  $4, R4
	B    lap1_loop4

lap1_scalar_tail:
	CBZ  R4, lap1_done
	FMOVS (R1), F0
	FMOVS (R3), F1
	FADDS F1, F0, F0
	FMOVS (R2), F2
	FADDS F2, F2, F2
	FSUBS F0, F2, F0
	FMULS F31, F0, F0
	FMOVS F0, (R0)
	ADD  $4, R1
	ADD  $4, R2
	ADD  $4, R3
	ADD  $4, R0
	SUB  $1, R4
	B    lap1_scalar_tail

lap1_done:
	RET

// func Grad1DStencilF32NEONAsm(out, left, right *float32, invTwoDx float32, n int)
// out[i] = (right[i] - left[i]) * invTwoDx
TEXT ·Grad1DStencilF32NEONAsm(SB), NOSPLIT, $8-40
	MOVD  out+0(FP), R0
	MOVD  left+8(FP), R1
	MOVD  right+16(FP), R2
	FMOVS invTwoDx+24(FP), F31
	MOVD  n+32(FP), R3
	FMOVS F31, 0(RSP)
	VDUP  V31.S[0], V31.S4
	CBZ   R3, grad_done

grad_loop4:
	CMP  $4, R3
	BLT  grad_scalar_tail
	VLD1.P 16(R2), [V0.S4]
	VLD1.P 16(R1), [V1.S4]
	VFSUB_S4(1, 0, 0)
	VFMUL_S4(31, 0, 0)
	VST1.P [V0.S4], 16(R0)
	SUB  $4, R3
	B    grad_loop4

grad_scalar_tail:
	CBZ  R3, grad_done
	FMOVS (R2), F0
	FMOVS (R1), F1
	FSUBS F1, F0, F0
	FMULS F31, F0, F0
	FMOVS F0, (R0)
	ADD  $4, R1
	ADD  $4, R2
	ADD  $4, R0
	SUB  $1, R3
	B    grad_scalar_tail

grad_done:
	RET

// func Laplacian4StencilF32NEONAsm(out, um2, um1, u0, up1, up2 *float32, invDen float32, n int)
// out[i] = (-um2 + 16*um1 - 30*u0 + 16*up1 - up2) * invDen
TEXT ·Laplacian4StencilF32NEONAsm(SB), NOSPLIT, $16-64
	MOVD  out+0(FP), R0
	MOVD  um2+8(FP), R1
	MOVD  um1+16(FP), R2
	MOVD  u0+24(FP), R3
	MOVD  up1+32(FP), R4
	MOVD  up2+40(FP), R5
	FMOVS invDen+48(FP), F31
	MOVD  n+56(FP), R6
	FMOVS F31, 0(RSP)
	VDUP  V31.S[0], V31.S4
	MOVD  $0x41800000, R7
	VMOV  R7, V29.S[0]
	VDUP  V29.S[0], V29.S4
	VMOV  V29.S[0], R7
	MOVD  R7, 4(RSP)
	MOVD  $0xC1F00000, R7
	VMOV  R7, V28.S[0]
	VDUP  V28.S[0], V28.S4
	VMOV  V28.S[0], R7
	MOVD  R7, 8(RSP)
	MOVD  $0xBF800000, R7
	VMOV  R7, V27.S[0]
	VDUP  V27.S[0], V27.S4
	CBZ   R6, lap4_done

lap4_loop4:
	CMP  $4, R6
	BLT  lap4_scalar_tail
	VLD1.P 16(R2), [V0.S4]
	VFMUL_S4(29, 0, 0)
	VLD1.P 16(R3), [V1.S4]
	VFMLA_S4(28, 1, 0)
	VLD1.P 16(R4), [V2.S4]
	VFMLA_S4(29, 2, 0)
	VLD1.P 16(R1), [V3.S4]
	VFMLA_S4(27, 3, 0)
	VLD1.P 16(R5), [V4.S4]
	VFMLA_S4(27, 4, 0)
	VFMUL_S4(31, 0, 0)
	VST1.P [V0.S4], 16(R0)
	SUB  $4, R6
	B    lap4_loop4

lap4_scalar_tail:
	CBZ  R6, lap4_done
	FMOVS (R2), F1
	FMOVS 4(RSP), F2
	FMULS F2, F1, F1
	FMOVS (R3), F0
	FMOVS 8(RSP), F2
	FMULS F2, F0, F0
	FADDS F0, F1, F0
	FMOVS (R4), F1
	FMOVS 4(RSP), F2
	FMULS F2, F1, F1
	FADDS F1, F0, F0
	FMOVS (R1), F1
	FNEGS F1, F1
	FADDS F1, F0, F0
	FMOVS (R5), F1
	FNEGS F1, F1
	FADDS F1, F0, F0
	FMOVS 0(RSP), F2
	FMULS F2, F0, F0
	FMOVS F0, (R0)
	ADD  $4, R1
	ADD  $4, R2
	ADD  $4, R3
	ADD  $4, R4
	ADD  $4, R5
	ADD  $4, R0
	SUB  $1, R6
	B    lap4_scalar_tail

lap4_done:
	RET
