// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON AXPY for bf16: y[i] = y[i] + alpha*x[i] in place.
// Widen bf16→f32, FMLA accumulate, narrow via VUZP2.

#include "textflag.h"
#include "../neon_bf16_macros.inc"

#define VFMLA_S4(m, n, d) WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))

// func AxpyBFloat16NEONAsm(y, x *uint16, alpha float32, n int)
TEXT ·AxpyBFloat16NEONAsm(SB), NOSPLIT, $0-32
	MOVD y+0(FP), R0
	MOVD x+8(FP), R1
	FMOVS alpha+16(FP), F28
	MOVD n+24(FP), R3

	VDUP V28.S[0], V28.S4
	VEOR V31.B16, V31.B16, V31.B16

axpybf16_loop16:
	CMP  $16, R3
	BLT  axpybf16_loop8
	VLD1.P 32(R0), [V0.H8, V1.H8]
	VLD1.P 32(R1), [V2.H8, V3.H8]
	BF16_BITS_TO_F32_LOW(V0.H8, V4.H8)
	BF16_BITS_TO_F32_HIGH(V0.H8, V5.H8)
	BF16_BITS_TO_F32_LOW(V1.H8, V6.H8)
	BF16_BITS_TO_F32_HIGH(V1.H8, V7.H8)
	BF16_BITS_TO_F32_LOW(V2.H8, V8.H8)
	BF16_BITS_TO_F32_HIGH(V2.H8, V9.H8)
	BF16_BITS_TO_F32_LOW(V3.H8, V10.H8)
	BF16_BITS_TO_F32_HIGH(V3.H8, V11.H8)
	VFMLA_S4(28, 8, 4)
	VFMLA_S4(28, 9, 5)
	VFMLA_S4(28, 10, 6)
	VFMLA_S4(28, 11, 7)
	F32_BITS_TO_BF16_H8(V4.H8, V5.H8, V12.H8)
	F32_BITS_TO_BF16_H8(V6.H8, V7.H8, V13.H8)
	VST1.P [V12.H8, V13.H8], 32(R0)
	SUB  $16, R3
	B    axpybf16_loop16

axpybf16_loop8:
	CMP  $8, R3
	BLT  axpybf16_scalar_tail
	VLD1.P 16(R0), [V0.H8]
	VLD1.P 16(R1), [V2.H8]
	BF16_BITS_TO_F32_LOW(V0.H8, V4.H8)
	BF16_BITS_TO_F32_HIGH(V0.H8, V5.H8)
	BF16_BITS_TO_F32_LOW(V2.H8, V8.H8)
	BF16_BITS_TO_F32_HIGH(V2.H8, V9.H8)
	VFMLA_S4(28, 8, 4)
	VFMLA_S4(28, 9, 5)
	F32_BITS_TO_BF16_H8(V4.H8, V5.H8, V12.H8)
	VST1.P [V12.H8], 16(R0)
	SUB  $8, R3
	B    axpybf16_loop8

axpybf16_scalar_tail:
	CBZ  R3, axpybf16_done

axpybf16_scalar_loop:
	MOVHU (R0), R4
	MOVHU (R1), R5
	LSL  $16, R4, R4
	LSL  $16, R5, R5
	FMOVS R4, F0
	FMOVS R5, F1
	FMULS F28, F1, F1
	FADDS F1, F0, F0
	BF16_RNE_SCALAR_F0_TO(R4)
	MOVH R4, (R0)
	ADD  $2, R0
	ADD  $2, R1
	SUB  $1, R3
	CBNZ R3, axpybf16_scalar_loop

axpybf16_done:
	RET
