// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON AXPY for float32: y[i] = alpha*x[i] + y[i] in place. The
// scalar reference is straight FMA (FMLA), so parity is bitwise.
// Processes 16 lanes per iteration with four parallel FMLAs.

#include "textflag.h"

// FMLA vector .4S: 0|1|0|01110|00|1|Rm|11001|1|Rn|Rd = 0x4E20CC00
// Semantics in ARM: FMLA Vd.4S, Vn.4S, Vm.4S → Vd += Vn * Vm.
#define VFMLA_S4(m, n, d) WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))

// func AxpyFloat32NEONAsm(y, x *float32, alpha float32, n int)
TEXT ·AxpyFloat32NEONAsm(SB), NOSPLIT, $0-32
    MOVD y+0(FP), R0
    MOVD x+8(FP), R1
    // alpha is a 4-byte float at offset 16, slot is 8 bytes wide on
    // arm64; the float sits in the low 4 bytes of that slot.
    FMOVS alpha+16(FP), F31
    MOVD n+24(FP), R2

    // Broadcast alpha into all four lanes of V31.S4.
    VDUP V31.S[0], V31.S4

axpy_loop16:
    CMP  $16, R2
    BLT  axpy_loop4
    VLD1   (R0), [V0.S4, V1.S4, V2.S4, V3.S4]   // y in place
    VLD1.P 64(R1), [V4.S4, V5.S4, V6.S4, V7.S4] // x advancing
    // V0..V3 += V31 * V4..V7
    VFMLA_S4(31, 4, 0)
    VFMLA_S4(31, 5, 1)
    VFMLA_S4(31, 6, 2)
    VFMLA_S4(31, 7, 3)
    VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)
    SUB  $16, R2
    B    axpy_loop16

axpy_loop4:
    CMP  $4, R2
    BLT  axpy_scalar_tail
    VLD1   (R0), [V0.S4]
    VLD1.P 16(R1), [V4.S4]
    VFMLA_S4(31, 4, 0)
    VST1.P [V0.S4], 16(R0)
    SUB  $4, R2
    B    axpy_loop4

axpy_scalar_tail:
    CBZ  R2, axpy_done

    // F31 still holds alpha in lane 0 (DUP preserves it).

axpy_scalar_loop:
    FMOVS (R0), F0
    FMOVS (R1), F1
    FMULS F31, F1, F1
    FADDS F1, F0, F0
    FMOVS F0, (R0)
    ADD  $4, R0
    ADD  $4, R1
    SUB  $1, R2
    CBNZ R2, axpy_scalar_loop

axpy_done:
    RET
