// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON AXPY for fp16: y[i] = y[i] + alpha*x[i]. Native .8H FMA.

#include "textflag.h"

#define VFMLA_H8(m, n, d) WORD $(0x4E400C00 | ((m) << 16) | ((n) << 5) | (d))

// func AxpyFloat16NEONAsm(y, x *uint16, alpha float32, n int)
TEXT ·AxpyFloat16NEONAsm(SB), NOSPLIT, $0-32
	MOVD y+0(FP), R0
	MOVD x+8(FP), R1
	FMOVS alpha+16(FP), F0
	MOVD n+24(FP), R3

	WORD $0x1E214000
	SUB  $16, RSP
	MOVD RSP, R7
	VMOV V0.H[0], R6
	MOVH R6, (R7)
	VLD1R (R7), [V28.H8]
	ADD  $16, RSP

axpyfp16_loop16:
	CMP  $16, R3
	BLT  axpyfp16_loop8
	VLD1.P 32(R0), [V0.H8, V1.H8]
	VLD1.P 32(R1), [V2.H8, V3.H8]
	VFMLA_H8(28, 2, 0)
	VFMLA_H8(28, 3, 1)
	VST1.P [V0.H8, V1.H8], 32(R0)
	SUB  $16, R3
	B    axpyfp16_loop16

axpyfp16_loop8:
	CMP  $8, R3
	BLT  axpyfp16_scalar_tail
	VLD1.P 16(R0), [V0.H8]
	VLD1.P 16(R1), [V2.H8]
	VFMLA_H8(28, 2, 0)
	VST1.P [V0.H8], 16(R0)
	SUB  $8, R3
	B    axpyfp16_loop8

axpyfp16_scalar_tail:
	CBZ  R3, axpyfp16_done

axpyfp16_scalar_loop:
	MOVHU (R0), R4
	MOVHU (R1), R5
	VMOV  R4, V0.H[0]
	VMOV  R5, V2.H[0]
	VFMLA_H8(28, 2, 0)
	VMOV  V0.H[0], R4
	MOVH  R4, (R0)
	ADD  $2, R0
	ADD  $2, R1
	SUB  $1, R3
	CBNZ R3, axpyfp16_scalar_loop

axpyfp16_done:
	RET
