// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON AXPY for fp16: y[i] = y[i] + alpha*x[i] in place.

#include "textflag.h"

#define VFMLA_S4(m, n, d) WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFCVTL_4S(n, d)   WORD $(0x0E217800 | ((n) << 5) | (d))
#define VFCVTL2_4S(n, d)  WORD $(0x4E217800 | ((n) << 5) | (d))
#define VFCVTN_4H(n, d)   WORD $(0x0E216800 | ((n) << 5) | (d))
#define VFCVTN2_8H(n, d)  WORD $(0x4E216800 | ((n) << 5) | (d))

// func AxpyFloat16NEONAsm(y, x *uint16, alpha float32, n int)
TEXT ·AxpyFloat16NEONAsm(SB), NOSPLIT, $0-32
	MOVD y+0(FP), R0
	MOVD x+8(FP), R1
	FMOVS alpha+16(FP), F28
	MOVD n+24(FP), R3

	VDUP V28.S[0], V28.S4

axpyfp16_loop16:
	CMP  $16, R3
	BLT  axpyfp16_loop8
	VLD1.P 32(R0), [V0.H8, V1.H8]
	VLD1.P 32(R1), [V2.H8, V3.H8]
	VFCVTL_4S(0, 4)
	VFCVTL2_4S(0, 5)
	VFCVTL_4S(1, 6)
	VFCVTL2_4S(1, 7)
	VFCVTL_4S(2, 8)
	VFCVTL2_4S(2, 9)
	VFCVTL_4S(3, 10)
	VFCVTL2_4S(3, 11)
	VFMLA_S4(28, 8, 4)
	VFMLA_S4(28, 9, 5)
	VFMLA_S4(28, 10, 6)
	VFMLA_S4(28, 11, 7)
	VFCVTN_4H(4, 12)
	VFCVTN2_8H(5, 12)
	VFCVTN_4H(6, 13)
	VFCVTN2_8H(7, 13)
	VST1.P [V12.H8, V13.H8], 32(R0)
	SUB  $16, R3
	B    axpyfp16_loop16

axpyfp16_loop8:
	CMP  $8, R3
	BLT  axpyfp16_scalar_tail
	VLD1.P 16(R0), [V0.H8]
	VLD1.P 16(R1), [V2.H8]
	VFCVTL_4S(0, 4)
	VFCVTL2_4S(0, 5)
	VFCVTL_4S(2, 8)
	VFCVTL2_4S(2, 9)
	VFMLA_S4(28, 8, 4)
	VFMLA_S4(28, 9, 5)
	VFCVTN_4H(4, 12)
	VFCVTN2_8H(5, 12)
	VST1.P [V12.H8], 16(R0)
	SUB  $8, R3
	B    axpyfp16_loop8

axpyfp16_scalar_tail:
	CBZ  R3, axpyfp16_done

axpyfp16_scalar_loop:
	MOVHU (R0), R4
	MOVHU (R1), R5
	VMOV  R4, V0.H[0]
	VMOV  R5, V2.H[0]
	VFCVTL_4S(0, 4)
	VFCVTL_4S(2, 8)
	VMOV  V4.S[0], R6
	VMOV  V8.S[0], R7
	FMOVS R6, F0
	FMOVS R7, F1
	FMULS F28, F1, F1
	FADDS F1, F0, F0
	FMOVS F0, R6
	VMOV  R6, V4.S[0]
	VFCVTN_4H(4, 12)
	VMOV  V12.H[0], R6
	MOVH  R6, (R0)
	ADD  $2, R0
	ADD  $2, R1
	SUB  $1, R3
	CBNZ R3, axpyfp16_scalar_loop

axpyfp16_done:
	RET
