// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON elementwise bf16 vector ops: add, sub, mul, div. Each kernel
// loads bf16 inputs, widens to f32 via VZIP{1,2} with a zero
// halfword vector, performs the operation in f32, and narrows the
// f32 result back to bf16 via VUZP2 (picking the upper 16 bits of
// each f32 lane = the bf16 representation under truncation rounding).
//
// This matches the scalar bf16 reference:
//   sum := left[i].Float32() + right[i].Float32()
//   out[i] = NewBfloat16FromFloat32(sum)
// where Float32() = uint32(bf16) << 16 (bit shuffle) and
// NewBfloat16FromFloat32 = uint16(bits >> 16) (bit shuffle). The
// f32 arithmetic in between is identical, so the NEON path is
// bit-exact against the scalar reference.

#include "textflag.h"

// FADD vector .4S: 0x4E20D400 base
#define VFADD_S4(m, n, d) WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
// FSUB vector .4S: 0x4EA0D400 base
#define VFSUB_S4(m, n, d) WORD $(0x4EA0D400 | ((m) << 16) | ((n) << 5) | (d))
// FMUL vector .4S: 0x6E20DC00 base
#define VFMUL_S4(m, n, d) WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))
// FDIV vector .4S: 0x6E20FC00 base
#define VFDIV_S4(m, n, d) WORD $(0x6E20FC00 | ((m) << 16) | ((n) << 5) | (d))
// FCMGT vector .4S: 0x6EA0E400 base
#define VFCMGT_S4(m, n, d) WORD $(0x6EA0E400 | ((m) << 16) | ((n) << 5) | (d))
// BSL .16B: Vd = (Vd & Vn) | (~Vd & Vm); base 0x6E601C00
#define VBSL_B16(m, n, d) WORD $(0x6E601C00 | ((m) << 16) | ((n) << 5) | (d))
// ORR .16B (vector move): base 0x4EA01C00 with Rm=Rn
#define VMOV_B16(src, dst) WORD $(0x4EA01C00 | ((src) << 16) | ((src) << 5) | (dst))

// Widen 8 bf16 lanes (one .H8 vector) into 2 f32 vectors using V31=0.
// VZIP1 src, zero, dst → dst[2k]=zero[k]=0, dst[2k+1]=src[k]
// reinterpreting dst as .S4 yields [src[k] << 16] = widened bf16 ✓
#define WIDEN_H8_TO_S4_LOW(src_h8, dst_h8)  VZIP1 src_h8, V31.H8, dst_h8
#define WIDEN_H8_TO_S4_HIGH(src_h8, dst_h8) VZIP2 src_h8, V31.H8, dst_h8

// Narrow 2 f32 vectors (.S4 each, 8 lanes total) into 1 bf16 .H8.
// VUZP2 picks the odd-indexed halfwords of the source pair, which in
// little-endian is the upper 16 bits of each .S lane = bf16 bits.
// Go reverses source order, so to get s0's odd lanes first then
// s1's we write VUZP2 s1, s0, dst.
#define NARROW_S4_TO_H8(s0_h8, s1_h8, dst_h8) VUZP2 s1_h8, s0_h8, dst_h8

// ADD scalar tail: F0 = F0 + F1
#define ADD_SCALAR_S FADDS F1, F0, F0
// SUB scalar tail: F0 = F0 - F1
#define SUB_SCALAR_S FSUBS F1, F0, F0
// MUL scalar tail: F0 = F0 * F1
#define MUL_SCALAR_S FMULS F1, F0, F0
// DIV scalar tail: F0 = F0 / F1
#define DIV_SCALAR_S FDIVS F1, F0, F0

#define BF16_BINARY_TEMPLATE(op_4x4, op_2x2, op_scalar)             \
    MOVD dst+0(FP), R0                                              \
    MOVD left+8(FP), R1                                             \
    MOVD right+16(FP), R2                                           \
    MOVD n+24(FP), R3                                               \
                                                                    \
    VEOR V31.B16, V31.B16, V31.B16                                  \
                                                                    \
loop16:                                                             \
    CMP  $16, R3                                                    \
    BLT  loop8                                                      \
    VLD1.P 32(R1), [V0.H8, V1.H8]                                   \
    VLD1.P 32(R2), [V2.H8, V3.H8]                                   \
    WIDEN_H8_TO_S4_LOW(V0.H8, V4.H8)                                \
    WIDEN_H8_TO_S4_HIGH(V0.H8, V5.H8)                               \
    WIDEN_H8_TO_S4_LOW(V1.H8, V6.H8)                                \
    WIDEN_H8_TO_S4_HIGH(V1.H8, V7.H8)                               \
    WIDEN_H8_TO_S4_LOW(V2.H8, V8.H8)                                \
    WIDEN_H8_TO_S4_HIGH(V2.H8, V9.H8)                               \
    WIDEN_H8_TO_S4_LOW(V3.H8, V10.H8)                               \
    WIDEN_H8_TO_S4_HIGH(V3.H8, V11.H8)                              \
    op_4x4                                                          \
    NARROW_S4_TO_H8(V4.H8, V5.H8, V12.H8)                           \
    NARROW_S4_TO_H8(V6.H8, V7.H8, V13.H8)                           \
    VST1.P [V12.H8, V13.H8], 32(R0)                                 \
    SUB  $16, R3                                                    \
    B    loop16                                                     \
                                                                    \
loop8:                                                              \
    CMP  $8, R3                                                     \
    BLT  scalar_tail                                                \
    VLD1.P 16(R1), [V0.H8]                                          \
    VLD1.P 16(R2), [V2.H8]                                          \
    WIDEN_H8_TO_S4_LOW(V0.H8, V4.H8)                                \
    WIDEN_H8_TO_S4_HIGH(V0.H8, V5.H8)                               \
    WIDEN_H8_TO_S4_LOW(V2.H8, V8.H8)                                \
    WIDEN_H8_TO_S4_HIGH(V2.H8, V9.H8)                               \
    op_2x2                                                          \
    NARROW_S4_TO_H8(V4.H8, V5.H8, V12.H8)                           \
    VST1.P [V12.H8], 16(R0)                                         \
    SUB  $8, R3                                                     \
    B    loop8                                                      \
                                                                    \
scalar_tail:                                                        \
    CBZ  R3, done                                                   \
                                                                    \
scalar_loop:                                                        \
    MOVHU (R1), R4                                                  \
    MOVHU (R2), R5                                                  \
    LSL  $16, R4, R4                                                \
    LSL  $16, R5, R5                                                \
    FMOVS R4, F0                                                    \
    FMOVS R5, F1                                                    \
    op_scalar                                                       \
    FMOVS F0, R4                                                    \
    LSR  $16, R4, R4                                                \
    MOVH R4, (R0)                                                   \
    ADD  $2, R1                                                     \
    ADD  $2, R2                                                     \
    ADD  $2, R0                                                     \
    SUB  $1, R3                                                     \
    CBNZ R3, scalar_loop                                            \
                                                                    \
done:                                                               \
    RET

#define ADD_4X4 \
    VFADD_S4(8, 4, 4)   \
    VFADD_S4(9, 5, 5)   \
    VFADD_S4(10, 6, 6)  \
    VFADD_S4(11, 7, 7)

#define ADD_2X2 \
    VFADD_S4(8, 4, 4)   \
    VFADD_S4(9, 5, 5)

#define SUB_4X4 \
    VFSUB_S4(8, 4, 4)   \
    VFSUB_S4(9, 5, 5)   \
    VFSUB_S4(10, 6, 6)  \
    VFSUB_S4(11, 7, 7)

#define SUB_2X2 \
    VFSUB_S4(8, 4, 4)   \
    VFSUB_S4(9, 5, 5)

#define MUL_4X4 \
    VFMUL_S4(8, 4, 4)   \
    VFMUL_S4(9, 5, 5)   \
    VFMUL_S4(10, 6, 6)  \
    VFMUL_S4(11, 7, 7)

#define MUL_2X2 \
    VFMUL_S4(8, 4, 4)   \
    VFMUL_S4(9, 5, 5)

#define DIV_4X4 \
    VFDIV_S4(8, 4, 4)   \
    VFDIV_S4(9, 5, 5)   \
    VFDIV_S4(10, 6, 6)  \
    VFDIV_S4(11, 7, 7)

#define DIV_2X2 \
    VFDIV_S4(8, 4, 4)   \
    VFDIV_S4(9, 5, 5)

// MAX: result = if (a > b) a else b. Uses FCMGT into scratch V12-V15
// then BSL with scratch as destination, then VMOV result back to
// V4-V7 for the narrow step. Matches Go's scalar `if a > b { return a
// } return b` semantics (no NaN propagation on the b operand) because
// FCMGT returns false on any NaN, so BSL falls through to b.
#define MAX_4X4 \
    VFCMGT_S4(8, 4, 12)  \
    VFCMGT_S4(9, 5, 13)  \
    VFCMGT_S4(10, 6, 14) \
    VFCMGT_S4(11, 7, 15) \
    VBSL_B16(8, 4, 12)   \
    VBSL_B16(9, 5, 13)   \
    VBSL_B16(10, 6, 14)  \
    VBSL_B16(11, 7, 15)  \
    VMOV_B16(12, 4)      \
    VMOV_B16(13, 5)      \
    VMOV_B16(14, 6)      \
    VMOV_B16(15, 7)

#define MAX_2X2 \
    VFCMGT_S4(8, 4, 12)  \
    VFCMGT_S4(9, 5, 13)  \
    VBSL_B16(8, 4, 12)   \
    VBSL_B16(9, 5, 13)   \
    VMOV_B16(12, 4)      \
    VMOV_B16(13, 5)

// MIN: result = if (a < b) a else b ≡ if (b > a) a else b.
// FCMGT swaps Rn/Rm; rest mirrors MAX.
#define MIN_4X4 \
    VFCMGT_S4(4, 8, 12)  \
    VFCMGT_S4(5, 9, 13)  \
    VFCMGT_S4(6, 10, 14) \
    VFCMGT_S4(7, 11, 15) \
    VBSL_B16(8, 4, 12)   \
    VBSL_B16(9, 5, 13)   \
    VBSL_B16(10, 6, 14)  \
    VBSL_B16(11, 7, 15)  \
    VMOV_B16(12, 4)      \
    VMOV_B16(13, 5)      \
    VMOV_B16(14, 6)      \
    VMOV_B16(15, 7)

#define MIN_2X2 \
    VFCMGT_S4(4, 8, 12)  \
    VFCMGT_S4(5, 9, 13)  \
    VBSL_B16(8, 4, 12)   \
    VBSL_B16(9, 5, 13)   \
    VMOV_B16(12, 4)      \
    VMOV_B16(13, 5)

#define MAX_SCALAR_S \
    FCMPS F1, F0       \
    FCSELS GT, F0, F1, F0

#define MIN_SCALAR_S \
    FCMPS F1, F0       \
    FCSELS LT, F0, F1, F0

// func AddBFloat16NEONAsm(dst, left, right *uint16, n int)
TEXT ·AddBFloat16NEONAsm(SB), NOSPLIT, $0-32
    BF16_BINARY_TEMPLATE(ADD_4X4, ADD_2X2, ADD_SCALAR_S)

// func SubBFloat16NEONAsm(dst, left, right *uint16, n int)
TEXT ·SubBFloat16NEONAsm(SB), NOSPLIT, $0-32
    BF16_BINARY_TEMPLATE(SUB_4X4, SUB_2X2, SUB_SCALAR_S)

// func MulBFloat16NEONAsm(dst, left, right *uint16, n int)
TEXT ·MulBFloat16NEONAsm(SB), NOSPLIT, $0-32
    BF16_BINARY_TEMPLATE(MUL_4X4, MUL_2X2, MUL_SCALAR_S)

// func DivBFloat16NEONAsm(dst, left, right *uint16, n int)
TEXT ·DivBFloat16NEONAsm(SB), NOSPLIT, $0-32
    BF16_BINARY_TEMPLATE(DIV_4X4, DIV_2X2, DIV_SCALAR_S)

// func MaxBFloat16NEONAsm(dst, left, right *uint16, n int)
TEXT ·MaxBFloat16NEONAsm(SB), NOSPLIT, $0-32
    BF16_BINARY_TEMPLATE(MAX_4X4, MAX_2X2, MAX_SCALAR_S)

// func MinBFloat16NEONAsm(dst, left, right *uint16, n int)
TEXT ·MinBFloat16NEONAsm(SB), NOSPLIT, $0-32
    BF16_BINARY_TEMPLATE(MIN_4X4, MIN_2X2, MIN_SCALAR_S)
