// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON elementwise bf16 unary ops: abs, neg, sqrt. Each kernel loads
// bf16, widens to f32, applies the unary op, narrows back to bf16.
// Matches the scalar reference, which is also widen→op→narrow.

#include "textflag.h"

// FABS .4S: 0x4EA0F800 base
#define VFABS_S4(n, d)  WORD $(0x4EA0F800 | ((n) << 5) | (d))
// FNEG .4S: 0x6EA0F800 base
#define VFNEG_S4(n, d)  WORD $(0x6EA0F800 | ((n) << 5) | (d))
// FSQRT .4S: 0x6EA1F800 base
#define VFSQRT_S4(n, d) WORD $(0x6EA1F800 | ((n) << 5) | (d))
// FCMGT .4S: 0x6EA0E400 base
#define VFCMGT_S4(m, n, d) WORD $(0x6EA0E400 | ((m) << 16) | ((n) << 5) | (d))
// BSL .16B: 0x6E601C00 base
#define VBSL_B16(m, n, d) WORD $(0x6E601C00 | ((m) << 16) | ((n) << 5) | (d))

#define WIDEN_H8_TO_S4_LOW(src_h8, dst_h8)  VZIP1 src_h8, V31.H8, dst_h8
#define WIDEN_H8_TO_S4_HIGH(src_h8, dst_h8) VZIP2 src_h8, V31.H8, dst_h8
#define NARROW_S4_TO_H8(s0_h8, s1_h8, dst_h8) VUZP2 s1_h8, s0_h8, dst_h8

#define BF16_UNARY_TEMPLATE(op_4x4, op_2x2, op_scalar)              \
    MOVD dst+0(FP), R0                                              \
    MOVD src+8(FP), R1                                              \
    MOVD n+16(FP), R2                                               \
                                                                    \
    VEOR V31.B16, V31.B16, V31.B16                                  \
                                                                    \
loop16:                                                             \
    CMP  $16, R2                                                    \
    BLT  loop8                                                      \
    VLD1.P 32(R1), [V0.H8, V1.H8]                                   \
    WIDEN_H8_TO_S4_LOW(V0.H8, V4.H8)                                \
    WIDEN_H8_TO_S4_HIGH(V0.H8, V5.H8)                               \
    WIDEN_H8_TO_S4_LOW(V1.H8, V6.H8)                                \
    WIDEN_H8_TO_S4_HIGH(V1.H8, V7.H8)                               \
    op_4x4                                                          \
    NARROW_S4_TO_H8(V8.H8, V9.H8, V12.H8)                           \
    NARROW_S4_TO_H8(V10.H8, V11.H8, V13.H8)                         \
    VST1.P [V12.H8, V13.H8], 32(R0)                                 \
    SUB  $16, R2                                                    \
    B    loop16                                                     \
                                                                    \
loop8:                                                              \
    CMP  $8, R2                                                     \
    BLT  scalar_tail                                                \
    VLD1.P 16(R1), [V0.H8]                                          \
    WIDEN_H8_TO_S4_LOW(V0.H8, V4.H8)                                \
    WIDEN_H8_TO_S4_HIGH(V0.H8, V5.H8)                               \
    op_2x2                                                          \
    NARROW_S4_TO_H8(V8.H8, V9.H8, V12.H8)                           \
    VST1.P [V12.H8], 16(R0)                                         \
    SUB  $8, R2                                                     \
    B    loop8                                                      \
                                                                    \
scalar_tail:                                                        \
    CBZ  R2, done                                                   \
                                                                    \
scalar_loop:                                                        \
    MOVHU (R1), R4                                                  \
    LSL  $16, R4, R4                                                \
    FMOVS R4, F0                                                    \
    op_scalar                                                       \
    FMOVS F0, R4                                                    \
    LSR  $16, R4, R4                                                \
    MOVH R4, (R0)                                                   \
    ADD  $2, R1                                                     \
    ADD  $2, R0                                                     \
    SUB  $1, R2                                                     \
    CBNZ R2, scalar_loop                                            \
                                                                    \
done:                                                               \
    RET

// abs/neg/sqrt write to V8-V11 so the narrow step picks up the result.
#define ABS_4X4 \
    VFABS_S4(4, 8)   \
    VFABS_S4(5, 9)   \
    VFABS_S4(6, 10)  \
    VFABS_S4(7, 11)

#define ABS_2X2 \
    VFABS_S4(4, 8)   \
    VFABS_S4(5, 9)

#define ABS_SCALAR_S FABSS F0, F0

#define NEG_4X4 \
    VFNEG_S4(4, 8)   \
    VFNEG_S4(5, 9)   \
    VFNEG_S4(6, 10)  \
    VFNEG_S4(7, 11)

#define NEG_2X2 \
    VFNEG_S4(4, 8)   \
    VFNEG_S4(5, 9)

#define NEG_SCALAR_S FNEGS F0, F0

#define SQRT_4X4 \
    VFSQRT_S4(4, 8)   \
    VFSQRT_S4(5, 9)   \
    VFSQRT_S4(6, 10)  \
    VFSQRT_S4(7, 11)

#define SQRT_2X2 \
    VFSQRT_S4(4, 8)   \
    VFSQRT_S4(5, 9)

#define SQRT_SCALAR_S FSQRTS F0, F0

// ReLU = if (x > 0) x else 0. FCMGT(x, 0) into V8-V11, BSL with V8-V11
// destination picks x or 0 per-lane.
#define RELU_4X4 \
    VFCMGT_S4(31, 4, 8)  \
    VFCMGT_S4(31, 5, 9)  \
    VFCMGT_S4(31, 6, 10) \
    VFCMGT_S4(31, 7, 11) \
    VBSL_B16(31, 4, 8)   \
    VBSL_B16(31, 5, 9)   \
    VBSL_B16(31, 6, 10)  \
    VBSL_B16(31, 7, 11)

#define RELU_2X2 \
    VFCMGT_S4(31, 4, 8)  \
    VFCMGT_S4(31, 5, 9)  \
    VBSL_B16(31, 4, 8)   \
    VBSL_B16(31, 5, 9)

#define RELU_SCALAR_S \
    FMOVS ZR, F1       \
    FCMPS F1, F0       \
    FCSELS GT, F0, F1, F0

// func AbsBFloat16NEONAsm(dst, src *uint16, n int)
TEXT ·AbsBFloat16NEONAsm(SB), NOSPLIT, $0-24
    BF16_UNARY_TEMPLATE(ABS_4X4, ABS_2X2, ABS_SCALAR_S)

// func NegBFloat16NEONAsm(dst, src *uint16, n int)
TEXT ·NegBFloat16NEONAsm(SB), NOSPLIT, $0-24
    BF16_UNARY_TEMPLATE(NEG_4X4, NEG_2X2, NEG_SCALAR_S)

// func SqrtBFloat16NEONAsm(dst, src *uint16, n int)
TEXT ·SqrtBFloat16NEONAsm(SB), NOSPLIT, $0-24
    BF16_UNARY_TEMPLATE(SQRT_4X4, SQRT_2X2, SQRT_SCALAR_S)

// func ReluBFloat16NEONAsm(dst, src *uint16, n int)
TEXT ·ReluBFloat16NEONAsm(SB), NOSPLIT, $0-24
    BF16_UNARY_TEMPLATE(RELU_4X4, RELU_2X2, RELU_SCALAR_S)
