// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON elementwise float32 vector ops: add, sub, mul, div, max, min.
// Each op processes 16 lanes (64 bytes) per inner iteration via four
// 128-bit registers, with a 4-lane secondary loop and scalar tail.

#include "textflag.h"

#define VFADD_S4(m, n, d) WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFSUB_S4(m, n, d) WORD $(0x4EA0D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_S4(m, n, d) WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFDIV_S4(m, n, d) WORD $(0x6E20FC00 | ((m) << 16) | ((n) << 5) | (d))
// FCMGT (vector, register), .4S: 0|1|1|01110|10|1|Rm|11100|1|Rn|Rd = 0x6EA0E400
#define VFCMGT_S4(m, n, d) WORD $(0x6EA0E400 | ((m) << 16) | ((n) << 5) | (d))
// BSL Vd.16B, Vn.16B, Vm.16B: 0|1|1|01110|01|1|Rm|00011|1|Rn|Rd = 0x6E601C00
// Semantics: per-bit, where original Vd=1 take from Vn, where Vd=0 take from Vm.
#define VBSL_B16(m, n, d) WORD $(0x6E601C00 | ((m) << 16) | ((n) << 5) | (d))
// ORR Vd.16B, Vn.16B, Vm.16B with m=n acts as vector-register move:
// 0|1|0|01110|10|1|Rm|00011|1|Rn|Rd = 0x4EA01C00
#define VMOV_B16(src, dst) WORD $(0x4EA01C00 | ((src) << 16) | ((src) << 5) | (dst))

#define ELEMENTWISE_TEMPLATE(op_4x4, op_4, op_scalar)              \
    MOVD dst+0(FP), R0                                              \
    MOVD left+8(FP), R1                                             \
    MOVD right+16(FP), R2                                           \
    MOVD n+24(FP), R3                                               \
                                                                    \
loop16:                                                             \
    CMP  $16, R3                                                    \
    BLT  loop4                                                      \
    VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]                     \
    VLD1.P 64(R2), [V4.S4, V5.S4, V6.S4, V7.S4]                     \
    op_4x4                                                          \
    VST1.P [V0.S4, V1.S4, V2.S4, V3.S4], 64(R0)                     \
    SUB  $16, R3                                                    \
    B    loop16                                                     \
                                                                    \
loop4:                                                              \
    CMP  $4, R3                                                     \
    BLT  scalar_tail                                                \
    VLD1.P 16(R1), [V0.S4]                                          \
    VLD1.P 16(R2), [V4.S4]                                          \
    op_4                                                            \
    VST1.P [V0.S4], 16(R0)                                          \
    SUB  $4, R3                                                     \
    B    loop4                                                      \
                                                                    \
scalar_tail:                                                        \
    CBZ  R3, done                                                   \
                                                                    \
scalar_loop:                                                        \
    FMOVS (R1), F0                                                  \
    FMOVS (R2), F1                                                  \
    op_scalar                                                       \
    FMOVS F0, (R0)                                                  \
    ADD  $4, R1                                                     \
    ADD  $4, R2                                                     \
    ADD  $4, R0                                                     \
    SUB  $1, R3                                                     \
    CBNZ R3, scalar_loop                                            \
                                                                    \
done:                                                               \
    RET

#define ADD_4X4                                                     \
    VFADD_S4(4, 0, 0)                                               \
    VFADD_S4(5, 1, 1)                                               \
    VFADD_S4(6, 2, 2)                                               \
    VFADD_S4(7, 3, 3)

#define ADD_4                                                       \
    VFADD_S4(4, 0, 0)

#define ADD_SCALAR                                                  \
    FADDS F1, F0, F0

#define SUB_4X4                                                     \
    VFSUB_S4(4, 0, 0)                                               \
    VFSUB_S4(5, 1, 1)                                               \
    VFSUB_S4(6, 2, 2)                                               \
    VFSUB_S4(7, 3, 3)

#define SUB_4                                                       \
    VFSUB_S4(4, 0, 0)

#define SUB_SCALAR                                                  \
    FSUBS F1, F0, F0

#define MUL_4X4                                                     \
    VFMUL_S4(4, 0, 0)                                               \
    VFMUL_S4(5, 1, 1)                                               \
    VFMUL_S4(6, 2, 2)                                               \
    VFMUL_S4(7, 3, 3)

#define MUL_4                                                       \
    VFMUL_S4(4, 0, 0)

#define MUL_SCALAR                                                  \
    FMULS F1, F0, F0

#define DIV_4X4                                                     \
    VFDIV_S4(4, 0, 0)                                               \
    VFDIV_S4(5, 1, 1)                                               \
    VFDIV_S4(6, 2, 2)                                               \
    VFDIV_S4(7, 3, 3)

#define DIV_4                                                       \
    VFDIV_S4(4, 0, 0)

#define DIV_SCALAR                                                  \
    FDIVS F1, F0, F0

// MAX = if (a > b) a else b
// FCMGT writes a per-lane mask into scratch (V8-V11), BSL with that
// scratch as destination picks a-or-b per bit (mask=1 → a, mask=0 → b),
// then ORR moves the result back into V0-V3 for the store.
//
// Go's scalar `if a > b { return a } return b` does NOT propagate NaN
// on the b operand; FCMGT returns false on any NaN, so BSL falls
// through to b, matching the scalar behavior bit-for-bit.
#define MAX_4X4                                                     \
    VFCMGT_S4(4, 0, 8)                                              \
    VFCMGT_S4(5, 1, 9)                                              \
    VFCMGT_S4(6, 2, 10)                                             \
    VFCMGT_S4(7, 3, 11)                                             \
    VBSL_B16(4, 0, 8)                                               \
    VBSL_B16(5, 1, 9)                                               \
    VBSL_B16(6, 2, 10)                                              \
    VBSL_B16(7, 3, 11)                                              \
    VMOV_B16(8, 0)                                                  \
    VMOV_B16(9, 1)                                                  \
    VMOV_B16(10, 2)                                                 \
    VMOV_B16(11, 3)

#define MAX_4                                                       \
    VFCMGT_S4(4, 0, 8)                                              \
    VBSL_B16(4, 0, 8)                                               \
    VMOV_B16(8, 0)

#define MAX_SCALAR                                                  \
    FCMPS F1, F0                                                    \
    FCSELS GT, F0, F1, F0

// MIN = if (a < b) a else b.  a < b is FCMGT(b, a), so swap Rn/Rm in
// the comparison; everything else mirrors MAX.
#define MIN_4X4                                                     \
    VFCMGT_S4(0, 4, 8)                                              \
    VFCMGT_S4(1, 5, 9)                                              \
    VFCMGT_S4(2, 6, 10)                                             \
    VFCMGT_S4(3, 7, 11)                                             \
    VBSL_B16(4, 0, 8)                                               \
    VBSL_B16(5, 1, 9)                                               \
    VBSL_B16(6, 2, 10)                                              \
    VBSL_B16(7, 3, 11)                                              \
    VMOV_B16(8, 0)                                                  \
    VMOV_B16(9, 1)                                                  \
    VMOV_B16(10, 2)                                                 \
    VMOV_B16(11, 3)

#define MIN_4                                                       \
    VFCMGT_S4(0, 4, 8)                                              \
    VBSL_B16(4, 0, 8)                                               \
    VMOV_B16(8, 0)

#define MIN_SCALAR                                                  \
    FCMPS F1, F0                                                    \
    FCSELS LT, F0, F1, F0

// func AddFloat32NEONAsm(dst, left, right *float32, n int)
TEXT ·AddFloat32NEONAsm(SB), NOSPLIT, $0-32
    ELEMENTWISE_TEMPLATE(ADD_4X4, ADD_4, ADD_SCALAR)

// func SubFloat32NEONAsm(dst, left, right *float32, n int)
TEXT ·SubFloat32NEONAsm(SB), NOSPLIT, $0-32
    ELEMENTWISE_TEMPLATE(SUB_4X4, SUB_4, SUB_SCALAR)

// func MulFloat32NEONAsm(dst, left, right *float32, n int)
TEXT ·MulFloat32NEONAsm(SB), NOSPLIT, $0-32
    ELEMENTWISE_TEMPLATE(MUL_4X4, MUL_4, MUL_SCALAR)

// func DivFloat32NEONAsm(dst, left, right *float32, n int)
TEXT ·DivFloat32NEONAsm(SB), NOSPLIT, $0-32
    ELEMENTWISE_TEMPLATE(DIV_4X4, DIV_4, DIV_SCALAR)

// func MaxFloat32NEONAsm(dst, left, right *float32, n int)
TEXT ·MaxFloat32NEONAsm(SB), NOSPLIT, $0-32
    ELEMENTWISE_TEMPLATE(MAX_4X4, MAX_4, MAX_SCALAR)

// func MinFloat32NEONAsm(dst, left, right *float32, n int)
TEXT ·MinFloat32NEONAsm(SB), NOSPLIT, $0-32
    ELEMENTWISE_TEMPLATE(MIN_4X4, MIN_4, MIN_SCALAR)
