// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON float64 elementwise add. Processes 2 lanes per inner iteration
// via FADD .2D, with a scalar tail.

#include "textflag.h"

#define VFADD_D2(m, n, d) WORD $(0x4E60D400 | ((m) << 16) | ((n) << 5) | (d))

// func AddFloat64NEONAsm(dst, left, right *float64, n int)
TEXT ·AddFloat64NEONAsm(SB), NOSPLIT, $0-32
    MOVD dst+0(FP), R0
    MOVD left+8(FP), R1
    MOVD right+16(FP), R2
    MOVD n+24(FP), R3

add_loop2:
    CMP  $2, R3
    BLT  add_scalar_tail
    VLD1.P 16(R1), [V0.D2]
    VLD1.P 16(R2), [V1.D2]
    VFADD_D2(1, 0, 0)
    VST1.P [V0.D2], 16(R0)
    SUB  $2, R3
    B    add_loop2

add_scalar_tail:
    CBZ  R3, add_done

add_scalar_loop:
    FMOVD (R1), F0
    FMOVD (R2), F1
    FADDD F1, F0, F0
    FMOVD F0, (R0)
    ADD  $8, R1
    ADD  $8, R2
    ADD  $8, R0
    SUB  $1, R3
    CBNZ R3, add_scalar_loop

add_done:
    RET
