// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON elementwise fp16 vector ops: add, sub, mul, div, max, min.
// Native .8H arithmetic — no FCVTL/FCVTN widen/narrow.

#include "textflag.h"

#define VFADD_H8(m, n, d)  WORD $(0x4E401400 | ((m) << 16) | ((n) << 5) | (d))
#define VFSUB_H8(m, n, d)  WORD $(0x4EC01400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_H8(m, n, d)  WORD $(0x6E401C00 | ((m) << 16) | ((n) << 5) | (d))
#define VFDIV_H8(m, n, d)  WORD $(0x6E403C00 | ((m) << 16) | ((n) << 5) | (d))
#define VFCMGT_H8(m, n, d) WORD $(0x6EC02400 | ((m) << 16) | ((n) << 5) | (d))
#define VBSL_B16(m, n, d)  WORD $(0x6E601C00 | ((m) << 16) | ((n) << 5) | (d))
#define VMOV_B16(src, dst) WORD $(0x4EA01C00 | ((src) << 16) | ((src) << 5) | (dst))

#define FP16_BINARY_TEMPLATE(op_2x8, op_1x8, op_scalar)             \
	MOVD dst+0(FP), R0                                              \
	MOVD left+8(FP), R1                                             \
	MOVD right+16(FP), R2                                           \
	MOVD n+24(FP), R3                                               \
                                                                    \
loop16:                                                             \
	CMP  $16, R3                                                    \
	BLT  loop8                                                      \
	VLD1.P 32(R1), [V0.H8, V1.H8]                                   \
	VLD1.P 32(R2), [V2.H8, V3.H8]                                   \
	op_2x8                                                          \
	VST1.P [V16.H8, V17.H8], 32(R0)                                 \
	SUB  $16, R3                                                    \
	B    loop16                                                     \
                                                                    \
loop8:                                                              \
	CMP  $8, R3                                                     \
	BLT  scalar_tail                                                \
	VLD1.P 16(R1), [V0.H8]                                          \
	VLD1.P 16(R2), [V2.H8]                                          \
	op_1x8                                                          \
	VST1.P [V16.H8], 16(R0)                                         \
	SUB  $8, R3                                                     \
	B    loop8                                                      \
                                                                    \
scalar_tail:                                                        \
	CBZ  R3, done                                                   \
                                                                    \
scalar_loop:                                                        \
	MOVHU (R1), R4                                                  \
	MOVHU (R2), R5                                                  \
	VMOV R4, V0.H[0]                                                \
	VMOV R5, V2.H[0]                                                \
	op_scalar                                                       \
	VMOV V16.H[0], R6                                               \
	MOVH R6, (R0)                                                   \
	ADD  $2, R1                                                     \
	ADD  $2, R2                                                     \
	ADD  $2, R0                                                     \
	SUB  $1, R3                                                     \
	CBNZ R3, scalar_loop                                            \
                                                                    \
done:                                                               \
	RET

#define ADD_2X8 \
	VFADD_H8(2, 0, 16) \
	VFADD_H8(3, 1, 17)

#define ADD_1X8 \
	VFADD_H8(2, 0, 16)

#define ADD_SCALAR \
	VFADD_H8(2, 0, 16)

#define SUB_2X8 \
	VFSUB_H8(2, 0, 16) \
	VFSUB_H8(3, 1, 17)

#define SUB_1X8 \
	VFSUB_H8(2, 0, 16)

#define SUB_SCALAR \
	VFSUB_H8(2, 0, 16)

#define MUL_2X8 \
	VFMUL_H8(2, 0, 16) \
	VFMUL_H8(3, 1, 17)

#define MUL_1X8 \
	VFMUL_H8(2, 0, 16)

#define MUL_SCALAR \
	VFMUL_H8(2, 0, 16)

#define DIV_2X8 \
	VFDIV_H8(2, 0, 16) \
	VFDIV_H8(3, 1, 17)

#define DIV_1X8 \
	VFDIV_H8(2, 0, 16)

#define DIV_SCALAR \
	VFDIV_H8(2, 0, 16)

#define MAX_2X8 \
	VFCMGT_H8(2, 0, 28) \
	VFCMGT_H8(3, 1, 29) \
	VBSL_B16(2, 0, 28) \
	VBSL_B16(3, 1, 29) \
	VMOV_B16(28, 16) \
	VMOV_B16(29, 17)

#define MAX_1X8 \
	VFCMGT_H8(2, 0, 28) \
	VBSL_B16(2, 0, 28) \
	VMOV_B16(28, 16)

#define MAX_SCALAR \
	VFCMGT_H8(2, 0, 28) \
	VBSL_B16(2, 0, 28) \
	VMOV_B16(28, 16)

#define MIN_2X8 \
	VFCMGT_H8(0, 2, 28) \
	VFCMGT_H8(1, 3, 29) \
	VBSL_B16(2, 0, 28) \
	VBSL_B16(3, 1, 29) \
	VMOV_B16(28, 16) \
	VMOV_B16(29, 17)

#define MIN_1X8 \
	VFCMGT_H8(0, 2, 28) \
	VBSL_B16(2, 0, 28) \
	VMOV_B16(28, 16)

#define MIN_SCALAR \
	VFCMGT_H8(0, 2, 28) \
	VBSL_B16(2, 0, 28) \
	VMOV_B16(28, 16)

// func AddFloat16NEONAsm(dst, left, right *uint16, n int)
TEXT ·AddFloat16NEONAsm(SB), NOSPLIT, $0-32
	FP16_BINARY_TEMPLATE(ADD_2X8, ADD_1X8, ADD_SCALAR)

// func SubFloat16NEONAsm(dst, left, right *uint16, n int)
TEXT ·SubFloat16NEONAsm(SB), NOSPLIT, $0-32
	FP16_BINARY_TEMPLATE(SUB_2X8, SUB_1X8, SUB_SCALAR)

// func MulFloat16NEONAsm(dst, left, right *uint16, n int)
TEXT ·MulFloat16NEONAsm(SB), NOSPLIT, $0-32
	FP16_BINARY_TEMPLATE(MUL_2X8, MUL_1X8, MUL_SCALAR)

// func DivFloat16NEONAsm(dst, left, right *uint16, n int)
TEXT ·DivFloat16NEONAsm(SB), NOSPLIT, $0-32
	FP16_BINARY_TEMPLATE(DIV_2X8, DIV_1X8, DIV_SCALAR)

// func MaxFloat16NEONAsm(dst, left, right *uint16, n int)
TEXT ·MaxFloat16NEONAsm(SB), NOSPLIT, $0-32
	FP16_BINARY_TEMPLATE(MAX_2X8, MAX_1X8, MAX_SCALAR)

// func MinFloat16NEONAsm(dst, left, right *uint16, n int)
TEXT ·MinFloat16NEONAsm(SB), NOSPLIT, $0-32
	FP16_BINARY_TEMPLATE(MIN_2X8, MIN_1X8, MIN_SCALAR)
