// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON elementwise fp16 vector ops: add, sub, mul, div, max, min.
// Inputs are widened fp16→f32 via FCVTL / FCVTL2 (single NEON
// instructions), the operation runs in f32, results are narrowed
// back via FCVTN / FCVTN2.
//
// Matches the scalar reference exactly:
//   sum := float32(left[i]) + float32(right[i])
//   out[i] = float16FromFloat32(sum)
// The f32 arithmetic in between is identical, and the FCVTL/FCVTN
// hardware conversions use IEEE-754 round-to-nearest-even — same as
// the Go reference's math.Float32frombits / math.Float32bits paths.

#include "textflag.h"

// FCVTL Vd.4S, Vn.4H: 0x0E217800 base
// FCVTL2 Vd.4S, Vn.8H: 0x4E217800 base
// FCVTN Vd.4H, Vn.4S: 0x0E216800 base
// FCVTN2 Vd.8H, Vn.4S: 0x4E216800 base
#define VFCVTL_4S(n, d)   WORD $(0x0E217800 | ((n) << 5) | (d))
#define VFCVTL2_4S(n, d)  WORD $(0x4E217800 | ((n) << 5) | (d))
#define VFCVTN_4H(n, d)   WORD $(0x0E216800 | ((n) << 5) | (d))
#define VFCVTN2_8H(n, d)  WORD $(0x4E216800 | ((n) << 5) | (d))

// FADD/FSUB/FMUL/FDIV vector .4S
#define VFADD_S4(m, n, d) WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFSUB_S4(m, n, d) WORD $(0x4EA0D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_S4(m, n, d) WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFDIV_S4(m, n, d) WORD $(0x6E20FC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFCMGT_S4(m, n, d) WORD $(0x6EA0E400 | ((m) << 16) | ((n) << 5) | (d))
#define VBSL_B16(m, n, d)  WORD $(0x6E601C00 | ((m) << 16) | ((n) << 5) | (d))
#define VMOV_B16(src, dst) WORD $(0x4EA01C00 | ((src) << 16) | ((src) << 5) | (dst))

#define FP16_BINARY_TEMPLATE(op_4x4, op_2x2, op_scalar)             \
    MOVD dst+0(FP), R0                                              \
    MOVD left+8(FP), R1                                             \
    MOVD right+16(FP), R2                                           \
    MOVD n+24(FP), R3                                               \
                                                                    \
loop16:                                                             \
    CMP  $16, R3                                                    \
    BLT  loop8                                                      \
    VLD1.P 32(R1), [V0.H8, V1.H8]                                   \
    VLD1.P 32(R2), [V2.H8, V3.H8]                                   \
    VFCVTL_4S(0, 4)                                                 \
    VFCVTL2_4S(0, 5)                                                \
    VFCVTL_4S(1, 6)                                                 \
    VFCVTL2_4S(1, 7)                                                \
    VFCVTL_4S(2, 8)                                                 \
    VFCVTL2_4S(2, 9)                                                \
    VFCVTL_4S(3, 10)                                                \
    VFCVTL2_4S(3, 11)                                               \
    op_4x4                                                          \
    VFCVTN_4H(4, 12)                                                \
    VFCVTN2_8H(5, 12)                                               \
    VFCVTN_4H(6, 13)                                                \
    VFCVTN2_8H(7, 13)                                               \
    VST1.P [V12.H8, V13.H8], 32(R0)                                 \
    SUB  $16, R3                                                    \
    B    loop16                                                     \
                                                                    \
loop8:                                                              \
    CMP  $8, R3                                                     \
    BLT  scalar_tail                                                \
    VLD1.P 16(R1), [V0.H8]                                          \
    VLD1.P 16(R2), [V2.H8]                                          \
    VFCVTL_4S(0, 4)                                                 \
    VFCVTL2_4S(0, 5)                                                \
    VFCVTL_4S(2, 8)                                                 \
    VFCVTL2_4S(2, 9)                                                \
    op_2x2                                                          \
    VFCVTN_4H(4, 12)                                                \
    VFCVTN2_8H(5, 12)                                               \
    VST1.P [V12.H8], 16(R0)                                         \
    SUB  $8, R3                                                     \
    B    loop8                                                      \
                                                                    \
scalar_tail:                                                        \
    CBZ  R3, done                                                   \
                                                                    \
scalar_loop:                                                        \
    MOVHU (R1), R4                                                  \
    MOVHU (R2), R5                                                  \
    VMOV R4, V0.H[0]                                                \
    VMOV R5, V2.H[0]                                                \
    VFCVTL_4S(0, 4)                                                 \
    VFCVTL_4S(2, 8)                                                 \
    VMOV V4.S[0], R6                                                \
    VMOV V8.S[0], R7                                                \
    FMOVS R6, F0                                                    \
    FMOVS R7, F1                                                    \
    op_scalar                                                       \
    FMOVS F0, R6                                                    \
    VMOV R6, V4.S[0]                                                \
    VFCVTN_4H(4, 12)                                                \
    VMOV V12.H[0], R6                                               \
    MOVH R6, (R0)                                                   \
    ADD  $2, R1                                                     \
    ADD  $2, R2                                                     \
    ADD  $2, R0                                                     \
    SUB  $1, R3                                                     \
    CBNZ R3, scalar_loop                                            \
                                                                    \
done:                                                               \
    RET

#define ADD_4X4 \
    VFADD_S4(8, 4, 4)   \
    VFADD_S4(9, 5, 5)   \
    VFADD_S4(10, 6, 6)  \
    VFADD_S4(11, 7, 7)

#define ADD_2X2 \
    VFADD_S4(8, 4, 4)   \
    VFADD_S4(9, 5, 5)

#define ADD_SCALAR_S FADDS F1, F0, F0

#define SUB_4X4 \
    VFSUB_S4(8, 4, 4)   \
    VFSUB_S4(9, 5, 5)   \
    VFSUB_S4(10, 6, 6)  \
    VFSUB_S4(11, 7, 7)

#define SUB_2X2 \
    VFSUB_S4(8, 4, 4)   \
    VFSUB_S4(9, 5, 5)

#define SUB_SCALAR_S FSUBS F1, F0, F0

#define MUL_4X4 \
    VFMUL_S4(8, 4, 4)   \
    VFMUL_S4(9, 5, 5)   \
    VFMUL_S4(10, 6, 6)  \
    VFMUL_S4(11, 7, 7)

#define MUL_2X2 \
    VFMUL_S4(8, 4, 4)   \
    VFMUL_S4(9, 5, 5)

#define MUL_SCALAR_S FMULS F1, F0, F0

#define DIV_4X4 \
    VFDIV_S4(8, 4, 4)   \
    VFDIV_S4(9, 5, 5)   \
    VFDIV_S4(10, 6, 6)  \
    VFDIV_S4(11, 7, 7)

#define DIV_2X2 \
    VFDIV_S4(8, 4, 4)   \
    VFDIV_S4(9, 5, 5)

#define DIV_SCALAR_S FDIVS F1, F0, F0

#define MAX_4X4 \
    VFCMGT_S4(8, 4, 16)  \
    VFCMGT_S4(9, 5, 17)  \
    VFCMGT_S4(10, 6, 18) \
    VFCMGT_S4(11, 7, 19) \
    VBSL_B16(8, 4, 16)   \
    VBSL_B16(9, 5, 17)   \
    VBSL_B16(10, 6, 18)  \
    VBSL_B16(11, 7, 19)  \
    VMOV_B16(16, 4)      \
    VMOV_B16(17, 5)      \
    VMOV_B16(18, 6)      \
    VMOV_B16(19, 7)

#define MAX_2X2 \
    VFCMGT_S4(8, 4, 16)  \
    VFCMGT_S4(9, 5, 17)  \
    VBSL_B16(8, 4, 16)   \
    VBSL_B16(9, 5, 17)   \
    VMOV_B16(16, 4)      \
    VMOV_B16(17, 5)

#define MAX_SCALAR_S \
    FCMPS F1, F0       \
    FCSELS GT, F0, F1, F0

#define MIN_4X4 \
    VFCMGT_S4(4, 8, 16)  \
    VFCMGT_S4(5, 9, 17)  \
    VFCMGT_S4(6, 10, 18) \
    VFCMGT_S4(7, 11, 19) \
    VBSL_B16(8, 4, 16)   \
    VBSL_B16(9, 5, 17)   \
    VBSL_B16(10, 6, 18)  \
    VBSL_B16(11, 7, 19)  \
    VMOV_B16(16, 4)      \
    VMOV_B16(17, 5)      \
    VMOV_B16(18, 6)      \
    VMOV_B16(19, 7)

#define MIN_2X2 \
    VFCMGT_S4(4, 8, 16)  \
    VFCMGT_S4(5, 9, 17)  \
    VBSL_B16(8, 4, 16)   \
    VBSL_B16(9, 5, 17)   \
    VMOV_B16(16, 4)      \
    VMOV_B16(17, 5)

#define MIN_SCALAR_S \
    FCMPS F1, F0       \
    FCSELS LT, F0, F1, F0

// func AddFloat16NEONAsm(dst, left, right *uint16, n int)
TEXT ·AddFloat16NEONAsm(SB), NOSPLIT, $0-32
    FP16_BINARY_TEMPLATE(ADD_4X4, ADD_2X2, ADD_SCALAR_S)

// func SubFloat16NEONAsm(dst, left, right *uint16, n int)
TEXT ·SubFloat16NEONAsm(SB), NOSPLIT, $0-32
    FP16_BINARY_TEMPLATE(SUB_4X4, SUB_2X2, SUB_SCALAR_S)

// func MulFloat16NEONAsm(dst, left, right *uint16, n int)
TEXT ·MulFloat16NEONAsm(SB), NOSPLIT, $0-32
    FP16_BINARY_TEMPLATE(MUL_4X4, MUL_2X2, MUL_SCALAR_S)

// func DivFloat16NEONAsm(dst, left, right *uint16, n int)
TEXT ·DivFloat16NEONAsm(SB), NOSPLIT, $0-32
    FP16_BINARY_TEMPLATE(DIV_4X4, DIV_2X2, DIV_SCALAR_S)

// func MaxFloat16NEONAsm(dst, left, right *uint16, n int)
TEXT ·MaxFloat16NEONAsm(SB), NOSPLIT, $0-32
    FP16_BINARY_TEMPLATE(MAX_4X4, MAX_2X2, MAX_SCALAR_S)

// func MinFloat16NEONAsm(dst, left, right *uint16, n int)
TEXT ·MinFloat16NEONAsm(SB), NOSPLIT, $0-32
    FP16_BINARY_TEMPLATE(MIN_4X4, MIN_2X2, MIN_SCALAR_S)
