// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON unary fp16 ops: abs, neg, sqrt, relu. Native .8H — no f32 widen.

#include "textflag.h"

#define VFABS_H8(n, d)     WORD $(0x4EF8F800 | ((n) << 5) | (d))
#define VFNEG_H8(n, d)     WORD $(0x6EF8F800 | ((n) << 5) | (d))
#define VFSQRT_H8(n, d)    WORD $(0x6EF9F800 | ((n) << 5) | (d))
#define VFCMGT_H8(m, n, d) WORD $(0x6EC02400 | ((m) << 16) | ((n) << 5) | (d))
#define VBSL_B16(m, n, d)  WORD $(0x6E601C00 | ((m) << 16) | ((n) << 5) | (d))
#define VMOV_B16(src, dst) WORD $(0x4EA01C00 | ((src) << 16) | ((src) << 5) | (dst))

#define FP16_UNARY_TEMPLATE(op_2x8, op_1x8, op_scalar)              \
	MOVD dst+0(FP), R0                                              \
	MOVD src+8(FP), R1                                              \
	MOVD n+16(FP), R2                                               \
                                                                    \
	VEOR V31.B16, V31.B16, V31.B16                                  \
                                                                    \
loop16:                                                             \
	CMP  $16, R2                                                    \
	BLT  loop8                                                      \
	VLD1.P 32(R1), [V0.H8, V1.H8]                                   \
	op_2x8                                                          \
	VST1.P [V16.H8, V17.H8], 32(R0)                                 \
	SUB  $16, R2                                                    \
	B    loop16                                                     \
                                                                    \
loop8:                                                              \
	CMP  $8, R2                                                     \
	BLT  scalar_tail                                                \
	VLD1.P 16(R1), [V0.H8]                                          \
	op_1x8                                                          \
	VST1.P [V16.H8], 16(R0)                                         \
	SUB  $8, R2                                                     \
	B    loop8                                                      \
                                                                    \
scalar_tail:                                                        \
	CBZ  R2, done                                                   \
                                                                    \
scalar_loop:                                                        \
	MOVHU (R1), R3                                                  \
	VMOV R3, V0.H[0]                                                \
	op_scalar                                                       \
	VMOV V16.H[0], R3                                               \
	MOVH R3, (R0)                                                   \
	ADD  $2, R1                                                     \
	ADD  $2, R0                                                     \
	SUB  $1, R2                                                     \
	CBNZ R2, scalar_loop                                            \
                                                                    \
done:                                                               \
	RET

#define ABS_2X8 \
	VFABS_H8(0, 16) \
	VFABS_H8(1, 17)

#define ABS_1X8 \
	VFABS_H8(0, 16)

#define ABS_SCALAR \
	VFABS_H8(0, 16)

#define NEG_2X8 \
	VFNEG_H8(0, 16) \
	VFNEG_H8(1, 17)

#define NEG_1X8 \
	VFNEG_H8(0, 16)

#define NEG_SCALAR \
	VFNEG_H8(0, 16)

#define SQRT_2X8 \
	VFSQRT_H8(0, 16) \
	VFSQRT_H8(1, 17)

#define SQRT_1X8 \
	VFSQRT_H8(0, 16)

#define SQRT_SCALAR \
	VFSQRT_H8(0, 16)

#define RELU_2X8 \
	VFCMGT_H8(31, 0, 28) \
	VFCMGT_H8(31, 1, 29) \
	VBSL_B16(31, 0, 28) \
	VBSL_B16(31, 1, 29) \
	VMOV_B16(28, 16) \
	VMOV_B16(29, 17)

#define RELU_1X8 \
	VFCMGT_H8(31, 0, 28) \
	VBSL_B16(31, 0, 28) \
	VMOV_B16(28, 16)

#define RELU_SCALAR \
	VFCMGT_H8(31, 0, 28) \
	VBSL_B16(31, 0, 28) \
	VMOV_B16(28, 16)

// func AbsFloat16NEONAsm(dst, src *uint16, n int)
TEXT ·AbsFloat16NEONAsm(SB), NOSPLIT, $0-24
	FP16_UNARY_TEMPLATE(ABS_2X8, ABS_1X8, ABS_SCALAR)

// func NegFloat16NEONAsm(dst, src *uint16, n int)
TEXT ·NegFloat16NEONAsm(SB), NOSPLIT, $0-24
	FP16_UNARY_TEMPLATE(NEG_2X8, NEG_1X8, NEG_SCALAR)

// func SqrtFloat16NEONAsm(dst, src *uint16, n int)
TEXT ·SqrtFloat16NEONAsm(SB), NOSPLIT, $0-24
	FP16_UNARY_TEMPLATE(SQRT_2X8, SQRT_1X8, SQRT_SCALAR)

// func ReluFloat16NEONAsm(dst, src *uint16, n int)
TEXT ·ReluFloat16NEONAsm(SB), NOSPLIT, $0-24
	FP16_UNARY_TEMPLATE(RELU_2X8, RELU_1X8, RELU_SCALAR)
