// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON unary fp16 ops: abs, neg, sqrt, relu. Widen → f32 op → narrow.

#include "textflag.h"

#define VFCVTL_4S(n, d)   WORD $(0x0E217800 | ((n) << 5) | (d))
#define VFCVTL2_4S(n, d)  WORD $(0x4E217800 | ((n) << 5) | (d))
#define VFCVTN_4H(n, d)   WORD $(0x0E216800 | ((n) << 5) | (d))
#define VFCVTN2_8H(n, d)  WORD $(0x4E216800 | ((n) << 5) | (d))
#define VFABS_S4(n, d)    WORD $(0x4EA0F800 | ((n) << 5) | (d))
#define VFNEG_S4(n, d)    WORD $(0x6EA0F800 | ((n) << 5) | (d))
#define VFSQRT_S4(n, d)   WORD $(0x6EA1F800 | ((n) << 5) | (d))
#define VFCMGT_S4(m, n, d) WORD $(0x6EA0E400 | ((m) << 16) | ((n) << 5) | (d))
#define VBSL_B16(m, n, d) WORD $(0x6E601C00 | ((m) << 16) | ((n) << 5) | (d))

#define FP16_UNARY_TEMPLATE(op_4x4, op_2x2, op_scalar)              \
    MOVD dst+0(FP), R0                                              \
    MOVD src+8(FP), R1                                              \
    MOVD n+16(FP), R2                                               \
                                                                    \
    VEOR V31.B16, V31.B16, V31.B16                                  \
                                                                    \
loop16:                                                             \
    CMP  $16, R2                                                    \
    BLT  loop8                                                      \
    VLD1.P 32(R1), [V0.H8, V1.H8]                                   \
    VFCVTL_4S(0, 4)                                                 \
    VFCVTL2_4S(0, 5)                                                \
    VFCVTL_4S(1, 6)                                                 \
    VFCVTL2_4S(1, 7)                                                \
    op_4x4                                                          \
    VFCVTN_4H(8, 12)                                                \
    VFCVTN2_8H(9, 12)                                               \
    VFCVTN_4H(10, 13)                                               \
    VFCVTN2_8H(11, 13)                                              \
    VST1.P [V12.H8, V13.H8], 32(R0)                                 \
    SUB  $16, R2                                                    \
    B    loop16                                                     \
                                                                    \
loop8:                                                              \
    CMP  $8, R2                                                     \
    BLT  scalar_tail                                                \
    VLD1.P 16(R1), [V0.H8]                                          \
    VFCVTL_4S(0, 4)                                                 \
    VFCVTL2_4S(0, 5)                                                \
    op_2x2                                                          \
    VFCVTN_4H(8, 12)                                                \
    VFCVTN2_8H(9, 12)                                               \
    VST1.P [V12.H8], 16(R0)                                         \
    SUB  $8, R2                                                     \
    B    loop8                                                      \
                                                                    \
scalar_tail:                                                        \
    CBZ  R2, done                                                   \
                                                                    \
scalar_loop:                                                        \
    MOVHU (R1), R3                                                  \
    VMOV R3, V0.H[0]                                                \
    VFCVTL_4S(0, 4)                                                 \
    VMOV V4.S[0], R3                                                \
    FMOVS R3, F0                                                    \
    op_scalar                                                       \
    FMOVS F0, R3                                                    \
    VMOV R3, V8.S[0]                                                \
    VFCVTN_4H(8, 12)                                                \
    VMOV V12.H[0], R3                                               \
    MOVH R3, (R0)                                                   \
    ADD  $2, R1                                                     \
    ADD  $2, R0                                                     \
    SUB  $1, R2                                                     \
    CBNZ R2, scalar_loop                                            \
                                                                    \
done:                                                               \
    RET

#define ABS_4X4 \
    VFABS_S4(4, 8)   \
    VFABS_S4(5, 9)   \
    VFABS_S4(6, 10)  \
    VFABS_S4(7, 11)

#define ABS_2X2 \
    VFABS_S4(4, 8)   \
    VFABS_S4(5, 9)

#define ABS_SCALAR_S FABSS F0, F0

#define NEG_4X4 \
    VFNEG_S4(4, 8)   \
    VFNEG_S4(5, 9)   \
    VFNEG_S4(6, 10)  \
    VFNEG_S4(7, 11)

#define NEG_2X2 \
    VFNEG_S4(4, 8)   \
    VFNEG_S4(5, 9)

#define NEG_SCALAR_S FNEGS F0, F0

#define SQRT_4X4 \
    VFSQRT_S4(4, 8)   \
    VFSQRT_S4(5, 9)   \
    VFSQRT_S4(6, 10)  \
    VFSQRT_S4(7, 11)

#define SQRT_2X2 \
    VFSQRT_S4(4, 8)   \
    VFSQRT_S4(5, 9)

#define SQRT_SCALAR_S FSQRTS F0, F0

#define RELU_4X4 \
    VFCMGT_S4(31, 4, 8)  \
    VFCMGT_S4(31, 5, 9)  \
    VFCMGT_S4(31, 6, 10) \
    VFCMGT_S4(31, 7, 11) \
    VBSL_B16(31, 4, 8)   \
    VBSL_B16(31, 5, 9)   \
    VBSL_B16(31, 6, 10)  \
    VBSL_B16(31, 7, 11)

#define RELU_2X2 \
    VFCMGT_S4(31, 4, 8)  \
    VFCMGT_S4(31, 5, 9)  \
    VBSL_B16(31, 4, 8)   \
    VBSL_B16(31, 5, 9)

#define RELU_SCALAR_S \
    FMOVS ZR, F1       \
    FCMPS F1, F0       \
    FCSELS GT, F0, F1, F0

// func AbsFloat16NEONAsm(dst, src *uint16, n int)
TEXT ·AbsFloat16NEONAsm(SB), NOSPLIT, $0-24
    FP16_UNARY_TEMPLATE(ABS_4X4, ABS_2X2, ABS_SCALAR_S)

// func NegFloat16NEONAsm(dst, src *uint16, n int)
TEXT ·NegFloat16NEONAsm(SB), NOSPLIT, $0-24
    FP16_UNARY_TEMPLATE(NEG_4X4, NEG_2X2, NEG_SCALAR_S)

// func SqrtFloat16NEONAsm(dst, src *uint16, n int)
TEXT ·SqrtFloat16NEONAsm(SB), NOSPLIT, $0-24
    FP16_UNARY_TEMPLATE(SQRT_4X4, SQRT_2X2, SQRT_SCALAR_S)

// func ReluFloat16NEONAsm(dst, src *uint16, n int)
TEXT ·ReluFloat16NEONAsm(SB), NOSPLIT, $0-24
    FP16_UNARY_TEMPLATE(RELU_4X4, RELU_2X2, RELU_SCALAR_S)
