// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON elementwise float32 unary ops: abs, neg, sqrt, relu, recip
// (and friends). Each op processes 16 lanes (64 bytes) per inner
// iteration via four 128-bit registers, with a 4-lane secondary loop
// and a scalar tail.

#include "textflag.h"

// FABS Vd.4S, Vn.4S  : 0|1|0|01110|10|10000|01111|10|Rn|Rd = 0x4EA0F800
// FNEG Vd.4S, Vn.4S  : 0|1|1|01110|10|10000|01111|10|Rn|Rd = 0x6EA0F800
// FSQRT Vd.4S, Vn.4S : 0|1|1|01110|10|10000|11111|10|Rn|Rd = 0x6EA1F800
#define VFABS_S4(n, d)  WORD $(0x4EA0F800 | ((n) << 5) | (d))
#define VFNEG_S4(n, d)  WORD $(0x6EA0F800 | ((n) << 5) | (d))
#define VFSQRT_S4(n, d) WORD $(0x6EA1F800 | ((n) << 5) | (d))

// FCMGT (vector, register), .4S: 0|1|1|01110|10|1|Rm|11100|1|Rn|Rd = 0x6EA0E400
#define VFCMGT_S4(m, n, d) WORD $(0x6EA0E400 | ((m) << 16) | ((n) << 5) | (d))
// BSL Vd.16B, Vn.16B, Vm.16B: 0|1|1|01110|01|1|Rm|00011|1|Rn|Rd = 0x6E601C00
// Vd = (Vd & Vn) | (~Vd & Vm).
#define VBSL_B16(m, n, d) WORD $(0x6E601C00 | ((m) << 16) | ((n) << 5) | (d))

#define UNARY_TEMPLATE(op_4x4, op_4, op_scalar)                    \
    MOVD dst+0(FP), R0                                              \
    MOVD src+8(FP), R1                                              \
    MOVD n+16(FP), R2                                               \
                                                                    \
loop16:                                                             \
    CMP  $16, R2                                                    \
    BLT  loop4                                                      \
    VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]                     \
    op_4x4                                                          \
    VST1.P [V4.S4, V5.S4, V6.S4, V7.S4], 64(R0)                     \
    SUB  $16, R2                                                    \
    B    loop16                                                     \
                                                                    \
loop4:                                                              \
    CMP  $4, R2                                                     \
    BLT  scalar_tail                                                \
    VLD1.P 16(R1), [V0.S4]                                          \
    op_4                                                            \
    VST1.P [V4.S4], 16(R0)                                          \
    SUB  $4, R2                                                     \
    B    loop4                                                      \
                                                                    \
scalar_tail:                                                        \
    CBZ  R2, done                                                   \
                                                                    \
scalar_loop:                                                        \
    FMOVS (R1), F0                                                  \
    op_scalar                                                       \
    FMOVS F0, (R0)                                                  \
    ADD  $4, R1                                                     \
    ADD  $4, R0                                                     \
    SUB  $1, R2                                                     \
    CBNZ R2, scalar_loop                                            \
                                                                    \
done:                                                               \
    RET

#define ABS_4X4                                                     \
    VFABS_S4(0, 4)                                                  \
    VFABS_S4(1, 5)                                                  \
    VFABS_S4(2, 6)                                                  \
    VFABS_S4(3, 7)

#define ABS_4                                                       \
    VFABS_S4(0, 4)

#define ABS_SCALAR                                                  \
    FABSS F0, F0

#define NEG_4X4                                                     \
    VFNEG_S4(0, 4)                                                  \
    VFNEG_S4(1, 5)                                                  \
    VFNEG_S4(2, 6)                                                  \
    VFNEG_S4(3, 7)

#define NEG_4                                                       \
    VFNEG_S4(0, 4)

#define NEG_SCALAR                                                  \
    FNEGS F0, F0

#define SQRT_4X4                                                    \
    VFSQRT_S4(0, 4)                                                 \
    VFSQRT_S4(1, 5)                                                 \
    VFSQRT_S4(2, 6)                                                 \
    VFSQRT_S4(3, 7)

#define SQRT_4                                                      \
    VFSQRT_S4(0, 4)

#define SQRT_SCALAR                                                 \
    FSQRTS F0, F0

// func AbsFloat32NEONAsm(dst, src *float32, n int)
TEXT ·AbsFloat32NEONAsm(SB), NOSPLIT, $0-24
    UNARY_TEMPLATE(ABS_4X4, ABS_4, ABS_SCALAR)

// func NegFloat32NEONAsm(dst, src *float32, n int)
TEXT ·NegFloat32NEONAsm(SB), NOSPLIT, $0-24
    UNARY_TEMPLATE(NEG_4X4, NEG_4, NEG_SCALAR)

// func SqrtFloat32NEONAsm(dst, src *float32, n int)
TEXT ·SqrtFloat32NEONAsm(SB), NOSPLIT, $0-24
    UNARY_TEMPLATE(SQRT_4X4, SQRT_4, SQRT_SCALAR)

// ReLU follows the unary loop shape but holds a zero vector in V8
// across the entire function so the inner loop only pays for FCMGT
// and BSL (no per-iteration VEOR). The scalar reference is:
//   for index, value := range input {
//       out[index] = 0; if value > 0 { out[index] = value }
//   }
// which does NOT propagate NaN. FCMGT returns false on any NaN input,
// so BSL falls through to the zero vector — matches scalar bit-for-bit.
//
// func ReluFloat32NEONAsm(dst, src *float32, n int)
TEXT ·ReluFloat32NEONAsm(SB), NOSPLIT, $0-24
    MOVD dst+0(FP), R0
    MOVD src+8(FP), R1
    MOVD n+16(FP), R2

    // V8 holds the zero vector across the whole function.
    VEOR V8.B16, V8.B16, V8.B16

relu_loop16:
    CMP  $16, R2
    BLT  relu_loop4
    VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
    VFCMGT_S4(8, 0, 4)
    VFCMGT_S4(8, 1, 5)
    VFCMGT_S4(8, 2, 6)
    VFCMGT_S4(8, 3, 7)
    VBSL_B16(8, 0, 4)
    VBSL_B16(8, 1, 5)
    VBSL_B16(8, 2, 6)
    VBSL_B16(8, 3, 7)
    VST1.P [V4.S4, V5.S4, V6.S4, V7.S4], 64(R0)
    SUB  $16, R2
    B    relu_loop16

relu_loop4:
    CMP  $4, R2
    BLT  relu_scalar_tail
    VLD1.P 16(R1), [V0.S4]
    VFCMGT_S4(8, 0, 4)
    VBSL_B16(8, 0, 4)
    VST1.P [V4.S4], 16(R0)
    SUB  $4, R2
    B    relu_loop4

relu_scalar_tail:
    CBZ  R2, relu_done

    // F1 holds scalar zero across the tail.
    FMOVS ZR, F1

relu_scalar_loop:
    FMOVS (R1), F0
    FCMPS F1, F0
    FCSELS GT, F0, F1, F0
    FMOVS F0, (R0)
    ADD  $4, R1
    ADD  $4, R0
    SUB  $1, R2
    CBNZ R2, relu_scalar_loop

relu_done:
    RET
