// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON flash-attention row helpers for online softmax accumulation:
//   acc = acc * alpha + valueRow * shifted
//   out = acc * invNormalizer

#include "textflag.h"

#define VFMUL_S4(m, n, d) WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFMLA_S4(m, n, d) WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))

// func FlashAttentionOnlineUpdateNEONAsm(
//     acc, valueRow *float32,
//     alpha, shifted float32,
//     n int,
// )
TEXT ·FlashAttentionOnlineUpdateNEONAsm(SB), NOSPLIT, $0-32
    MOVD acc+0(FP), R0
    MOVD valueRow+8(FP), R1
    MOVD n+24(FP), R4
    FMOVS alpha+16(FP), F16
    VDUP V16.S[0], V16.S4
    FMOVS shifted+20(FP), F17
    VDUP V17.S[0], V17.S4

flash_update_loop4:
    CMP  $4, R4
    BLT  flash_update_done
    VLD1 (R0), [V0.S4]
    VLD1 (R1), [V2.S4]
    VFMUL_S4(16, 0, 0)
    VFMLA_S4(2, 17, 0)
    VST1 [V0.S4], (R0)
    ADD  $16, R0
    ADD  $16, R1
    SUB  $4, R4
    B    flash_update_loop4

flash_update_done:
    RET

// func FlashAttentionScaleNEONAsm(
//     out, acc *float32,
//     invNormalizer float32,
//     n int,
// )
TEXT ·FlashAttentionScaleNEONAsm(SB), NOSPLIT, $0-32
    MOVD out+0(FP), R0
    MOVD acc+8(FP), R1
    MOVD n+24(FP), R4
    FMOVS invNormalizer+16(FP), F16
    VDUP V16.S[0], V16.S4

flash_scale_loop4:
    CMP  $4, R4
    BLT  flash_scale_done
    VLD1 (R1), [V0.S4]
    VFMUL_S4(16, 0, 0)
    VST1 [V0.S4], (R0)
    ADD  $16, R0
    ADD  $16, R1
    SUB  $4, R4
    B    flash_scale_loop4

flash_scale_done:
    RET
