// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0

#include "textflag.h"

// func bfloat16ToFloat32NEONAsm(dst *float32, src *uint16, n int) int
// dst at +0(FP), src at +8(FP), n at +16(FP), return at +24(FP)
//
// Algorithm: each bf16 occupies the upper 16 bits of its float32
// representation. We produce that by zipping each uint16 with a zero
// halfword. Go's plan9 ZIP1 reverses source order vs the ARM
// mnemonic — `VZIP1 Vsrc1_go, Vsrc2_go, Vdst` is encoded as the ARM
// `ZIP1 Vdst, Vsrc2_go, Vsrc1_go`, which produces Vdst[2k] =
// Vsrc2_go[k] and Vdst[2k+1] = Vsrc1_go[k]. To get [0, a, 0, a, ...]
// (so `a` ends up in the high 16 bits of each u32 lane in little-
// endian memory) we therefore put the source vector first and zeros
// second: `VZIP1 V_src, V_zero, V_dst`.
TEXT ·bfloat16ToFloat32NEONAsm(SB), NOSPLIT, $0-32
    MOVD dst+0(FP), R0
    MOVD src+8(FP), R1
    MOVD n+16(FP), R2

    MOVD R2, R3              // return value: number of elements consumed

    VEOR V31.B16, V31.B16, V31.B16

loop8:
    CMP  $8, R2
    BLT  tail4
    VLD1.P 16(R1), [V0.H8]
    VZIP1 V0.H8, V31.H8, V1.H8 // V1 = [0, a0, 0, a1, 0, a2, 0, a3]
    VZIP2 V0.H8, V31.H8, V2.H8 // V2 = [0, a4, 0, a5, 0, a6, 0, a7]
    VST1.P [V1.S4, V2.S4], 32(R0)
    SUB  $8, R2
    B    loop8

tail4:
    CMP  $4, R2
    BLT  tail_scalar
    VLD1.P 8(R1), [V0.H4]
    VZIP1 V0.H8, V31.H8, V1.H8 // valid 4 u32s in lower lanes
    VST1.P [V1.S4], 16(R0)
    SUB  $4, R2

tail_scalar:
    CBZ  R2, done

scalar_loop:
    MOVHU.P 2(R1), R4
    LSL   $16, R4, R4
    MOVW.P R4, 4(R0)
    SUB   $1, R2
    CBNZ  R2, scalar_loop

done:
    MOVD R3, ret+24(FP)
    RET

// func float32ToBFloat16NEONAsm(dst *uint16, src *float32, n int) int
// Truncation-rounding bf16: take the upper 16 bits of each f32.
// UZP2 with the same vector as both sources picks every odd-indexed
// halfword, which in little-endian is the upper 16 bits of each
// u32 lane.
TEXT ·float32ToBFloat16NEONAsm(SB), NOSPLIT, $0-32
    MOVD dst+0(FP), R0
    MOVD src+8(FP), R1
    MOVD n+16(FP), R2

    MOVD R2, R3

loop8:
    CMP  $8, R2
    BLT  tail4
    VLD1.P 32(R1), [V0.S4, V1.S4]
    VUZP2 V1.H8, V0.H8, V2.H8     // odd halfwords of V0 then V1
    VST1.P [V2.H8], 16(R0)
    SUB   $8, R2
    B     loop8

tail4:
    CMP  $4, R2
    BLT  tail_scalar
    VLD1.P 16(R1), [V0.S4]
    VUZP2 V0.H8, V0.H8, V2.H8     // odd halfwords replicate to all 8 lanes
    VST1.P [V2.H4], 8(R0)
    SUB   $4, R2

tail_scalar:
    CBZ  R2, done

scalar_loop:
    MOVWU.P 4(R1), R4
    LSR   $16, R4, R4
    MOVH.P R4, 2(R0)
    SUB   $1, R2
    CBNZ  R2, scalar_loop

done:
    MOVD R3, ret+24(FP)
    RET
