// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0

#include "textflag.h"

// Raw WORD encodings for NEON FCVTL / FCVTL2 / FCVTN / FCVTN2 since
// Go's plan9 assembler doesn't expose those mnemonics. The encodings
// follow the ARM ARM (FCVTL: 0Q | 0 0001110 0 0100001 0111 10 | Vn[4:0]
// | Vd[4:0]).
//
// FCVTL  V1.4S, V0.4H  → 0x0E217801
// FCVTL2 V2.4S, V0.8H  → 0x4E217802
// FCVTN  V2.4H, V0.4S  → 0x0E216802
// FCVTN2 V2.8H, V1.4S  → 0x4E216822

#define FCVTL_V0_V1   WORD $0x0E217801
#define FCVTL2_V0_V2  WORD $0x4E217802
#define FCVTN_V0_V2   WORD $0x0E216802
#define FCVTN2_V1_V2  WORD $0x4E216822

// func float16ToFloat32NEONAsm(dst *float32, src *uint16, n int) int
TEXT ·float16ToFloat32NEONAsm(SB), NOSPLIT, $0-32
    MOVD dst+0(FP), R0
    MOVD src+8(FP), R1
    MOVD n+16(FP), R2
    MOVD R2, R3

loop8:
    CMP  $8, R2
    BLT  tail4
    VLD1.P 16(R1), [V0.H8]
    FCVTL_V0_V1                       // FCVTL  V1.4S, V0.4H
    FCVTL2_V0_V2                      // FCVTL2 V2.4S, V0.8H
    VST1.P [V1.S4, V2.S4], 32(R0)
    SUB  $8, R2
    B    loop8

tail4:
    CMP  $4, R2
    BLT  tail_scalar
    VLD1.P 8(R1), [V0.H4]
    FCVTL_V0_V1                       // FCVTL V1.4S, V0.4H
    VST1.P [V1.S4], 16(R0)
    SUB  $4, R2

tail_scalar:
    CBZ  R2, done

scalar_loop:
    MOVHU.P 2(R1), R4
    VMOV   R4, V0.H[0]
    FCVTL_V0_V1                       // FCVTL V1.4S, V0.4H — converts lane 0
    VMOV   V1.S[0], R5
    MOVW.P R5, 4(R0)
    SUB    $1, R2
    CBNZ   R2, scalar_loop

done:
    MOVD R3, ret+24(FP)
    RET

// func float32ToFloat16NEONAsm(dst *uint16, src *float32, n int) int
TEXT ·float32ToFloat16NEONAsm(SB), NOSPLIT, $0-32
    MOVD dst+0(FP), R0
    MOVD src+8(FP), R1
    MOVD n+16(FP), R2
    MOVD R2, R3

loop8:
    CMP  $8, R2
    BLT  tail4
    VLD1.P 32(R1), [V0.S4, V1.S4]
    FCVTN_V0_V2                       // FCVTN  V2.4H, V0.4S
    FCVTN2_V1_V2                      // FCVTN2 V2.8H, V1.4S
    VST1.P [V2.H8], 16(R0)
    SUB  $8, R2
    B    loop8

tail4:
    CMP  $4, R2
    BLT  tail_scalar
    VLD1.P 16(R1), [V0.S4]
    FCVTN_V0_V2                       // FCVTN V2.4H, V0.4S
    VST1.P [V2.H4], 8(R0)
    SUB  $4, R2

tail_scalar:
    CBZ  R2, done

scalar_loop:
    MOVWU.P 4(R1), R4
    VMOV   R4, V0.S[0]
    FCVTN_V0_V2                       // FCVTN V2.4H, V0.4S — converts lane 0
    VMOV   V2.H[0], R5
    MOVH.P R5, 2(R0)
    SUB    $1, R2
    CBNZ   R2, scalar_loop

done:
    MOVD R3, ret+24(FP)
    RET
