// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0

#include "textflag.h"

// FCVTL (f32→f64): widens 2 f32 to 2 f64. Encoding:
//   FCVTL  Vd.2D, Vn.2S → 0 0001110 0 1100001 0111 10 nnnnn ddddd = 0x0E617800
//   FCVTL2 Vd.2D, Vn.4S → 0 1001110 0 1100001 0111 10 nnnnn ddddd = 0x4E617800
// FCVTN (f64→f32): narrows 2 f64 to 2 f32.
//   FCVTN  Vd.2S, Vn.2D → 0 0001110 0 1100001 0110 10 nnnnn ddddd = 0x0E616800
//   FCVTN2 Vd.4S, Vn.2D → 0 1001110 0 1100001 0110 10 nnnnn ddddd = 0x4E616800

#define FCVTLD_V0_V1   WORD $0x0E617801
#define FCVTL2D_V0_V2  WORD $0x4E617802
#define FCVTND_V0_V2   WORD $0x0E616802
#define FCVTN2D_V1_V2  WORD $0x4E616822

// func float32ToFloat64NEONAsm(dst *float64, src *float32, n int) int
TEXT ·float32ToFloat64NEONAsm(SB), NOSPLIT, $0-32
    MOVD dst+0(FP), R0
    MOVD src+8(FP), R1
    MOVD n+16(FP), R2
    MOVD R2, R3

loop4:
    CMP  $4, R2
    BLT  tail2
    VLD1.P 16(R1), [V0.S4]
    FCVTLD_V0_V1                       // FCVTL  V1.2D, V0.2S
    FCVTL2D_V0_V2                      // FCVTL2 V2.2D, V0.4S
    VST1.P [V1.D2, V2.D2], 32(R0)
    SUB  $4, R2
    B    loop4

tail2:
    CMP  $2, R2
    BLT  tail_scalar
    VLD1.P 8(R1), [V0.S2]
    FCVTLD_V0_V1                       // FCVTL V1.2D, V0.2S
    VST1.P [V1.D2], 16(R0)
    SUB  $2, R2

tail_scalar:
    CBZ  R2, done

scalar_loop:
    FMOVS (R1), F0
    FCVTSD F0, F0
    FMOVD F0, (R0)
    ADD   $4, R1
    ADD   $8, R0
    SUB   $1, R2
    CBNZ  R2, scalar_loop

done:
    MOVD R3, ret+24(FP)
    RET

// func float64ToFloat32NEONAsm(dst *float32, src *float64, n int) int
TEXT ·float64ToFloat32NEONAsm(SB), NOSPLIT, $0-32
    MOVD dst+0(FP), R0
    MOVD src+8(FP), R1
    MOVD n+16(FP), R2
    MOVD R2, R3

loop4:
    CMP  $4, R2
    BLT  tail2
    VLD1.P 32(R1), [V0.D2, V1.D2]
    FCVTND_V0_V2                       // FCVTN  V2.2S, V0.2D
    FCVTN2D_V1_V2                      // FCVTN2 V2.4S, V1.2D
    VST1.P [V2.S4], 16(R0)
    SUB  $4, R2
    B    loop4

tail2:
    CMP  $2, R2
    BLT  tail_scalar
    VLD1.P 16(R1), [V0.D2]
    FCVTND_V0_V2                       // FCVTN V2.2S, V0.2D
    VST1.P [V2.S2], 8(R0)
    SUB  $2, R2

tail_scalar:
    CBZ  R2, done

scalar_loop:
    FMOVD (R1), F0
    FCVTDS F0, F0
    FMOVS F0, (R0)
    ADD   $8, R1
    ADD   $4, R0
    SUB   $1, R2
    CBNZ  R2, scalar_loop

done:
    MOVD R3, ret+24(FP)
    RET
