// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON RoPE pair rotation:
//   x'_{2i}   = x_{2i}   * cos - x_{2i+1} * sin
//   x'_{2i+1} = x_{2i}   * sin + x_{2i+1} * cos
//
// Caller precomputes cos and sin arrays per (position, pair_index)
// and passes them as f32 slices of length headDim/2. The asm walks 4
// pairs at a time using even/odd lane deinterleave + FMUL/FMLA/FMLS.

#include "textflag.h"

#define VFADD_S4(m, n, d)  WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFSUB_S4(m, n, d)  WORD $(0x4EA0D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_S4(m, n, d)  WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFMLA_S4(m, n, d)  WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))
// VUZP1 .4S: pick even-indexed S lanes
#define VUZP1_S4(m, n, d) WORD $(0x4E801800 | ((m) << 16) | ((n) << 5) | (d))
// VUZP2 .4S: pick odd-indexed S lanes
#define VUZP2_S4(m, n, d) WORD $(0x4E805800 | ((m) << 16) | ((n) << 5) | (d))
// VZIP1 .4S: interleave from low halves
#define VZIP1_S4(m, n, d) WORD $(0x4E803800 | ((m) << 16) | ((n) << 5) | (d))
// VZIP2 .4S: interleave from high halves
#define VZIP2_S4(m, n, d) WORD $(0x4E807800 | ((m) << 16) | ((n) << 5) | (d))

// func RopePairsNEONAsm(out, in, cos, sin *float32, pairs int)
// pairs = headDim / 2 — number of (even, odd) pairs in one head row.
// Input layout: out[2*p]   = in[2*p]   * cos[p] - in[2*p+1] * sin[p]
//               out[2*p+1] = in[2*p]   * sin[p] + in[2*p+1] * cos[p]
//
// Walks 4 pairs at a time → loads 8 floats interleaved (even, odd, ...).
TEXT ·RopePairsNEONAsm(SB), NOSPLIT, $0-40
    MOVD out+0(FP), R0
    MOVD in+8(FP), R1
    MOVD cos+16(FP), R2
    MOVD sin+24(FP), R3
    MOVD pairs+32(FP), R4

rope_loop4:
    CMP  $4, R4
    BLT  rope_done
    // Load 8 interleaved inputs into V0.S4, V1.S4.
    VLD1.P 32(R1), [V0.S4, V1.S4]
    // Deinterleave into even (V2) and odd (V3) lanes.
    VUZP1_S4(1, 0, 2)             // V2 = [even0, even1, even2, even3]
    VUZP2_S4(1, 0, 3)             // V3 = [odd0,  odd1,  odd2,  odd3]
    // Load 4 cosines and 4 sines.
    VLD1.P 16(R2), [V4.S4]        // V4 = cos
    VLD1.P 16(R3), [V5.S4]        // V5 = sin
    // V6 = even * cos
    VFMUL_S4(4, 2, 6)
    // V6 -= odd * sin → FMUL+FSUB or use FMLS-style; we don't have
    // FMLS macro yet, so compute V7 = odd*sin and FSUB.
    VFMUL_S4(5, 3, 7)
    VFSUB_S4(7, 6, 6)             // V6 = even*cos - odd*sin
    // V8 = even * sin
    VFMUL_S4(5, 2, 8)
    // V8 += odd * cos (FMLA Vd, Vn, Vm)
    VFMLA_S4(4, 3, 8)             // V8 = even*sin + odd*cos
    // Reinterleave V6 (even outs) and V8 (odd outs) → V9.S4, V10.S4.
    VZIP1_S4(8, 6, 9)             // V9 = [V6[0], V8[0], V6[1], V8[1]]
    VZIP2_S4(8, 6, 10)            // V10= [V6[2], V8[2], V6[3], V8[3]]
    VST1.P [V9.S4, V10.S4], 32(R0)
    SUB  $4, R4
    B    rope_loop4

rope_done:
    RET
