// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON int8 quantization. Scalar reference:
//   scaled  = math.Round(f64(value / scale)) + f64(zeroPoint)
//   if scaled > 127  → 127
//   if scaled < -128 → -128
//   else            → int8(scaled)
//
// NEON pipeline per 16 lanes:
//   load .S4 × 4 → multiply by (1/scale) broadcast
//   → FCVTAS (round-to-nearest-ties-away, matches math.Round) → int32 .S4
//   → add zeroPoint (broadcast int32) → SQXTN saturating narrow .S→.H
//   → SQXTN saturating narrow .H→.B → store .B16

#include "textflag.h"

// FCVTAS Vd.4S, Vn.4S  — float→int32, ties away from zero
#define VFCVTAS_S4(n, d) WORD $(0x4E21C800 | ((n) << 5) | (d))
// FMUL .4S
#define VFMUL_S4(m, n, d) WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))
// ADD vector .4S (integer)
#define VADD_S4(m, n, d)  WORD $(0x4EA08400 | ((m) << 16) | ((n) << 5) | (d))
// SQXTN .4H from .4S, signed-saturating
#define VSQXTN_H4(n, d)   WORD $(0x0E614800 | ((n) << 5) | (d))
#define VSQXTN2_H8(n, d)  WORD $(0x4E614800 | ((n) << 5) | (d))
// SQXTN .8B from .8H
#define VSQXTN_B8(n, d)   WORD $(0x0E214800 | ((n) << 5) | (d))
#define VSQXTN2_B16(n, d) WORD $(0x4E214800 | ((n) << 5) | (d))
// FCVTAS scalar single → 32-bit signed GPR
#define FCVTAS_WS(n, d)   WORD $(0x1E240000 | ((n) << 5) | (d))

// func QuantInt8NEONAsm(dst *int8, src *float32, n int, invScale float32, zeroPoint int32)
TEXT ·QuantInt8NEONAsm(SB), NOSPLIT, $0-32
    MOVD dst+0(FP), R0
    MOVD src+8(FP), R1
    MOVD n+16(FP), R2
    FMOVS invScale+24(FP), F30
    MOVW zeroPoint+28(FP), R3

    VDUP V30.S[0], V30.S4
    VMOV R3, V29.S[0]
    VDUP V29.S[0], V29.S4

quant_int8_loop16:
    CMP  $16, R2
    BLT  quant_int8_loop4
    VLD1.P 64(R1), [V0.S4, V1.S4, V2.S4, V3.S4]
    VFMUL_S4(30, 0, 0)
    VFMUL_S4(30, 1, 1)
    VFMUL_S4(30, 2, 2)
    VFMUL_S4(30, 3, 3)
    VFCVTAS_S4(0, 0)
    VFCVTAS_S4(1, 1)
    VFCVTAS_S4(2, 2)
    VFCVTAS_S4(3, 3)
    VADD_S4(29, 0, 0)
    VADD_S4(29, 1, 1)
    VADD_S4(29, 2, 2)
    VADD_S4(29, 3, 3)
    VSQXTN_H4(0, 4)
    VSQXTN2_H8(1, 4)
    VSQXTN_H4(2, 5)
    VSQXTN2_H8(3, 5)
    VSQXTN_B8(4, 6)
    VSQXTN2_B16(5, 6)
    VST1.P [V6.B16], 16(R0)
    SUB  $16, R2
    B    quant_int8_loop16

quant_int8_loop4:
    CMP  $4, R2
    BLT  quant_int8_scalar_tail
    VLD1.P 16(R1), [V0.S4]
    VFMUL_S4(30, 0, 0)
    VFCVTAS_S4(0, 0)
    VADD_S4(29, 0, 0)
    VSQXTN_H4(0, 4)
    VSQXTN_B8(4, 6)
    VMOV V6.S[0], R4
    MOVW.P R4, 4(R0)
    SUB  $4, R2
    B    quant_int8_loop4

quant_int8_scalar_tail:
    CBZ  R2, quant_int8_done

quant_int8_scalar_loop:
    FMOVS (R1), F0
    FMULS F30, F0, F0
    FCVTAS_WS(0, 4)
    ADDW R3, R4, R4
    // Saturate to int8 range [-128, 127].
    CMPW $127, R4
    BLE  quant_int8_no_high_sat
    MOVD $127, R4
quant_int8_no_high_sat:
    CMPW $-128, R4
    BGE  quant_int8_no_low_sat
    MOVD $-128, R4
quant_int8_no_low_sat:
    MOVB R4, (R0)
    ADD  $4, R1
    ADD  $1, R0
    SUB  $1, R2
    CBNZ R2, quant_int8_scalar_loop

quant_int8_done:
    RET
