// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0

#include "textflag.h"

#define VFMLA_S4(m, n, d) WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))
#define VMOV_VREG(src, dst) WORD $(0x4EA01C00 | ((src) << 16) | ((src) << 5) | (dst))
#define NARROW_BF16_S4_TO_H4(src) \
    VMOV_VREG(src, 8) \
    VMOV_VREG(src, 9) \
    VUZP2 V9.H8, V8.H8, V12.H8

// func MatmulRowBF16NEONAsm(cRow, aRow, b *uint16, inner, colsBlock, bCols int)
TEXT ·MatmulRowBF16NEONAsm(SB), NOSPLIT, $0-48
    MOVD cRow+0(FP), R0
    MOVD aRow+8(FP), R1
    MOVD b+16(FP), R2
    MOVD inner+24(FP), R3
    MOVD colsBlock+32(FP), R4
    MOVD bCols+40(FP), R21

    VEOR V31.B16, V31.B16, V31.B16
    LSL  $1, R21, R5
    MOVD R4, R6
    MOVD R2, R7

col_block_loop:
    CBZ  R6, mm_done
    CMP  $4, R6
    BLT  mm_done

    VEOR V0.B16, V0.B16, V0.B16

    MOVD R3, R8
    MOVD R1, R9
    MOVD R7, R10

k_loop:
    CBZ  R8, k_done
    MOVHU (R9), R11
    LSL  $16, R11, R11
    FMOVS R11, F1
    VDUP V1.S[0], V1.S4
    VLD1 (R10), [V2.H4]
    VZIP1 V2.H8, V31.H8, V20.H8
    VFMLA_S4(20, 1, 0)
    ADD  $2, R9
    ADD  R5, R10
    SUB  $1, R8
    B    k_loop

k_done:
    NARROW_BF16_S4_TO_H4(0)
    VST1 [V12.H4], (R0)
    ADD  $8, R0
    ADD  $8, R7
    SUB  $4, R6
    B    col_block_loop

mm_done:
    RET
