// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON f32 matmul outer-product driver: C[M, N] += A[M, K] × B[K, N].
// Processes the K-inner loop with one A row broadcasted lane-by-lane
// against contiguous 4-lane B columns via FMLA. Each output row of C
// is computed in 4-lane chunks.
//
// Caller is responsible for output initialization (zero) and shape
// validation. Cols is a multiple of 4; the M and K dims are arbitrary.
//
// Real NEON kernel per AGENTS.md §1.1.

#include "textflag.h"

#define VFMLA_S4(m, n, d) WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFADD_S4(m, n, d) WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))

// func MatmulRowFloat32NEONAsm(cRow, aRow, b *float32, inner, cols int)
// cRow:  output row pointer C[m, :] of length cols
// aRow:  A row pointer A[m, :] of length inner
// b:     B matrix pointer B[0, :], row-major [inner, cols]
// inner: K dimension
// cols:  N dimension (must be a multiple of 4)
TEXT ·MatmulRowFloat32NEONAsm(SB), NOSPLIT, $0-40
    MOVD cRow+0(FP), R0
    MOVD aRow+8(FP), R1
    MOVD b+16(FP), R2
    MOVD inner+24(FP), R3
    MOVD cols+32(FP), R4

    // R5 = byte stride of one B row = cols * 4.
    LSL  $2, R4, R5

    // For each block of 4 columns:
    //   acc4 = C[m, j..j+4]
    //   for k = 0..inner: acc4 += A[m, k] * B[k, j..j+4]
    //   write back acc4.
    //
    // We re-load C[m, j..] at each column block and walk B's column
    // stride to scan down K. The outer column-block loop is here.

    MOVD R4, R6                          // R6 = remaining cols (block counter, decreasing)
    MOVD R2, R7                          // R7 = B base for this column block

col_block_loop:
    CBZ  R6, mm_done
    CMP  $4, R6
    BLT  mm_done                         // cols not a multiple of 4: stop

    // Load existing C[m, j..j+4] into V0.S4.
    VLD1 (R0), [V0.S4]

    // Walk K. R8 = remaining k, R9 = A pointer copy, R10 = B pointer copy.
    MOVD R3, R8
    MOVD R1, R9
    MOVD R7, R10

k_loop:
    CBZ  R8, k_done
    // Broadcast A[m, k] into V1.S4.
    FMOVS (R9), F1
    VDUP V1.S[0], V1.S4
    // Load B[k, j..j+4] into V2.S4.
    VLD1 (R10), [V2.S4]
    // V0 += V1 * V2 — FMLA Vd, Vn, Vm: Vd = Vd + Vn * Vm.
    VFMLA_S4(2, 1, 0)
    ADD  $4, R9                          // A++ stride 1 f32
    ADD  R5, R10                         // B += one row (cols*4 bytes)
    SUB  $1, R8
    B    k_loop

k_done:
    // Store back C[m, j..j+4].
    VST1 [V0.S4], (R0)
    ADD  $16, R0                         // C row advance 4 floats
    ADD  $16, R7                         // B column-block advance 4 floats
    SUB  $4, R6
    B    col_block_loop

mm_done:
    RET
