// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON f64 matmul outer-product driver: C[M, N] += A[M, K] × B[K, N].
// Processes the K-inner loop with one A row broadcasted against
// contiguous 2-lane B columns via FMLA .2D.

#include "textflag.h"

#define VFMLA_D2(m, n, d) WORD $(0x4EE0CC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_D2(m, n, d) WORD $(0x6E60DC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFADD_D2(m, n, d) WORD $(0x4E60D400 | ((m) << 16) | ((n) << 5) | (d))

// func MatmulRowFloat64NEONAsm(cRow, aRow, b *float64, inner, cols int)
TEXT ·MatmulRowFloat64NEONAsm(SB), $16-40
    MOVD cRow+0(FP), R0
    MOVD aRow+8(FP), R1
    MOVD b+16(FP), R2
    MOVD inner+24(FP), R3
    MOVD cols+32(FP), R4

    LSL  $3, R4, R5

    MOVD R4, R6
    MOVD R2, R7

col_block_loop:
    CBZ  R6, mm_done
    CMP  $2, R6
    BLT  mm_done

    VLD1 (R0), [V0.D2]

    MOVD R3, R8
    MOVD R1, R9
    MOVD R7, R10

k_loop:
    CBZ  R8, k_done
    MOVD (R9), R12
    VMOV R12, V8.D[0]
    VDUP V8.D[0], V8.D2
    VLD1 (R10), [V2.D2]
    VFMUL_D2(8, 2, 3)
    VFADD_D2(3, 0, 0)
    ADD  $8, R9
    ADD  R5, R10
    SUB  $1, R8
    B    k_loop

k_done:
    VST1 [V0.D2], (R0)
    ADD  $16, R0
    ADD  $16, R7
    SUB  $2, R6
    B    col_block_loop

mm_done:
    RET
