// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON matmul row for fp16: native .8H multiply, f32 accumulation via
// FCVTL on products only.

#include "textflag.h"

#define VFADD_S4(m, n, d) WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_H8(m, n, d)  WORD $(0x6E401C00 | ((m) << 16) | ((n) << 5) | (d))
#define VFCVTL_4S(n, d)    WORD $(0x0E217800 | ((n) << 5) | (d))
#define VFCVTN_4H(n, d)    WORD $(0x0E216800 | ((n) << 5) | (d))

// func MatmulRowFP16NEONAsm(cRow, aRow, b *uint16, inner, colsBlock, bCols int)
TEXT ·MatmulRowFP16NEONAsm(SB), NOSPLIT, $16-48
	MOVD cRow+0(FP), R0
	MOVD aRow+8(FP), R1
	MOVD b+16(FP), R2
	MOVD inner+24(FP), R3
	MOVD colsBlock+32(FP), R4
	MOVD bCols+40(FP), R21

	LSL  $1, R21, R5
	MOVD R4, R6
	MOVD R2, R7
	MOVD RSP, R12

col_block_loop:
	CBZ  R6, mm_done
	CMP  $4, R6
	BLT  mm_done

	VEOR V0.B16, V0.B16, V0.B16

	MOVD R3, R8
	MOVD R1, R9
	MOVD R7, R10

k_loop:
	CBZ  R8, k_done
	MOVHU (R9), R11
	VMOV R11, V1.H[0]
	VMOV V1.H[0], R11
	MOVH R11, (R12)
	VLD1R (R12), [V1.H4]
	VLD1 (R10), [V2.H4]
	VFMUL_H8(2, 1, 24)
	VFCVTL_4S(24, 20)
	VFADD_S4(20, 0, 0)
	ADD  $2, R9
	ADD  R5, R10
	SUB  $1, R8
	B    k_loop

k_done:
	VFCVTN_4H(0, 12)
	VST1 [V12.H4], (R0)
	ADD  $8, R0
	ADD  $8, R7
	SUB  $4, R6
	B    col_block_loop

mm_done:
	RET
