// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON sparse CSR matmul row update for one nonzero:
//   outRow[j] += value * denseRow[j]
// Go dispatch computes denseRow from colIdx; this kernel only
// performs the vector FMLA over 16/4/scalar column blocks.

#include "textflag.h"

#define VFMLA_S4(m, n, d) WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))

// func SparseCSRMatMulRowSingleNzNEONAsm(
//     outRow *float32,
//     value float32,
//     denseRow *float32,
//     cols int,
// )
TEXT ·SparseCSRMatMulRowSingleNzNEONAsm(SB), NOSPLIT, $0-32
    MOVD outRow+0(FP), R7
    FMOVS value+8(FP), F16
    VDUP V16.S[0], V31.S4
    MOVD denseRow+16(FP), R6
    MOVD cols+24(FP), R8

sparse_nz_col16:
    CMP  $16, R8
    BLT  sparse_nz_col4
    VLD1 (R7), [V0.S4, V1.S4, V2.S4, V3.S4]
    VLD1 (R6), [V4.S4, V5.S4, V6.S4, V7.S4]
    VFMLA_S4(31, 4, 0)
    VFMLA_S4(31, 5, 1)
    VFMLA_S4(31, 6, 2)
    VFMLA_S4(31, 7, 3)
    VST1 [V0.S4, V1.S4, V2.S4, V3.S4], (R7)
    ADD  $64, R7
    ADD  $64, R6
    SUB  $16, R8
    B    sparse_nz_col16

sparse_nz_col4:
    CMP  $4, R8
    BLT  sparse_nz_col_scalar
    VLD1 (R7), [V0.S4]
    VLD1 (R6), [V4.S4]
    VFMLA_S4(31, 4, 0)
    VST1 [V0.S4], (R7)
    ADD  $16, R7
    ADD  $16, R6
    SUB  $4, R8
    B    sparse_nz_col4

sparse_nz_col_scalar:
    CBZ  R8, sparse_nz_done
    FMOVS (R7), F1
    FMOVS (R6), F2
    FMULS F16, F2, F2
    FADDS F2, F1, F1
    FMOVS F1, (R7)
    ADD  $4, R7
    ADD  $4, R6
    SUB  $1, R8
    B    sparse_nz_col_scalar

sparse_nz_done:
    RET
