// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON dropout. Per-lane xorshift32 PRNG → uniform [0, 1) f32 →
// compare against keep probability → multiply input by mask/keepProb.
//
// Args: dst, src *float32, n int, seed *uint32 (4 lane seeds),
//       keepProb float32 (1 - dropoutProb)
// Returns: nothing. Mutates seed in place so consecutive calls produce
// independent random streams.

#include "textflag.h"

#define VFMUL_S4(m, n, d)   WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))
#define VEOR_B16(m, n, d)   WORD $(0x6E201C00 | ((m) << 16) | ((n) << 5) | (d))
#define VSHL_S4_BY13(n, d)  WORD $(0x4F2D5400 | ((n) << 5) | (d))
#define VUSHR_S4_BY17(n, d) WORD $(0x6F2F0400 | ((n) << 5) | (d))
#define VSHL_S4_BY5(n, d)   WORD $(0x4F255400 | ((n) << 5) | (d))
// CMHI (unsigned higher): Vd = (Vn > Vm) ? all-ones : 0, 32-bit lanes.
#define VCMHI_S4(m, n, d)   WORD $(0x6EA03400 | ((m) << 16) | ((n) << 5) | (d))
#define VAND_B16(m, n, d)   WORD $(0x4E201C00 | ((m) << 16) | ((n) << 5) | (d))
// UCVTF (unsigned int → float): 0|1|1|01110|0|sz|10000|11101|10|Rn|Rd
// For .4S (sz=0, U=1, Q=1, opcode=11101):
// 0|1|1|01110|0|0|10000|11101|10|Rn|Rd = 0x6E21D800
#define VUCVTF_S4(n, d)     WORD $(0x6E21D800 | ((n) << 5) | (d))

DATA  dropoutC<>+0(SB)/4, $2.3283064365386963e-10  // 1.0 / 2^32 (for uint32 → [0,1))
GLOBL dropoutC<>(SB), 8, $4

// func DropoutFloat32NEONAsm(dst, src *float32, n int, seedState *uint32, scale, threshold float32)
// scale = 1 / keepProb (so kept lanes are scaled to preserve expectation).
// threshold = keepProb as uint32 representing [0, 2^32 * keepProb].
TEXT ·DropoutFloat32NEONAsm(SB), NOSPLIT, $0-40
    MOVD dst+0(FP), R0
    MOVD src+8(FP), R1
    MOVD n+16(FP), R2
    MOVD seedState+24(FP), R3
    FMOVS scale+32(FP), F16
    FMOVS threshold+36(FP), F17

    VDUP V16.S[0], V16.S4
    VDUP V17.S[0], V17.S4
    // Load 4 lane seeds from R3 into V18.S4.
    VLD1 (R3), [V18.S4]

dropout_loop4:
    CMP  $4, R2
    BLT  dropout_done
    VLD1.P 16(R1), [V0.S4]
    // xorshift32: x ^= x << 13; x ^= x >> 17; x ^= x << 5.
    VSHL_S4_BY13(18, 19)
    VEOR_B16(19, 18, 18)
    VUSHR_S4_BY17(18, 19)
    VEOR_B16(19, 18, 18)
    VSHL_S4_BY5(18, 19)
    VEOR_B16(19, 18, 18)
    // V18 now holds 4 fresh uint32 lanes. Compare against threshold:
    //   mask = (V17 > V18) ? all-ones : 0  // i.e. keep if rand < threshold
    VCMHI_S4(18, 17, 20)
    // Apply mask AND-wise to V0, then scale by V16.
    VAND_B16(20, 0, 0)
    VFMUL_S4(16, 0, 0)
    VST1.P [V0.S4], 16(R0)
    SUB  $4, R2
    B    dropout_loop4

dropout_done:
    // Save updated seed back to memory.
    VST1 [V18.S4], (R3)
    RET
