// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON L1 norm reduction for float32. Returns sum(|src[i]|).

#include "textflag.h"

#define VFADD_S4(m, n, d)  WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFABS_S4(n, d)     WORD $(0x4EA0F800 | ((n) << 5) | (d))
#define VFADDP_S4(m, n, d) WORD $(0x6E30D400 | ((m) << 16) | ((n) << 5) | (d))
#define FADDP_S(n, d)      WORD $(0x7E30D800 | ((n) << 5) | (d))

// func L1NormNEONAsm(src *float32, count int) float32
TEXT ·L1NormNEONAsm(SB), NOSPLIT, $0-20
    MOVD src+0(FP), R0
    MOVD count+8(FP), R1

    VEOR V16.B16, V16.B16, V16.B16

l1_loop4:
    CMP  $4, R1
    BLT  l1_reduce
    VLD1.P 16(R0), [V0.S4]
    VFABS_S4(0, 0)
    VFADD_S4(0, 16, 16)
    SUB  $4, R1
    B    l1_loop4

l1_reduce:
    VFADDP_S4(16, 16, 16)
    FADDP_S(16, 0)

    CBZ  R1, l1_done

l1_scalar_loop:
    FMOVS (R0), F1
    FABSS F1, F1
    FADDS F1, F0, F0
    ADD  $4, R0
    SUB  $1, R1
    CBNZ R1, l1_scalar_loop

l1_done:
    FMOVS F0, ret+16(FP)
    RET
