// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON max-reduce for float32. Four parallel accumulators initialised
// to -inf, then FMAX across 16-lane stripes; folded with FMAX + FMAXV
// at the end to a single scalar. Used by softmax (the max shift) and
// by reduce_max / argmax kernels.
//
// Go scalar reference walks element-by-element with `if v > max { max
// = v }`. FCMGT (used internally by FMAX max-num) returns false on
// NaN, so FMAX/FMAXV match the scalar behavior bit-for-bit when no
// NaNs are present. With NaN, FMAX uses maxnum semantics (NaN→other)
// while the scalar reference returns the running max (which can be
// NaN once seen). Callers that need exact NaN semantics use the
// scalar path; for softmax this isn't an issue.

#include "textflag.h"

// FMAX vector .4S: 0|0|0|01110|0|sz|1|Rm|11110|1|Rn|Rd
// For sz=0 (single), Q=1: 0|1|0|01110|0|0|1|Rm|11110|1|Rn|Rd
// = 0_1_0_01110_001_Rm_111101_Rn_Rd
// = 0x4E20F400
#define VFMAX_S4(m, n, d) WORD $(0x4E20F400 | ((m) << 16) | ((n) << 5) | (d))
// FMAXV (vector across), single-precision .4S: reduces 4 S lanes of
// Vn into S Rd.
// 0|1|0|01110|10|11000|01111|10|Rn|Rd
// = 0x6E30F800
// Hmm need to verify. From ARM ARM: FMAXV V_d.S, V_n.4S
// 0|Q|U|01110|0|sz|11000|01111|10|Rn|Rd
// For Q=1, sz=0, U=1: 0|1|1|01110|0|0|11000|01111|10|nnnnn|ddddd
// = 0_1_1_01110_0_0_11000_01111_10_nnnnn_ddddd
// Binary: 0110_1110_0011_0000_1111_1000_0000_0000 = 0x6E30F800
#define VFMAXV_S4(n, d) WORD $(0x6E30F800 | ((n) << 5) | (d))

// func ReduceMaxFloat32NEONAsm(src *float32, n int) float32
TEXT ·ReduceMaxFloat32NEONAsm(SB), NOSPLIT, $0-20
    MOVD src+0(FP), R0
    MOVD n+8(FP), R1

    // Initialize four accumulators to -inf. -inf as f32 = 0xFF800000.
    // We can't easily move an immediate large negative into a NEON
    // register, so load the first element and use that as initial,
    // then loop. Edge case: n=0 → return 0 (callers check).
    CBZ  R1, reduce_max_done

    // Initialize V16-V19 with the first element broadcast.
    FMOVS (R0), F16
    VDUP V16.S[0], V16.S4
    VMOV V16.B16, V17.B16
    VMOV V16.B16, V18.B16
    VMOV V16.B16, V19.B16

reduce_max_loop16:
    CMP  $16, R1
    BLT  reduce_max_loop4
    VLD1.P 64(R0), [V0.S4, V1.S4, V2.S4, V3.S4]
    VFMAX_S4(0, 16, 16)
    VFMAX_S4(1, 17, 17)
    VFMAX_S4(2, 18, 18)
    VFMAX_S4(3, 19, 19)
    SUB  $16, R1
    B    reduce_max_loop16

reduce_max_loop4:
    CMP  $4, R1
    BLT  reduce_max_scalar_tail
    VLD1.P 16(R0), [V0.S4]
    VFMAX_S4(0, 16, 16)
    SUB  $4, R1
    B    reduce_max_loop4

reduce_max_scalar_tail:
    // Fold the 4 accumulators into V16.
    VFMAX_S4(17, 16, 16)
    VFMAX_S4(18, 16, 16)
    VFMAX_S4(19, 16, 16)
    // Reduce V16's 4 lanes to scalar in F0.
    VFMAXV_S4(16, 0)

    CBZ  R1, reduce_max_finalize

reduce_max_scalar_loop:
    FMOVS (R0), F1
    // F0 = max(F0, F1). Use the same FCSEL trick as the binary max
    // kernel for NaN-non-propagating semantics matching Go.
    FCMPS F1, F0
    FCSELS GT, F0, F1, F0
    ADD  $4, R0
    SUB  $1, R1
    CBNZ R1, reduce_max_scalar_loop

reduce_max_finalize:
    FMOVS F0, ret+16(FP)
    RET

reduce_max_done:
    FMOVS ZR, F0
    FMOVS F0, ret+16(FP)
    RET
