// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0

#include "textflag.h"

// FMIN vector .4S: 0|1|0|01110|10|1|Rm|11110|1|Rn|Rd = 0x4EA0F400
#define VFMIN_S4(m, n, d) WORD $(0x4EA0F400 | ((m) << 16) | ((n) << 5) | (d))
// FMINV across .4S: 0|1|1|01110|10|11000|01111|10|Rn|Rd = 0x6EB0F800
#define VFMINV_S4(n, d) WORD $(0x6EB0F800 | ((n) << 5) | (d))

// func ReduceMinFloat32NEONAsm(src *float32, n int) float32
TEXT ·ReduceMinFloat32NEONAsm(SB), NOSPLIT, $0-20
    MOVD src+0(FP), R0
    MOVD n+8(FP), R1

    CBZ  R1, reduce_min_done

    // Initialize V16-V19 to first element.
    FMOVS (R0), F16
    VDUP V16.S[0], V16.S4
    WORD $(0x4EA01C00 | (16 << 16) | (16 << 5) | 17)
    WORD $(0x4EA01C00 | (16 << 16) | (16 << 5) | 18)
    WORD $(0x4EA01C00 | (16 << 16) | (16 << 5) | 19)

reduce_min_loop16:
    CMP  $16, R1
    BLT  reduce_min_loop4
    VLD1.P 64(R0), [V0.S4, V1.S4, V2.S4, V3.S4]
    VFMIN_S4(0, 16, 16)
    VFMIN_S4(1, 17, 17)
    VFMIN_S4(2, 18, 18)
    VFMIN_S4(3, 19, 19)
    SUB  $16, R1
    B    reduce_min_loop16

reduce_min_loop4:
    CMP  $4, R1
    BLT  reduce_min_scalar_tail
    VLD1.P 16(R0), [V0.S4]
    VFMIN_S4(0, 16, 16)
    SUB  $4, R1
    B    reduce_min_loop4

reduce_min_scalar_tail:
    VFMIN_S4(17, 16, 16)
    VFMIN_S4(18, 16, 16)
    VFMIN_S4(19, 16, 16)
    VFMINV_S4(16, 0)

    CBZ  R1, reduce_min_finalize

reduce_min_scalar_loop:
    FMOVS (R0), F1
    FCMPS F1, F0
    FCSELS LT, F0, F1, F0
    ADD  $4, R0
    SUB  $1, R1
    CBNZ R1, reduce_min_scalar_loop

reduce_min_finalize:
    FMOVS F0, ret+16(FP)
    RET

reduce_min_done:
    FMOVS ZR, F0
    FMOVS F0, ret+16(FP)
    RET
