// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON product reduction for f32. Four parallel accumulators init to
// 1.0, FMUL across stripes, final fold + horizontal multiply.

#include "textflag.h"

#define VFMUL_S4(m, n, d) WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))

// func ReduceProdFloat32NEONAsm(src *float32, n int) float32
TEXT ·ReduceProdFloat32NEONAsm(SB), NOSPLIT, $0-20
    MOVD src+0(FP), R0
    MOVD n+8(FP), R1

    CBZ  R1, prod_zero

    // Initialize V16-V19 to 1.0 broadcast.
    MOVD $0x3F800000, R6
    VMOV R6, V16.S[0]
    VDUP V16.S[0], V16.S4
    WORD $(0x4EA01C00 | (16 << 16) | (16 << 5) | 17)
    WORD $(0x4EA01C00 | (16 << 16) | (16 << 5) | 18)
    WORD $(0x4EA01C00 | (16 << 16) | (16 << 5) | 19)

prod_loop16:
    CMP  $16, R1
    BLT  prod_loop4
    VLD1.P 64(R0), [V0.S4, V1.S4, V2.S4, V3.S4]
    VFMUL_S4(0, 16, 16)
    VFMUL_S4(1, 17, 17)
    VFMUL_S4(2, 18, 18)
    VFMUL_S4(3, 19, 19)
    SUB  $16, R1
    B    prod_loop16

prod_loop4:
    CMP  $4, R1
    BLT  prod_scalar_tail
    VLD1.P 16(R0), [V0.S4]
    VFMUL_S4(0, 16, 16)
    SUB  $4, R1
    B    prod_loop4

prod_scalar_tail:
    VFMUL_S4(17, 16, 16)
    VFMUL_S4(18, 16, 16)
    VFMUL_S4(19, 16, 16)
    // Horizontal product across V16.S4 lanes via 3 FMULS on extracted lanes.
    VMOV V16.S[0], V20.S[0]
    VMOV V16.S[1], V21.S[0]
    VMOV V16.S[2], V22.S[0]
    VMOV V16.S[3], V23.S[0]
    FMOVS F20, F0
    FMOVS F21, F1
    FMULS F1, F0, F0
    FMOVS F22, F1
    FMULS F1, F0, F0
    FMOVS F23, F1
    FMULS F1, F0, F0

    CBZ  R1, prod_finalize

prod_scalar_loop:
    FMOVS (R0), F1
    FMULS F1, F0, F0
    ADD  $4, R0
    SUB  $1, R1
    CBNZ R1, prod_scalar_loop

prod_finalize:
    FMOVS F0, ret+16(FP)
    RET

prod_zero:
    FMOVS ZR, F0
    FMOVS F0, ret+16(FP)
    RET
