// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON sum reduction for bf16 with f32 accumulation. Inputs are
// widened bf16→f32 via VZIP{1,2} with a zero halfword vector, then
// accumulated across four parallel .S4 lanes. The final horizontal
// reduce produces a single f32, narrowed to bf16 via shift-right-16.
//
// f32 accumulation matches AGENTS.md §5.5 mixed-dtype convention:
// bf16/fp16 inputs always accumulate in f32. The 24-bit mantissa of
// f32 is more than enough for any sum of bf16 inputs (which have only
// 8 mantissa bits each).

#include "textflag.h"
#include "../neon_bf16_macros.inc"

// FADD vector .4S: 0x4E20D400 base
#define VFADD_S4(m, n, d) WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
// FADDP scalar Sd, Vn.2S: pairwise add of S lanes (sz=0)
// 0|1|0|11110|0|0|1|10000|11011|10|Rn|Rd = 0x7E30D800
#define FADDP_S(n, d) WORD $(0x7E30D800 | ((n) << 5) | (d))

// func SumBFloat16NEONAsm(src *uint16, n int) uint16
TEXT ·SumBFloat16NEONAsm(SB), NOSPLIT, $0-18
    MOVD src+0(FP), R0
    MOVD n+8(FP), R1

    // V31 = 0 (used both as widening zero and below as scratch)
    VEOR V31.B16, V31.B16, V31.B16
    // Four parallel f32x4 accumulators.
    VEOR V16.B16, V16.B16, V16.B16
    VEOR V17.B16, V17.B16, V17.B16
    VEOR V18.B16, V18.B16, V18.B16
    VEOR V19.B16, V19.B16, V19.B16

sum_bf16_loop16:
    CMP  $16, R1
    BLT  sum_bf16_loop8
    VLD1.P 32(R0), [V0.H8, V1.H8]
    BF16_BITS_TO_F32_LOW(V0.H8, V4.H8)
    BF16_BITS_TO_F32_HIGH(V0.H8, V5.H8)
    BF16_BITS_TO_F32_LOW(V1.H8, V6.H8)
    BF16_BITS_TO_F32_HIGH(V1.H8, V7.H8)
    VFADD_S4(4, 16, 16)
    VFADD_S4(5, 17, 17)
    VFADD_S4(6, 18, 18)
    VFADD_S4(7, 19, 19)
    SUB  $16, R1
    B    sum_bf16_loop16

sum_bf16_loop8:
    CMP  $8, R1
    BLT  sum_bf16_reduce
    VLD1.P 16(R0), [V0.H8]
    BF16_BITS_TO_F32_LOW(V0.H8, V4.H8)
    BF16_BITS_TO_F32_HIGH(V0.H8, V5.H8)
    VFADD_S4(4, 16, 16)
    VFADD_S4(5, 17, 17)
    SUB  $8, R1
    B    sum_bf16_loop8

sum_bf16_reduce:
    // Fold the four .S4 accumulators into V16.S4.
    VFADD_S4(17, 16, 16)
    VFADD_S4(18, 16, 16)
    VFADD_S4(19, 16, 16)

    // Two rounds of FADDP reduce four S lanes to one in F0.
    // FADDP V16.S4, V16.S4, V16.S4 — pairwise add gives 2 valid lanes
    WORD $(0x6E30D400 | (16 << 16) | (16 << 5) | 16)  // FADDP V16, V16, V16 (.4S)
    FADDP_S(16, 0)

    // V31 holds zero; F1 = 0 for the tail accumulator.
    FMOVS ZR, F1

    CBZ  R1, sum_bf16_finalize

sum_bf16_scalar_loop:
    MOVHU.P 2(R0), R2
    LSL  $16, R2, R2
    FMOVS R2, F1
    FADDS F1, F0, F0
    SUB  $1, R1
    CBNZ R1, sum_bf16_scalar_loop

sum_bf16_finalize:
    BF16_RNE_SCALAR_F0_TO(R2)
    MOVH R2, ret+16(FP)
    RET
