// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON sum reduction for fp16: native .8H add in V24, f32 accumulation via
// FCVTL on partial sums (not per-lane input widen).

#include "textflag.h"

#define VFADD_H8(m, n, d)  WORD $(0x4E401400 | ((m) << 16) | ((n) << 5) | (d))
#define VFCVTL_4S(n, d)     WORD $(0x0E217800 | ((n) << 5) | (d))
#define VFCVTL2_4S(n, d)    WORD $(0x4E217800 | ((n) << 5) | (d))
#define VFADD_S4(m, n, d)   WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
#define FADDP_S(n, d)       WORD $(0x7E30D800 | ((n) << 5) | (d))

// func SumFloat16NEONAsm(src *uint16, n int) uint16
TEXT ·SumFloat16NEONAsm(SB), NOSPLIT, $0-18
	MOVD src+0(FP), R0
	MOVD n+8(FP), R1

	VEOR V16.B16, V16.B16, V16.B16
	VEOR V17.B16, V17.B16, V17.B16
	VEOR V18.B16, V18.B16, V18.B16
	VEOR V19.B16, V19.B16, V19.B16

sum_fp16_loop16:
	CMP  $16, R1
	BLT  sum_fp16_loop8
	VLD1.P 32(R0), [V0.H8, V1.H8]
	VEOR V24.B16, V24.B16, V24.B16
	VFADD_H8(0, 24, 24)
	VFADD_H8(1, 24, 24)
	VFCVTL_4S(24, 4)
	VFCVTL2_4S(24, 5)
	VFADD_S4(4, 16, 16)
	VFADD_S4(5, 17, 17)
	SUB  $16, R1
	B    sum_fp16_loop16

sum_fp16_loop8:
	CMP  $8, R1
	BLT  sum_fp16_reduce
	VLD1.P 16(R0), [V0.H8]
	VEOR V24.B16, V24.B16, V24.B16
	VFADD_H8(0, 24, 24)
	VFCVTL_4S(24, 4)
	VFCVTL2_4S(24, 5)
	VFADD_S4(4, 16, 16)
	VFADD_S4(5, 17, 17)
	SUB  $8, R1
	B    sum_fp16_loop8

sum_fp16_reduce:
	VFADD_S4(17, 16, 16)
	VFADD_S4(18, 16, 16)
	VFADD_S4(19, 16, 16)
	WORD $(0x6E30D400 | (16 << 16) | (16 << 5) | 16)
	FADDP_S(16, 0)

	CBZ  R1, sum_fp16_finalize

sum_fp16_scalar_loop:
	MOVHU.P 2(R0), R2
	VMOV R2, V0.H[0]
	VEOR V24.B16, V24.B16, V24.B16
	VFADD_H8(0, 24, 24)
	VFCVTL_4S(24, 4)
	VMOV V4.S[0], R2
	FMOVS R2, F1
	FADDS F1, F0, F0
	SUB  $1, R1
	CBNZ R1, sum_fp16_scalar_loop

sum_fp16_finalize:
	FCVTSH F0, F0
	FMOVS F0, R2
	MOVH R2, ret+16(FP)
	RET
