// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON sum reduction for fp16 with f32 accumulation, mirroring the
// BF16 sum reduction structure. Inputs are widened via FCVTL /
// FCVTL2 (single NEON instructions), accumulated across four parallel
// .S4 lanes, horizontally reduced, and the final f32 is narrowed
// back to fp16 via FCVT (scalar fp32→fp16, plan9 mnemonic FCVTHS).

#include "textflag.h"

#define VFCVTL_4S(n, d)   WORD $(0x0E217800 | ((n) << 5) | (d))
#define VFCVTL2_4S(n, d)  WORD $(0x4E217800 | ((n) << 5) | (d))
#define VFADD_S4(m, n, d) WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
#define FADDP_S(n, d)     WORD $(0x7E30D800 | ((n) << 5) | (d))

// func SumFloat16NEONAsm(src *uint16, n int) uint16
TEXT ·SumFloat16NEONAsm(SB), NOSPLIT, $0-18
    MOVD src+0(FP), R0
    MOVD n+8(FP), R1

    VEOR V16.B16, V16.B16, V16.B16
    VEOR V17.B16, V17.B16, V17.B16
    VEOR V18.B16, V18.B16, V18.B16
    VEOR V19.B16, V19.B16, V19.B16

sum_fp16_loop16:
    CMP  $16, R1
    BLT  sum_fp16_loop8
    VLD1.P 32(R0), [V0.H8, V1.H8]
    VFCVTL_4S(0, 4)
    VFCVTL2_4S(0, 5)
    VFCVTL_4S(1, 6)
    VFCVTL2_4S(1, 7)
    VFADD_S4(4, 16, 16)
    VFADD_S4(5, 17, 17)
    VFADD_S4(6, 18, 18)
    VFADD_S4(7, 19, 19)
    SUB  $16, R1
    B    sum_fp16_loop16

sum_fp16_loop8:
    CMP  $8, R1
    BLT  sum_fp16_reduce
    VLD1.P 16(R0), [V0.H8]
    VFCVTL_4S(0, 4)
    VFCVTL2_4S(0, 5)
    VFADD_S4(4, 16, 16)
    VFADD_S4(5, 17, 17)
    SUB  $8, R1
    B    sum_fp16_loop8

sum_fp16_reduce:
    VFADD_S4(17, 16, 16)
    VFADD_S4(18, 16, 16)
    VFADD_S4(19, 16, 16)
    WORD $(0x6E30D400 | (16 << 16) | (16 << 5) | 16)  // FADDP V16.4S
    FADDP_S(16, 0)

    CBZ  R1, sum_fp16_finalize

sum_fp16_scalar_loop:
    MOVHU.P 2(R0), R2
    VMOV R2, V1.H[0]
    VFCVTL_4S(1, 4)
    VMOV V4.S[0], R2
    FMOVS R2, F1
    FADDS F1, F0, F0
    SUB  $1, R1
    CBNZ R1, sum_fp16_scalar_loop

sum_fp16_finalize:
    // Narrow f32 in F0 to fp16. plan9 mnemonic FCVTSH = "FCVT from
    // Single to Half" — type=00 (src=single), opc=11 (dst=half).
    FCVTSH F0, F0
    FMOVS F0, R2
    MOVH R2, ret+16(FP)
    RET
