// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON sum reduction for float32. The scalar reference accumulates
// into a single f64 to keep summation precision well-controlled across
// long inputs. This kernel mirrors that contract: every f32 lane is
// widened to f64 via FCVTL / FCVTL2 (one ARM instruction per pair),
// accumulated into four parallel D2 (f64x2) accumulators to expose
// instruction-level parallelism, and reduced to a single f64 at the
// end. The function returns the f32 cast of that f64, so it inherits
// the same rounding behavior as the scalar reference.

#include "textflag.h"

// FADD vector .2D: 0|1|0|01110|01|1|Rm|11010|1|Rn|Rd = 0x4E60D400
#define VFADD_D2(m, n, d)  WORD $(0x4E60D400 | ((m) << 16) | ((n) << 5) | (d))
// FCVTL Vd.2D, Vn.2S: 0x0E617800; FCVTL2 Vd.2D, Vn.4S: 0x4E617800
#define FCVTL_2D(n, d)     WORD $(0x0E617800 | ((n) << 5) | (d))
#define FCVTL2_2D(n, d)    WORD $(0x4E617800 | ((n) << 5) | (d))
// FADDP scalar Dd, Vn.2D (sz=1): 0|1|0|11110|01|1|10000|11011|10|Rn|Rd = 0x7E70D800
#define FADDP_D(n, d)      WORD $(0x7E70D800 | ((n) << 5) | (d))

// func SumFloat32NEONAsm(src *float32, n int) float32
TEXT ·SumFloat32NEONAsm(SB), NOSPLIT, $0-20
    MOVD src+0(FP), R0
    MOVD n+8(FP), R1

    // Zero the four f64 accumulators V16-V19 (.D2 each = 2 lanes).
    VEOR V16.B16, V16.B16, V16.B16
    VEOR V17.B16, V17.B16, V17.B16
    VEOR V18.B16, V18.B16, V18.B16
    VEOR V19.B16, V19.B16, V19.B16

sum_loop16:
    CMP  $16, R1
    BLT  sum_loop4
    VLD1.P 64(R0), [V0.S4, V1.S4, V2.S4, V3.S4]
    FCVTL_2D(0, 4)
    FCVTL2_2D(0, 5)
    FCVTL_2D(1, 6)
    FCVTL2_2D(1, 7)
    FCVTL_2D(2, 8)
    FCVTL2_2D(2, 9)
    FCVTL_2D(3, 10)
    FCVTL2_2D(3, 11)
    VFADD_D2(4, 16, 16)
    VFADD_D2(5, 17, 17)
    VFADD_D2(6, 18, 18)
    VFADD_D2(7, 19, 19)
    VFADD_D2(8, 16, 16)
    VFADD_D2(9, 17, 17)
    VFADD_D2(10, 18, 18)
    VFADD_D2(11, 19, 19)
    SUB  $16, R1
    B    sum_loop16

sum_loop4:
    CMP  $4, R1
    BLT  sum_reduce
    VLD1.P 16(R0), [V0.S4]
    FCVTL_2D(0, 4)
    FCVTL2_2D(0, 5)
    VFADD_D2(4, 16, 16)
    VFADD_D2(5, 17, 17)
    SUB  $4, R1
    B    sum_loop4

sum_reduce:
    // Fold the four D2 accumulators into V16.D2.
    VFADD_D2(17, 16, 16)
    VFADD_D2(18, 16, 16)
    VFADD_D2(19, 16, 16)

    // FADDP D0, V16.D2 — horizontal add of the two lanes into F0.
    FADDP_D(16, 0)

    // Scalar tail: each remaining f32 widened to f64 and added.
    CBZ  R1, sum_finalize

sum_scalar_loop:
    FMOVS (R0), F1
    FCVTSD F1, F1    // promote f32→f64 (FCVT D <-> S works on F regs)
    FADDD F1, F0, F0
    ADD  $4, R0
    SUB  $1, R1
    CBNZ R1, sum_scalar_loop

sum_finalize:
    // Narrow the f64 accumulator back to f32 for the result.
    FCVTDS F0, F0
    FMOVS F0, ret+16(FP)
    RET
