// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON Hawkes helpers. Callers precompute exponent arguments
// (-beta * delta) in a scratch buffer; these kernels apply vector
// exp and sum/store in V registers.

#include "textflag.h"

#define VFADD_S4(m, n, d)  WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFSUB_S4(m, n, d)  WORD $(0x4EA0D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_S4(m, n, d)  WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFMLA_S4(m, n, d)  WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFRINTN_S4(n, d)   WORD $(0x4E218800 | ((n) << 5) | (d))
#define VFCVTZS_S4(n, d)   WORD $(0x4EA1B800 | ((n) << 5) | (d))
#define VADD_S4(m, n, d)   WORD $(0x4EA08400 | ((m) << 16) | ((n) << 5) | (d))
#define VSHL_S4_BY23(n, d) WORD $(0x4F375400 | ((n) << 5) | (d))
#define VMOV_B16(src, dst) WORD $(0x4EA01C00 | ((src) << 16) | ((src) << 5) | (dst))

DATA  hawkesExpC<>+0(SB)/4, $1.4426950408889634
DATA  hawkesExpC<>+4(SB)/4, $0.6931471805599453
DATA  hawkesExpC<>+8(SB)/4, $127.0
DATA  hawkesExpC<>+12(SB)/4, $0.00019841270
DATA  hawkesExpC<>+16(SB)/4, $0.0013888889
DATA  hawkesExpC<>+20(SB)/4, $0.008333334
DATA  hawkesExpC<>+24(SB)/4, $0.041666667
DATA  hawkesExpC<>+28(SB)/4, $0.16666667
DATA  hawkesExpC<>+32(SB)/4, $0.5
DATA  hawkesExpC<>+36(SB)/4, $1.0
DATA  hawkesExpC<>+40(SB)/4, $1.0
GLOBL hawkesExpC<>(SB), 8, $44

#define HAWKES_EXP_V0_TO_V6 \
    VFMUL_S4(16, 0, 1) \
    VFRINTN_S4(1, 1) \
    VFMUL_S4(17, 1, 2) \
    VFSUB_S4(2, 0, 0) \
    VMOV_B16(19, 3) \
    VMOV_B16(20, 4) ; VFMLA_S4(0, 3, 4) \
    VMOV_B16(21, 3) ; VFMLA_S4(0, 4, 3) \
    VMOV_B16(22, 4) ; VFMLA_S4(0, 3, 4) \
    VMOV_B16(23, 3) ; VFMLA_S4(0, 4, 3) \
    VMOV_B16(24, 4) ; VFMLA_S4(0, 3, 4) \
    VMOV_B16(25, 3) ; VFMLA_S4(0, 4, 3) \
    VMOV_B16(26, 4) ; VFMLA_S4(0, 3, 4) \
    VFCVTZS_S4(1, 5) \
    VADD_S4(27, 5, 5) \
    VSHL_S4_BY23(5, 5) \
    VFMUL_S4(5, 4, 6)

// func HawkesExpSumNEONAsm(exponents *float32, n int) float32
TEXT ·HawkesExpSumNEONAsm(SB), NOSPLIT, $16-20
    MOVD exponents+0(FP), R0
    MOVD n+8(FP), R1
    MOVD $hawkesExpC<>(SB), R2
    FMOVS 0(R2), F16 ; VDUP V16.S[0], V16.S4
    FMOVS 4(R2), F17 ; VDUP V17.S[0], V17.S4
    FMOVS 8(R2), F18 ; VDUP V18.S[0], V18.S4
    FMOVS 12(R2), F19 ; VDUP V19.S[0], V19.S4
    FMOVS 16(R2), F20 ; VDUP V20.S[0], V20.S4
    FMOVS 20(R2), F21 ; VDUP V21.S[0], V21.S4
    FMOVS 24(R2), F22 ; VDUP V22.S[0], V22.S4
    FMOVS 28(R2), F23 ; VDUP V23.S[0], V23.S4
    FMOVS 32(R2), F24 ; VDUP V24.S[0], V24.S4
    FMOVS 36(R2), F25 ; VDUP V25.S[0], V25.S4
    FMOVS 40(R2), F26 ; VDUP V26.S[0], V26.S4
    VFCVTZS_S4(18, 27)
    VEOR V31.B16, V31.B16, V31.B16

hawkes_sum_loop4:
    CMP  $4, R1
    BLT  hawkes_sum_finalize
    VLD1.P 16(R0), [V0.S4]
    HAWKES_EXP_V0_TO_V6
    VFADD_S4(6, 31, 31)
    SUB  $4, R1
    B    hawkes_sum_loop4

hawkes_sum_finalize:
    MOVD RSP, R6
    VST1 [V31.S4], (R6)
    FMOVS (R6), F0
    FMOVS 4(R6), F1
    FMOVS 8(R6), F2
    FMOVS 12(R6), F3
    FADDS F1, F0, F0
    FADDS F2, F0, F0
    FADDS F3, F0, F0
    FMOVS F0, ret+16(FP)
    RET

// func HawkesScaledExpStoreNEONAsm(
//     exponents *float32,
//     alpha float32,
//     out *float32,
//     n int,
// )
TEXT ·HawkesScaledExpStoreNEONAsm(SB), NOSPLIT, $0-32
    MOVD exponents+0(FP), R0
    MOVD out+16(FP), R1
    MOVD n+24(FP), R2
    MOVD alpha+8(FP), R6
    VMOV R6, V30.S[0]
    VDUP V30.S[0], V30.S4
    MOVD $hawkesExpC<>(SB), R3
    FMOVS 0(R3), F16 ; VDUP V16.S[0], V16.S4
    FMOVS 4(R3), F17 ; VDUP V17.S[0], V17.S4
    FMOVS 8(R3), F18 ; VDUP V18.S[0], V18.S4
    FMOVS 12(R3), F19 ; VDUP V19.S[0], V19.S4
    FMOVS 16(R3), F20 ; VDUP V20.S[0], V20.S4
    FMOVS 20(R3), F21 ; VDUP V21.S[0], V21.S4
    FMOVS 24(R3), F22 ; VDUP V22.S[0], V22.S4
    FMOVS 28(R3), F23 ; VDUP V23.S[0], V23.S4
    FMOVS 32(R3), F24 ; VDUP V24.S[0], V24.S4
    FMOVS 36(R3), F25 ; VDUP V25.S[0], V25.S4
    FMOVS 40(R3), F26 ; VDUP V26.S[0], V26.S4
    VFCVTZS_S4(18, 27)

hawkes_store_loop4:
    CMP  $4, R2
    BLT  hawkes_store_done
    VLD1.P 16(R0), [V0.S4]
    HAWKES_EXP_V0_TO_V6
    VFMUL_S4(30, 6, 6)
    VST1.P [V6.S4], 16(R1)
    SUB  $4, R2
    B    hawkes_store_loop4

hawkes_store_done:
    RET
