// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON dot product for bf16 with f32 accumulation. Each pair (a, b)
// of bf16 lanes is widened to f32, multiplied via FMLA (single-rounded
// in f32), and accumulated across four parallel .S4 lanes. The final
// horizontal reduce produces a single f32, narrowed to bf16.

#include "textflag.h"
#include "../neon_bf16_macros.inc"

// FMLA vector .4S: 0x4E20CC00 base. Vd += Vn * Vm
#define VFMLA_S4(m, n, d) WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))
// FADD .4S: 0x4E20D400 base
#define VFADD_S4(m, n, d) WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
// FADDP scalar Sd, Vn.2S: 0x7E30D800 base
#define FADDP_S(n, d) WORD $(0x7E30D800 | ((n) << 5) | (d))

// func DotBFloat16NEONAsm(a, b *uint16, n int) uint16
TEXT ·DotBFloat16NEONAsm(SB), NOSPLIT, $0-26
    MOVD a+0(FP), R0
    MOVD b+8(FP), R1
    MOVD n+16(FP), R2

    VEOR V31.B16, V31.B16, V31.B16
    // Four parallel f32 accumulators.
    VEOR V16.B16, V16.B16, V16.B16
    VEOR V17.B16, V17.B16, V17.B16
    VEOR V18.B16, V18.B16, V18.B16
    VEOR V19.B16, V19.B16, V19.B16

dot_bf16_loop16:
    CMP  $16, R2
    BLT  dot_bf16_loop8
    VLD1.P 32(R0), [V0.H8, V1.H8]
    VLD1.P 32(R1), [V2.H8, V3.H8]
    BF16_BITS_TO_F32_LOW(V0.H8, V4.H8)
    BF16_BITS_TO_F32_HIGH(V0.H8, V5.H8)
    BF16_BITS_TO_F32_LOW(V1.H8, V6.H8)
    BF16_BITS_TO_F32_HIGH(V1.H8, V7.H8)
    BF16_BITS_TO_F32_LOW(V2.H8, V8.H8)
    BF16_BITS_TO_F32_HIGH(V2.H8, V9.H8)
    BF16_BITS_TO_F32_LOW(V3.H8, V10.H8)
    BF16_BITS_TO_F32_HIGH(V3.H8, V11.H8)
    VFMLA_S4(8, 4, 16)
    VFMLA_S4(9, 5, 17)
    VFMLA_S4(10, 6, 18)
    VFMLA_S4(11, 7, 19)
    SUB  $16, R2
    B    dot_bf16_loop16

dot_bf16_loop8:
    CMP  $8, R2
    BLT  dot_bf16_reduce
    VLD1.P 16(R0), [V0.H8]
    VLD1.P 16(R1), [V2.H8]
    BF16_BITS_TO_F32_LOW(V0.H8, V4.H8)
    BF16_BITS_TO_F32_HIGH(V0.H8, V5.H8)
    BF16_BITS_TO_F32_LOW(V2.H8, V8.H8)
    BF16_BITS_TO_F32_HIGH(V2.H8, V9.H8)
    VFMLA_S4(8, 4, 16)
    VFMLA_S4(9, 5, 17)
    SUB  $8, R2
    B    dot_bf16_loop8

dot_bf16_reduce:
    // Fold accumulators V16..V19 into V16.S4.
    VFADD_S4(17, 16, 16)
    VFADD_S4(18, 16, 16)
    VFADD_S4(19, 16, 16)
    // Pairwise → 2 valid lanes → 1 scalar.
    WORD $(0x6E30D400 | (16 << 16) | (16 << 5) | 16)  // FADDP V16.4S
    FADDP_S(16, 0)

    CBZ  R2, dot_bf16_finalize

dot_bf16_scalar_loop:
    MOVHU.P 2(R0), R3
    MOVHU.P 2(R1), R4
    LSL  $16, R3, R3
    LSL  $16, R4, R4
    FMOVS R3, F1
    FMOVS R4, F2
    FMULS F2, F1, F1
    FADDS F1, F0, F0
    SUB  $1, R2
    CBNZ R2, dot_bf16_scalar_loop

dot_bf16_finalize:
    BF16_RNE_SCALAR_F0_TO(R3)
    MOVH R3, ret+24(FP)
    RET
