// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON dot product for float32 with f64 accumulation. Scalar reference
// is sum(float64(a[i]) * float64(b[i])) cast to float32. NEON widens
// each pair to f64 before multiplying so the product never loses
// precision, FMLA accumulates into four parallel D2 (f64x2) lanes,
// then a horizontal reduce produces a single f64 narrowed to f32.

#include "textflag.h"

// FMLA vector .2D (fused multiply-add, f64): 0x4E60CC00 base
#define VFMLA_D2(m, n, d) WORD $(0x4E60CC00 | ((m) << 16) | ((n) << 5) | (d))
// FCVTL Vd.2D, Vn.2S: 0x0E617800; FCVTL2 Vd.2D, Vn.4S: 0x4E617800
#define FCVTL_2D(n, d)    WORD $(0x0E617800 | ((n) << 5) | (d))
#define FCVTL2_2D(n, d)   WORD $(0x4E617800 | ((n) << 5) | (d))
// FADD vector .2D: 0x4E60D400 base
#define VFADD_D2(m, n, d) WORD $(0x4E60D400 | ((m) << 16) | ((n) << 5) | (d))
// FADDP scalar Dd, Vn.2D: 0x7E70D800 base
#define FADDP_D(n, d)     WORD $(0x7E70D800 | ((n) << 5) | (d))

// func DotFloat32NEONAsm(a, b *float32, n int) float32
TEXT ·DotFloat32NEONAsm(SB), NOSPLIT, $0-28
    MOVD a+0(FP), R0
    MOVD b+8(FP), R1
    MOVD n+16(FP), R2

    // Four parallel f64x2 accumulators.
    VEOR V16.B16, V16.B16, V16.B16
    VEOR V17.B16, V17.B16, V17.B16
    VEOR V18.B16, V18.B16, V18.B16
    VEOR V19.B16, V19.B16, V19.B16

dot_loop8:
    CMP  $8, R2
    BLT  dot_loop4
    VLD1.P 32(R0), [V0.S4, V1.S4]
    VLD1.P 32(R1), [V4.S4, V5.S4]
    // Widen a's eight f32 lanes to four D2 (f64x2) vectors.
    FCVTL_2D(0, 8)
    FCVTL2_2D(0, 9)
    FCVTL_2D(1, 10)
    FCVTL2_2D(1, 11)
    // Widen b's eight f32 lanes to four D2 vectors.
    FCVTL_2D(4, 12)
    FCVTL2_2D(4, 13)
    FCVTL_2D(5, 14)
    FCVTL2_2D(5, 15)
    // Fused multiply-add into the four accumulators.
    VFMLA_D2(12, 8, 16)
    VFMLA_D2(13, 9, 17)
    VFMLA_D2(14, 10, 18)
    VFMLA_D2(15, 11, 19)
    SUB  $8, R2
    B    dot_loop8

dot_loop4:
    CMP  $4, R2
    BLT  dot_reduce
    VLD1.P 16(R0), [V0.S4]
    VLD1.P 16(R1), [V4.S4]
    FCVTL_2D(0, 8)
    FCVTL2_2D(0, 9)
    FCVTL_2D(4, 12)
    FCVTL2_2D(4, 13)
    VFMLA_D2(12, 8, 16)
    VFMLA_D2(13, 9, 17)
    SUB  $4, R2
    B    dot_loop4

dot_reduce:
    // Fold the four D2 accumulators into V16.
    VFADD_D2(17, 16, 16)
    VFADD_D2(18, 16, 16)
    VFADD_D2(19, 16, 16)
    // Horizontal add of V16.D2 into scalar F0.
    FADDP_D(16, 0)

    CBZ  R2, dot_finalize

dot_scalar_loop:
    FMOVS (R0), F1
    FMOVS (R1), F2
    FCVTSD F1, F1
    FCVTSD F2, F2
    FMULD F2, F1, F1
    FADDD F1, F0, F0
    ADD  $4, R0
    ADD  $4, R1
    SUB  $1, R2
    CBNZ R2, dot_scalar_loop

dot_finalize:
    FCVTDS F0, F0
    FMOVS F0, ret+24(FP)
    RET
