// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON dot product for fp16 with f32 accumulation. Each pair of fp16
// lanes is widened to f32 via FCVTL/FCVTL2, multiplied-accumulated
// via FMLA into four parallel .S4 accumulators. The final horizontal
// reduce produces an f32 narrowed to fp16 via FCVTSH.

#include "textflag.h"

#define VFCVTL_4S(n, d)   WORD $(0x0E217800 | ((n) << 5) | (d))
#define VFCVTL2_4S(n, d)  WORD $(0x4E217800 | ((n) << 5) | (d))
#define VFADD_S4(m, n, d) WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMLA_S4(m, n, d) WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))
#define FADDP_S(n, d)     WORD $(0x7E30D800 | ((n) << 5) | (d))

// func DotFloat16NEONAsm(a, b *uint16, n int) uint16
TEXT ·DotFloat16NEONAsm(SB), NOSPLIT, $0-26
    MOVD a+0(FP), R0
    MOVD b+8(FP), R1
    MOVD n+16(FP), R2

    VEOR V16.B16, V16.B16, V16.B16
    VEOR V17.B16, V17.B16, V17.B16
    VEOR V18.B16, V18.B16, V18.B16
    VEOR V19.B16, V19.B16, V19.B16

dot_fp16_loop16:
    CMP  $16, R2
    BLT  dot_fp16_loop8
    VLD1.P 32(R0), [V0.H8, V1.H8]
    VLD1.P 32(R1), [V2.H8, V3.H8]
    VFCVTL_4S(0, 4)
    VFCVTL2_4S(0, 5)
    VFCVTL_4S(1, 6)
    VFCVTL2_4S(1, 7)
    VFCVTL_4S(2, 8)
    VFCVTL2_4S(2, 9)
    VFCVTL_4S(3, 10)
    VFCVTL2_4S(3, 11)
    VFMLA_S4(8, 4, 16)
    VFMLA_S4(9, 5, 17)
    VFMLA_S4(10, 6, 18)
    VFMLA_S4(11, 7, 19)
    SUB  $16, R2
    B    dot_fp16_loop16

dot_fp16_loop8:
    CMP  $8, R2
    BLT  dot_fp16_reduce
    VLD1.P 16(R0), [V0.H8]
    VLD1.P 16(R1), [V2.H8]
    VFCVTL_4S(0, 4)
    VFCVTL2_4S(0, 5)
    VFCVTL_4S(2, 8)
    VFCVTL2_4S(2, 9)
    VFMLA_S4(8, 4, 16)
    VFMLA_S4(9, 5, 17)
    SUB  $8, R2
    B    dot_fp16_loop8

dot_fp16_reduce:
    VFADD_S4(17, 16, 16)
    VFADD_S4(18, 16, 16)
    VFADD_S4(19, 16, 16)
    WORD $(0x6E30D400 | (16 << 16) | (16 << 5) | 16)  // FADDP V16.4S
    FADDP_S(16, 0)

    CBZ  R2, dot_fp16_finalize

dot_fp16_scalar_loop:
    MOVHU.P 2(R0), R3
    MOVHU.P 2(R1), R4
    VMOV R3, V1.H[0]
    VMOV R4, V2.H[0]
    VFCVTL_4S(1, 4)
    VFCVTL_4S(2, 8)
    VMOV V4.S[0], R3
    VMOV V8.S[0], R4
    FMOVS R3, F1
    FMOVS R4, F2
    FMULS F2, F1, F1
    FADDS F1, F0, F0
    SUB  $1, R2
    CBNZ R2, dot_fp16_scalar_loop

dot_fp16_finalize:
    FCVTSH F0, F0
    FMOVS F0, R3
    MOVH R3, ret+24(FP)
    RET
