// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON int8 dot product with int32 accumulation, using SDOT
// (FEAT_DotProd, ARMv8.2+). Each SDOT instruction computes four
// independent int8×int8 partial dots of length 4 each, accumulating
// into a single int32 destination lane:
//
//   dst.s[i] += sum_{j=0..3} a.b[4i+j] * b.b[4i+j]
//
// So one SDOT consumes 16 int8 lanes from each operand and produces
// 4 int32 results. We use 4 accumulator vectors (V16-V19) and run
// SDOT against the same 16-byte input vectors, then horizontally
// reduce at the end.

#include "textflag.h"

// SDOT Vd.4S, Vn.16B, Vm.16B (FEAT_DotProd)
// 0|1|0|01110|10|0|Rm|10010|1|Rn|Rd = 0x4E809400
#define VSDOT_S4(m, n, d) WORD $(0x4E809400 | ((m) << 16) | ((n) << 5) | (d))
// ADDV vector reduction across 4 int32 lanes into a scalar S register
// 0|1|0|01110|10|11000|11011|10|Rn|Rd = 0x4EB1B800
#define VADDV_S4(n, d)    WORD $(0x4EB1B800 | ((n) << 5) | (d))
// ADD vector .4S (integer)
#define VADD_S4(m, n, d)  WORD $(0x4EA08400 | ((m) << 16) | ((n) << 5) | (d))

// func DotInt8NEONAsm(a, b *int8, n int) int32
TEXT ·DotInt8NEONAsm(SB), NOSPLIT, $0-28
    MOVD a+0(FP), R0
    MOVD b+8(FP), R1
    MOVD n+16(FP), R2

    // Four parallel int32x4 accumulators.
    VEOR V16.B16, V16.B16, V16.B16
    VEOR V17.B16, V17.B16, V17.B16
    VEOR V18.B16, V18.B16, V18.B16
    VEOR V19.B16, V19.B16, V19.B16

dot_int8_loop64:
    CMP  $64, R2
    BLT  dot_int8_loop16
    VLD1.P 64(R0), [V0.B16, V1.B16, V2.B16, V3.B16]
    VLD1.P 64(R1), [V4.B16, V5.B16, V6.B16, V7.B16]
    VSDOT_S4(4, 0, 16)
    VSDOT_S4(5, 1, 17)
    VSDOT_S4(6, 2, 18)
    VSDOT_S4(7, 3, 19)
    SUB  $64, R2
    B    dot_int8_loop64

dot_int8_loop16:
    CMP  $16, R2
    BLT  dot_int8_reduce
    VLD1.P 16(R0), [V0.B16]
    VLD1.P 16(R1), [V4.B16]
    VSDOT_S4(4, 0, 16)
    SUB  $16, R2
    B    dot_int8_loop16

dot_int8_reduce:
    // Fold the four accumulators into V16.
    VADD_S4(17, 16, 16)
    VADD_S4(18, 16, 16)
    VADD_S4(19, 16, 16)
    // Sum the 4 int32 lanes of V16 into S0.
    VADDV_S4(16, 0)

    CBZ  R2, dot_int8_finalize

    // Move S0 into a GP register for scalar accumulation.
    VMOV V0.S[0], R3

dot_int8_scalar_loop:
    MOVB (R0), R4
    MOVB (R1), R5
    SXTB R4, R4
    SXTB R5, R5
    MUL  R5, R4, R4
    ADDW R4, R3, R3
    ADD  $1, R0
    ADD  $1, R1
    SUB  $1, R2
    CBNZ R2, dot_int8_scalar_loop

    MOVW R3, ret+24(FP)
    RET

dot_int8_finalize:
    VMOV V0.S[0], R3
    MOVW R3, ret+24(FP)
    RET
